// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_jobcategories.proto

package jobs

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetJobCategoriesRequest) Validate() error {
	return nil
}
func (this *GetJobCategoriesResponseWrapper) Validate() error {
	return nil
}
