// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_jobcategories.proto

package jobs

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//GetJobCategories请求
type GetJobCategoriesRequest struct {
	//
	//menuId过虑
	MenuId               string   `protobuf:"bytes,1,opt,name=menuId,proto3" json:"menuId" form:"menuId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobCategoriesRequest) Reset()         { *m = GetJobCategoriesRequest{} }
func (m *GetJobCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobCategoriesRequest) ProtoMessage()    {}
func (*GetJobCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e006344805881d13, []int{0}
}
func (m *GetJobCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobCategoriesRequest.Unmarshal(m, b)
}
func (m *GetJobCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobCategoriesRequest.Marshal(b, m, deterministic)
}
func (m *GetJobCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobCategoriesRequest.Merge(m, src)
}
func (m *GetJobCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobCategoriesRequest.Size(m)
}
func (m *GetJobCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobCategoriesRequest proto.InternalMessageInfo

func (m *GetJobCategoriesRequest) GetMenuId() string {
	if m != nil {
		return m.MenuId
	}
	return ""
}

//
//GetJobCategoriesApi返回
type GetJobCategoriesResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 []string `protobuf:"bytes,4,rep,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobCategoriesResponseWrapper) Reset()         { *m = GetJobCategoriesResponseWrapper{} }
func (m *GetJobCategoriesResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*GetJobCategoriesResponseWrapper) ProtoMessage()    {}
func (*GetJobCategoriesResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_e006344805881d13, []int{1}
}
func (m *GetJobCategoriesResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobCategoriesResponseWrapper.Unmarshal(m, b)
}
func (m *GetJobCategoriesResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobCategoriesResponseWrapper.Marshal(b, m, deterministic)
}
func (m *GetJobCategoriesResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobCategoriesResponseWrapper.Merge(m, src)
}
func (m *GetJobCategoriesResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_GetJobCategoriesResponseWrapper.Size(m)
}
func (m *GetJobCategoriesResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobCategoriesResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobCategoriesResponseWrapper proto.InternalMessageInfo

func (m *GetJobCategoriesResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetJobCategoriesResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *GetJobCategoriesResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetJobCategoriesResponseWrapper) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetJobCategoriesRequest)(nil), "jobs.GetJobCategoriesRequest")
	proto.RegisterType((*GetJobCategoriesResponseWrapper)(nil), "jobs.GetJobCategoriesResponseWrapper")
}

func init() { proto.RegisterFile("get_jobcategories.proto", fileDescriptor_e006344805881d13) }

var fileDescriptor_e006344805881d13 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x89, 0x4d, 0x0b, 0xdd, 0x2a, 0xea, 0x1e, 0x6c, 0xa8, 0x87, 0x94, 0x15, 0xa4, 0x1e,
	0x6c, 0x0f, 0x5e, 0xc4, 0x63, 0x55, 0x44, 0x8f, 0x7b, 0xf1, 0x28, 0xd9, 0x64, 0xba, 0xa6, 0x34,
	0x99, 0x75, 0xb3, 0x01, 0x7d, 0x48, 0x5f, 0x21, 0x0f, 0x91, 0x27, 0x90, 0xcc, 0x16, 0x5b, 0xe8,
	0x29, 0x99, 0xff, 0xfb, 0xff, 0x7f, 0x86, 0x65, 0x63, 0x0d, 0xee, 0x63, 0x8d, 0x2a, 0x4d, 0x1c,
	0x68, 0xb4, 0x39, 0x54, 0x73, 0x63, 0xd1, 0x21, 0x0f, 0xd7, 0xa8, 0xaa, 0xc9, 0xad, 0xce, 0xdd,
	0x67, 0xad, 0xe6, 0x29, 0x16, 0x0b, 0x8d, 0x1a, 0x17, 0x04, 0x55, 0xbd, 0xa2, 0x89, 0x06, 0xfa,
	0xf3, 0xa1, 0xc9, 0xa5, 0x46, 0xd4, 0x1b, 0xd8, 0xb9, 0xa0, 0x30, 0xee, 0xc7, 0x43, 0xf1, 0xc4,
	0xc6, 0x2f, 0xe0, 0xde, 0x50, 0x3d, 0xfe, 0xef, 0x92, 0xf0, 0x55, 0x43, 0xe5, 0xf8, 0x0d, 0x1b,
	0x14, 0x50, 0xd6, 0xaf, 0x59, 0x14, 0x4c, 0x83, 0xd9, 0x70, 0x79, 0xde, 0x36, 0xf1, 0xc9, 0x0a,
	0x6d, 0xf1, 0x20, 0xbc, 0x2e, 0xe4, 0xd6, 0x20, 0x7e, 0x03, 0x16, 0x1f, 0xd6, 0x54, 0x06, 0xcb,
	0x0a, 0xde, 0x6d, 0x62, 0x0c, 0x58, 0x7e, 0xc5, 0xc2, 0x14, 0x33, 0xa0, 0xb2, 0xfe, 0xf2, 0xb4,
	0x6d, 0xe2, 0x91, 0x2f, 0xeb, 0x54, 0x21, 0x09, 0xf2, 0x7b, 0x36, 0xea, 0xbe, 0xcf, 0xdf, 0x66,
	0x93, 0xe4, 0x65, 0x74, 0x44, 0x8b, 0x2f, 0xda, 0x26, 0xe6, 0x3b, 0xef, 0x16, 0x0a, 0xb9, 0x6f,
	0xe5, 0xd7, 0xac, 0x0f, 0xd6, 0xa2, 0x8d, 0x7a, 0x94, 0x39, 0x6b, 0x9b, 0xf8, 0xd8, 0x67, 0x48,
	0x16, 0xd2, 0xe3, 0xee, 0x8c, 0x2c, 0x71, 0x49, 0x14, 0x4e, 0x7b, 0xb3, 0xe1, 0xfe, 0x19, 0x9d,
	0x2a, 0x24, 0x41, 0x35, 0xa0, 0xc7, 0xb9, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x90, 0x4f, 0xf8,
	0x71, 0x89, 0x01, 0x00, 0x00,
}
