// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: update_menu.proto

package menu

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
//UpdateMenu请求
type UpdateMenuRequest struct {
	//
	//菜单id
	MenusId string `protobuf:"bytes,1,opt,name=menusId,proto3" json:"menusId" form:"menusId"`
	//
	//菜单名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	//
	//菜单图标
	Icon string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon" form:"icon"`
	//
	//菜单分类
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category" form:"category"`
	//
	//访问白名单 [easyops, test_uesr]
	Visitors []string `protobuf:"bytes,5,rep,name=visitors,proto3" json:"visitors" form:"visitors"`
	//
	//管理白名单 [easyops, test_uesr]
	Managers             []string `protobuf:"bytes,6,rep,name=managers,proto3" json:"managers" form:"managers"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMenuRequest) Reset()         { *m = UpdateMenuRequest{} }
func (m *UpdateMenuRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuRequest) ProtoMessage()    {}
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9055fd4950581c98, []int{0}
}
func (m *UpdateMenuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuRequest.Unmarshal(m, b)
}
func (m *UpdateMenuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMenuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuRequest.Merge(m, src)
}
func (m *UpdateMenuRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuRequest.Size(m)
}
func (m *UpdateMenuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuRequest proto.InternalMessageInfo

func (m *UpdateMenuRequest) GetMenusId() string {
	if m != nil {
		return m.MenusId
	}
	return ""
}

func (m *UpdateMenuRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateMenuRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *UpdateMenuRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *UpdateMenuRequest) GetVisitors() []string {
	if m != nil {
		return m.Visitors
	}
	return nil
}

func (m *UpdateMenuRequest) GetManagers() []string {
	if m != nil {
		return m.Managers
	}
	return nil
}

//
//UpdateMenu返回
type UpdateMenuResponse struct {
	//
	//菜单id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMenuResponse) Reset()         { *m = UpdateMenuResponse{} }
func (m *UpdateMenuResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuResponse) ProtoMessage()    {}
func (*UpdateMenuResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9055fd4950581c98, []int{1}
}
func (m *UpdateMenuResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuResponse.Unmarshal(m, b)
}
func (m *UpdateMenuResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMenuResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuResponse.Merge(m, src)
}
func (m *UpdateMenuResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuResponse.Size(m)
}
func (m *UpdateMenuResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuResponse proto.InternalMessageInfo

func (m *UpdateMenuResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//
//UpdateMenuApi返回
type UpdateMenuResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *UpdateMenuResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UpdateMenuResponseWrapper) Reset()         { *m = UpdateMenuResponseWrapper{} }
func (m *UpdateMenuResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*UpdateMenuResponseWrapper) ProtoMessage()    {}
func (*UpdateMenuResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_9055fd4950581c98, []int{2}
}
func (m *UpdateMenuResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMenuResponseWrapper.Unmarshal(m, b)
}
func (m *UpdateMenuResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMenuResponseWrapper.Marshal(b, m, deterministic)
}
func (m *UpdateMenuResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMenuResponseWrapper.Merge(m, src)
}
func (m *UpdateMenuResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_UpdateMenuResponseWrapper.Size(m)
}
func (m *UpdateMenuResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMenuResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMenuResponseWrapper proto.InternalMessageInfo

func (m *UpdateMenuResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateMenuResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *UpdateMenuResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateMenuResponseWrapper) GetData() *UpdateMenuResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateMenuRequest)(nil), "menu.UpdateMenuRequest")
	proto.RegisterType((*UpdateMenuResponse)(nil), "menu.UpdateMenuResponse")
	proto.RegisterType((*UpdateMenuResponseWrapper)(nil), "menu.UpdateMenuResponseWrapper")
}

func init() { proto.RegisterFile("update_menu.proto", fileDescriptor_9055fd4950581c98) }

var fileDescriptor_9055fd4950581c98 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x49, 0x9a, 0xad, 0xdd, 0x89, 0x5a, 0x3b, 0x48, 0x89, 0x05, 0x49, 0x19, 0x45, 0x7a,
	0xd1, 0x6c, 0xc0, 0x95, 0x22, 0x82, 0x82, 0x05, 0x2f, 0x7a, 0xe1, 0xcd, 0x80, 0x08, 0x7e, 0x95,
	0xd9, 0x64, 0x36, 0x0e, 0x6e, 0x32, 0x71, 0x32, 0xd9, 0xf5, 0x03, 0x5f, 0x35, 0xb2, 0x3e, 0x42,
	0x5e, 0x40, 0x99, 0x93, 0x8f, 0x0d, 0xbb, 0x60, 0x6e, 0x72, 0xe6, 0xfc, 0x7f, 0xff, 0xc3, 0x99,
	0x73, 0x06, 0x1d, 0x95, 0x79, 0xcc, 0x34, 0xbf, 0x4e, 0x79, 0x56, 0x4e, 0x72, 0x25, 0xb5, 0xc4,
	0x8e, 0x89, 0x4f, 0x82, 0x44, 0xe8, 0xcf, 0xe5, 0x6c, 0x12, 0xc9, 0x34, 0x4c, 0x64, 0x22, 0x43,
	0x10, 0x67, 0xe5, 0x1c, 0x4e, 0x70, 0x80, 0xa8, 0x31, 0x9d, 0x5c, 0x0c, 0xf0, 0x74, 0x25, 0xf4,
	0x17, 0xb9, 0x0a, 0x13, 0x19, 0x80, 0x18, 0x2c, 0xd9, 0x42, 0xc4, 0x4c, 0x4b, 0x55, 0x84, 0x7d,
	0xd8, 0xf8, 0xc8, 0xda, 0x46, 0x47, 0x6f, 0xa0, 0x85, 0xd7, 0x3c, 0x2b, 0x29, 0xff, 0x5a, 0xf2,
	0x42, 0xe3, 0x73, 0x74, 0xc3, 0x34, 0x51, 0x5c, 0xc5, 0x9e, 0x75, 0x6a, 0x9d, 0x8d, 0x2f, 0x71,
	0x5d, 0xf9, 0xb7, 0xe7, 0x52, 0xa5, 0xcf, 0x48, 0x2b, 0x10, 0xda, 0x21, 0xf8, 0x01, 0x72, 0x32,
	0x96, 0x72, 0xcf, 0x06, 0xf4, 0xb0, 0xae, 0x7c, 0xb7, 0x41, 0x4d, 0x96, 0x50, 0x10, 0x0d, 0x24,
	0x22, 0x99, 0x79, 0x7b, 0xdb, 0x90, 0xc9, 0x12, 0x0a, 0x22, 0x7e, 0x81, 0x0e, 0x22, 0xa6, 0x79,
	0x22, 0xd5, 0x77, 0xcf, 0x01, 0x90, 0xd4, 0x95, 0x7f, 0xd8, 0x80, 0x9d, 0x42, 0xfe, 0xfc, 0xf6,
	0xdd, 0xfc, 0x6f, 0xf7, 0x59, 0xb4, 0xf7, 0xe0, 0x2b, 0x74, 0xb0, 0x14, 0x85, 0x30, 0x37, 0xf5,
	0x46, 0xa7, 0x7b, 0x67, 0xe3, 0xcb, 0x60, 0xe3, 0xef, 0x14, 0xe3, 0x3f, 0x46, 0x77, 0x3f, 0xbd,
	0x7f, 0x19, 0xbc, 0x63, 0xc1, 0x8f, 0xeb, 0xe0, 0xe3, 0x87, 0xd5, 0xcf, 0xe9, 0xf9, 0xc5, 0x93,
	0x5f, 0x0f, 0x69, 0x6f, 0x37, 0xa5, 0x52, 0x96, 0xb1, 0x84, 0xab, 0xc2, 0xdb, 0xdf, 0x2e, 0xd5,
	0x29, 0xff, 0x2d, 0xd5, 0x43, 0x53, 0x84, 0x87, 0x23, 0x2e, 0x72, 0x99, 0x15, 0x1c, 0xdf, 0x47,
	0xb6, 0xe8, 0xc6, 0x7b, 0xab, 0xae, 0xfc, 0x71, 0x3b, 0x8e, 0x98, 0x50, 0x5b, 0xc4, 0x64, 0x6d,
	0xa1, 0x7b, 0xbb, 0xae, 0xb7, 0x8a, 0xe5, 0x39, 0x57, 0x66, 0x9a, 0x91, 0x8c, 0x39, 0xd8, 0x47,
	0xc3, 0x69, 0x9a, 0x2c, 0xa1, 0x20, 0xe2, 0xa7, 0xc8, 0x35, 0xff, 0x57, 0xdf, 0xf2, 0x05, 0x13,
	0x59, 0xbb, 0x9e, 0xe3, 0xba, 0xf2, 0xf1, 0x86, 0x6d, 0x45, 0x42, 0x87, 0x28, 0x7e, 0x84, 0x46,
	0x5c, 0x29, 0xa9, 0xda, 0x6d, 0xdd, 0xa9, 0x2b, 0xff, 0x66, 0xe3, 0x81, 0x34, 0xa1, 0x8d, 0x8c,
	0x9f, 0x23, 0x27, 0x66, 0x9a, 0xc1, 0xae, 0xdc, 0xc7, 0xde, 0x04, 0x5e, 0xf1, 0x6e, 0xd7, 0xc3,
	0x06, 0x0d, 0x4f, 0x28, 0xd8, 0x66, 0xfb, 0xf0, 0x06, 0xa7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x8c, 0x61, 0xeb, 0x4f, 0x05, 0x03, 0x00, 0x00,
}
