// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_micro_app_list_by_objectId.proto

package object_micro_app

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	micro_app "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/micro_app"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//GetMicroAppList请求
type GetMicroAppListRequest struct {
	//
	//模型id
	ObjectId             string   `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id" form:"object_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMicroAppListRequest) Reset()         { *m = GetMicroAppListRequest{} }
func (m *GetMicroAppListRequest) String() string { return proto.CompactTextString(m) }
func (*GetMicroAppListRequest) ProtoMessage()    {}
func (*GetMicroAppListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ef0ee3873b4e2a2, []int{0}
}
func (m *GetMicroAppListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMicroAppListRequest.Unmarshal(m, b)
}
func (m *GetMicroAppListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMicroAppListRequest.Marshal(b, m, deterministic)
}
func (m *GetMicroAppListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMicroAppListRequest.Merge(m, src)
}
func (m *GetMicroAppListRequest) XXX_Size() int {
	return xxx_messageInfo_GetMicroAppListRequest.Size(m)
}
func (m *GetMicroAppListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMicroAppListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMicroAppListRequest proto.InternalMessageInfo

func (m *GetMicroAppListRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

//
//GetMicroAppList返回
type GetMicroAppListResponse struct {
	//
	//页数
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" form:"page"`
	//
	//页大小
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//总数
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total" form:"total"`
	//
	//数据列表
	List                 []*micro_app.ObjectMicroApp `protobuf:"bytes,4,rep,name=list,proto3" json:"list" form:"list"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GetMicroAppListResponse) Reset()         { *m = GetMicroAppListResponse{} }
func (m *GetMicroAppListResponse) String() string { return proto.CompactTextString(m) }
func (*GetMicroAppListResponse) ProtoMessage()    {}
func (*GetMicroAppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ef0ee3873b4e2a2, []int{1}
}
func (m *GetMicroAppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMicroAppListResponse.Unmarshal(m, b)
}
func (m *GetMicroAppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMicroAppListResponse.Marshal(b, m, deterministic)
}
func (m *GetMicroAppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMicroAppListResponse.Merge(m, src)
}
func (m *GetMicroAppListResponse) XXX_Size() int {
	return xxx_messageInfo_GetMicroAppListResponse.Size(m)
}
func (m *GetMicroAppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMicroAppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMicroAppListResponse proto.InternalMessageInfo

func (m *GetMicroAppListResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetMicroAppListResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetMicroAppListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetMicroAppListResponse) GetList() []*micro_app.ObjectMicroApp {
	if m != nil {
		return m.List
	}
	return nil
}

//
//GetMicroAppListApi返回
type GetMicroAppListResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *GetMicroAppListResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetMicroAppListResponseWrapper) Reset()         { *m = GetMicroAppListResponseWrapper{} }
func (m *GetMicroAppListResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*GetMicroAppListResponseWrapper) ProtoMessage()    {}
func (*GetMicroAppListResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ef0ee3873b4e2a2, []int{2}
}
func (m *GetMicroAppListResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMicroAppListResponseWrapper.Unmarshal(m, b)
}
func (m *GetMicroAppListResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMicroAppListResponseWrapper.Marshal(b, m, deterministic)
}
func (m *GetMicroAppListResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMicroAppListResponseWrapper.Merge(m, src)
}
func (m *GetMicroAppListResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_GetMicroAppListResponseWrapper.Size(m)
}
func (m *GetMicroAppListResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMicroAppListResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GetMicroAppListResponseWrapper proto.InternalMessageInfo

func (m *GetMicroAppListResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetMicroAppListResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *GetMicroAppListResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetMicroAppListResponseWrapper) GetData() *GetMicroAppListResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetMicroAppListRequest)(nil), "object_micro_app.GetMicroAppListRequest")
	proto.RegisterType((*GetMicroAppListResponse)(nil), "object_micro_app.GetMicroAppListResponse")
	proto.RegisterType((*GetMicroAppListResponseWrapper)(nil), "object_micro_app.GetMicroAppListResponseWrapper")
}

func init() {
	proto.RegisterFile("get_micro_app_list_by_objectId.proto", fileDescriptor_9ef0ee3873b4e2a2)
}

var fileDescriptor_9ef0ee3873b4e2a2 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0x75, 0xdb, 0x54, 0x9a, 0x59, 0xc1, 0x65, 0xc0, 0x1a, 0x0b, 0x9a, 0x65, 0x2c, 0xb2, 0x05,
	0x93, 0xd4, 0x16, 0xac, 0xfa, 0x20, 0x74, 0x41, 0x44, 0xf0, 0x03, 0xa2, 0x20, 0xb4, 0x68, 0x98,
	0x24, 0xd3, 0x38, 0x9a, 0xec, 0x1d, 0x67, 0x66, 0xad, 0x5d, 0xf1, 0xaf, 0xae, 0x20, 0xf8, 0x07,
	0xf6, 0xc5, 0x57, 0x99, 0xc9, 0x66, 0x13, 0x2c, 0x7d, 0x9a, 0xb9, 0xf7, 0x9c, 0x73, 0xcf, 0x3d,
	0xc3, 0xa0, 0x9d, 0x82, 0xe9, 0xa4, 0xe2, 0x99, 0x84, 0x84, 0x0a, 0x91, 0x94, 0x5c, 0xe9, 0x24,
	0x3d, 0x4f, 0x20, 0xfd, 0xcc, 0x32, 0xfd, 0x22, 0x0f, 0x85, 0x04, 0x0d, 0x78, 0x50, 0xd7, 0x2d,
	0x71, 0x3b, 0x28, 0xb8, 0xfe, 0x34, 0x4d, 0xc3, 0x0c, 0xaa, 0xa8, 0x80, 0x02, 0x22, 0x4b, 0x4c,
	0xa7, 0xa7, 0xb6, 0xb2, 0x85, 0xbd, 0xd5, 0x03, 0xb6, 0x8f, 0x0b, 0x08, 0x19, 0x55, 0xe7, 0x20,
	0x54, 0x58, 0x42, 0x46, 0xcb, 0x28, 0x83, 0x89, 0x96, 0x34, 0xd3, 0xaa, 0x56, 0x4a, 0x26, 0x20,
	0xa8, 0x20, 0x67, 0xa5, 0x8a, 0x96, 0xc4, 0xc8, 0x96, 0xd1, 0xca, 0x33, 0xfa, 0x7f, 0x89, 0xe5,
	0xec, 0x87, 0x9d, 0x55, 0xaa, 0x33, 0xae, 0xbf, 0xc0, 0x59, 0x54, 0x40, 0x60, 0xc1, 0xe0, 0x1b,
	0x2d, 0x79, 0x4e, 0x35, 0x48, 0x15, 0xad, 0xae, 0xb5, 0x8e, 0x4c, 0xd0, 0xd6, 0x73, 0xa6, 0x5f,
	0x99, 0x69, 0x47, 0x42, 0xbc, 0xe4, 0x4a, 0xc7, 0xec, 0xeb, 0x94, 0x29, 0x8d, 0xdf, 0x21, 0x77,
	0xe9, 0xc5, 0x73, 0xaf, 0x37, 0xec, 0x8d, 0xdc, 0xf1, 0xe1, 0x62, 0xee, 0x0f, 0x4e, 0x41, 0x56,
	0x4f, 0xc8, 0x0a, 0x22, 0xbf, 0x7f, 0xf9, 0x3e, 0xba, 0xfd, 0xf1, 0x84, 0x06, 0xb3, 0xa3, 0xe0,
	0x38, 0xf9, 0x70, 0xb2, 0x17, 0x3c, 0x6e, 0xee, 0x3f, 0xf6, 0xee, 0x1f, 0x3c, 0xf8, 0xb9, 0x13,
	0x6f, 0x36, 0x4f, 0x49, 0xfe, 0xf4, 0xd0, 0xcd, 0x0b, 0x86, 0x4a, 0xc0, 0x44, 0x31, 0xbc, 0x8b,
	0x1c, 0x41, 0x0b, 0x66, 0xcd, 0x36, 0xc6, 0x37, 0x16, 0x73, 0xbf, 0x5f, 0x9b, 0x99, 0xae, 0xf1,
	0x59, 0x1b, 0x5c, 0x89, 0x2d, 0x05, 0x1f, 0x22, 0xd7, 0x9c, 0x89, 0xe2, 0x33, 0xe6, 0xad, 0x59,
	0xfe, 0x76, 0xbb, 0xdc, 0x0a, 0x6a, 0x44, 0x9b, 0xa6, 0xf3, 0x96, 0xcf, 0x18, 0xbe, 0x87, 0x36,
	0x34, 0x68, 0x5a, 0x7a, 0xeb, 0x56, 0x34, 0x58, 0xcc, 0xfd, 0x6b, 0xb5, 0xc8, 0xb6, 0x49, 0x5c,
	0xc3, 0xf8, 0x29, 0x72, 0xcc, 0x37, 0xf0, 0x9c, 0xe1, 0xfa, 0xa8, 0xbf, 0x7f, 0x2b, 0x6c, 0xdf,
	0xfb, 0x8d, 0x8d, 0xd2, 0x04, 0x18, 0x5f, 0x6f, 0xd7, 0x34, 0x02, 0x12, 0x5b, 0x1d, 0xf9, 0xdb,
	0x43, 0x77, 0x2e, 0xc9, 0xf9, 0x5e, 0x52, 0x21, 0x98, 0xc4, 0x77, 0x91, 0x93, 0x41, 0xde, 0xc4,
	0xed, 0xcc, 0x31, 0x5d, 0x12, 0x5b, 0x10, 0x3f, 0x42, 0x7d, 0x73, 0x3e, 0xfb, 0x2e, 0x4a, 0xca,
	0x27, 0x36, 0xaa, 0x3b, 0xde, 0x5a, 0xcc, 0x7d, 0xdc, 0x72, 0x97, 0x20, 0x89, 0xbb, 0x54, 0x93,
	0x94, 0x49, 0x09, 0xd2, 0x26, 0x75, 0xbb, 0x49, 0x6d, 0x9b, 0xc4, 0x35, 0x8c, 0x5f, 0x23, 0x27,
	0xa7, 0x9a, 0x7a, 0xce, 0xb0, 0x37, 0xea, 0xef, 0xef, 0x86, 0x17, 0x3e, 0xd8, 0x25, 0x31, 0xba,
	0x1b, 0x9b, 0x01, 0x24, 0xb6, 0x73, 0xd2, 0xab, 0xf6, 0x63, 0x1d, 0xfc, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xe7, 0x9f, 0x46, 0xcd, 0x55, 0x03, 0x00, 0x00,
}
