// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_app_health_config_v2.proto

package app_health

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	monitor_config "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/monitor_config"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//GetAppHealthConfigV2请求
type GetAppHealthConfigV2Request struct {
	//
	//应用id
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id" form:"app_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppHealthConfigV2Request) Reset()         { *m = GetAppHealthConfigV2Request{} }
func (m *GetAppHealthConfigV2Request) String() string { return proto.CompactTextString(m) }
func (*GetAppHealthConfigV2Request) ProtoMessage()    {}
func (*GetAppHealthConfigV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f8a055a9f678ade, []int{0}
}
func (m *GetAppHealthConfigV2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppHealthConfigV2Request.Unmarshal(m, b)
}
func (m *GetAppHealthConfigV2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppHealthConfigV2Request.Marshal(b, m, deterministic)
}
func (m *GetAppHealthConfigV2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppHealthConfigV2Request.Merge(m, src)
}
func (m *GetAppHealthConfigV2Request) XXX_Size() int {
	return xxx_messageInfo_GetAppHealthConfigV2Request.Size(m)
}
func (m *GetAppHealthConfigV2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppHealthConfigV2Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppHealthConfigV2Request proto.InternalMessageInfo

func (m *GetAppHealthConfigV2Request) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

//
//GetAppHealthConfigV2返回
type GetAppHealthConfigV2Response struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回信息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" form:"msg"`
	//
	//返回数据
	Data                 *monitor_config.AppHealthConfig `protobuf:"bytes,3,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GetAppHealthConfigV2Response) Reset()         { *m = GetAppHealthConfigV2Response{} }
func (m *GetAppHealthConfigV2Response) String() string { return proto.CompactTextString(m) }
func (*GetAppHealthConfigV2Response) ProtoMessage()    {}
func (*GetAppHealthConfigV2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f8a055a9f678ade, []int{1}
}
func (m *GetAppHealthConfigV2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppHealthConfigV2Response.Unmarshal(m, b)
}
func (m *GetAppHealthConfigV2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppHealthConfigV2Response.Marshal(b, m, deterministic)
}
func (m *GetAppHealthConfigV2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppHealthConfigV2Response.Merge(m, src)
}
func (m *GetAppHealthConfigV2Response) XXX_Size() int {
	return xxx_messageInfo_GetAppHealthConfigV2Response.Size(m)
}
func (m *GetAppHealthConfigV2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppHealthConfigV2Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppHealthConfigV2Response proto.InternalMessageInfo

func (m *GetAppHealthConfigV2Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAppHealthConfigV2Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetAppHealthConfigV2Response) GetData() *monitor_config.AppHealthConfig {
	if m != nil {
		return m.Data
	}
	return nil
}

//
//GetAppHealthConfigV2Api返回
type GetAppHealthConfigV2ResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *GetAppHealthConfigV2Response `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetAppHealthConfigV2ResponseWrapper) Reset()         { *m = GetAppHealthConfigV2ResponseWrapper{} }
func (m *GetAppHealthConfigV2ResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*GetAppHealthConfigV2ResponseWrapper) ProtoMessage()    {}
func (*GetAppHealthConfigV2ResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f8a055a9f678ade, []int{2}
}
func (m *GetAppHealthConfigV2ResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppHealthConfigV2ResponseWrapper.Unmarshal(m, b)
}
func (m *GetAppHealthConfigV2ResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppHealthConfigV2ResponseWrapper.Marshal(b, m, deterministic)
}
func (m *GetAppHealthConfigV2ResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppHealthConfigV2ResponseWrapper.Merge(m, src)
}
func (m *GetAppHealthConfigV2ResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_GetAppHealthConfigV2ResponseWrapper.Size(m)
}
func (m *GetAppHealthConfigV2ResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppHealthConfigV2ResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppHealthConfigV2ResponseWrapper proto.InternalMessageInfo

func (m *GetAppHealthConfigV2ResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAppHealthConfigV2ResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *GetAppHealthConfigV2ResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetAppHealthConfigV2ResponseWrapper) GetData() *GetAppHealthConfigV2Response {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAppHealthConfigV2Request)(nil), "app_health.GetAppHealthConfigV2Request")
	proto.RegisterType((*GetAppHealthConfigV2Response)(nil), "app_health.GetAppHealthConfigV2Response")
	proto.RegisterType((*GetAppHealthConfigV2ResponseWrapper)(nil), "app_health.GetAppHealthConfigV2ResponseWrapper")
}

func init() { proto.RegisterFile("get_app_health_config_v2.proto", fileDescriptor_4f8a055a9f678ade) }

var fileDescriptor_4f8a055a9f678ade = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x6b, 0xe3, 0x30,
	0x14, 0xc4, 0x9b, 0x0f, 0x88, 0xb2, 0x9f, 0x3a, 0x2c, 0x21, 0xbb, 0xac, 0x83, 0x02, 0x8b, 0x2f,
	0x91, 0x21, 0x7b, 0x59, 0xf6, 0xb6, 0x69, 0x4b, 0xda, 0x43, 0x2f, 0x3e, 0xb4, 0x47, 0x57, 0xb1,
	0x15, 0xc5, 0x60, 0xfb, 0xa9, 0x92, 0x52, 0xda, 0xdf, 0xd4, 0xff, 0xe4, 0x1f, 0xe1, 0x6b, 0x2f,
	0xc5, 0x92, 0x21, 0xe9, 0x57, 0xe8, 0xc9, 0x7e, 0x6f, 0x66, 0xde, 0xcc, 0x20, 0xf4, 0x4b, 0x70,
	0x13, 0x33, 0x29, 0xe3, 0x0d, 0x67, 0xb9, 0xd9, 0xc4, 0x09, 0x94, 0xeb, 0x4c, 0xc4, 0x37, 0x73,
	0x2a, 0x15, 0x18, 0xc0, 0x68, 0x87, 0x8d, 0x67, 0x22, 0x33, 0x9b, 0xed, 0x8a, 0x26, 0x50, 0x84,
	0x02, 0x04, 0x84, 0x96, 0xb2, 0xda, 0xae, 0xed, 0x64, 0x07, 0xfb, 0xe7, 0xa4, 0xe3, 0x2b, 0x01,
	0x94, 0x33, 0x7d, 0x07, 0x52, 0xd3, 0x1c, 0x12, 0x96, 0x87, 0x09, 0x94, 0x46, 0xb1, 0xc4, 0x68,
	0xa7, 0x54, 0x5c, 0xc2, 0xac, 0x80, 0x94, 0xe7, 0x3a, 0x6c, 0x89, 0xa1, 0x1d, 0xc3, 0x02, 0xca,
	0xcc, 0x80, 0x6a, 0xd3, 0x84, 0x2f, 0xf2, 0x39, 0x07, 0xb2, 0x44, 0x3f, 0x96, 0xdc, 0xfc, 0x97,
	0xf2, 0xd4, 0x82, 0x47, 0x16, 0xbb, 0x98, 0x47, 0xfc, 0x7a, 0xcb, 0xb5, 0xc1, 0x01, 0xea, 0x37,
	0xca, 0x2c, 0x1d, 0x79, 0x13, 0x2f, 0x18, 0x2c, 0xbe, 0xd5, 0x95, 0xff, 0x69, 0x0d, 0xaa, 0xf8,
	0x47, 0xdc, 0x9e, 0x44, 0x3d, 0x26, 0xe5, 0x59, 0x4a, 0xee, 0x3d, 0xf4, 0xf3, 0xf5, 0x4b, 0x5a,
	0x42, 0xa9, 0x39, 0x9e, 0xa2, 0x6e, 0x02, 0x29, 0xb7, 0x87, 0x7a, 0x8b, 0x2f, 0x75, 0xe5, 0x0f,
	0xdd, 0xa1, 0x66, 0x4b, 0x22, 0x0b, 0xe2, 0x09, 0xea, 0x14, 0x5a, 0x8c, 0x3e, 0x58, 0xb3, 0xcf,
	0x75, 0xe5, 0x23, 0xc7, 0x29, 0xb4, 0x20, 0x51, 0x03, 0xe1, 0x63, 0xd4, 0x4d, 0x99, 0x61, 0xa3,
	0xce, 0xc4, 0x0b, 0x86, 0x73, 0x9f, 0x3e, 0xed, 0x49, 0x9f, 0xf9, 0xef, 0xfb, 0x34, 0x32, 0x12,
	0x59, 0x35, 0x79, 0xf0, 0xd0, 0xf4, 0x50, 0xda, 0x4b, 0xc5, 0xa4, 0xe4, 0xea, 0x7d, 0xa1, 0xff,
	0xa2, 0x61, 0xf3, 0x3d, 0xb9, 0x95, 0x39, 0xcb, 0xca, 0x36, 0xfc, 0xf7, 0xba, 0xf2, 0xf1, 0x8e,
	0xdb, 0x82, 0x24, 0xda, 0xa7, 0xe2, 0xdf, 0xa8, 0xc7, 0x95, 0x02, 0x65, 0xdb, 0x0c, 0x16, 0x5f,
	0xeb, 0xca, 0xff, 0xe8, 0x34, 0x76, 0x4d, 0x22, 0x07, 0xe3, 0xf3, 0xb6, 0x74, 0xd7, 0x96, 0x0e,
	0xe8, 0xee, 0x35, 0xe9, 0xa1, 0x16, 0x6f, 0xb4, 0x5f, 0xf5, 0xed, 0xdb, 0xff, 0x79, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0xf4, 0xe9, 0x4e, 0xba, 0x02, 0x00, 0x00,
}
