// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: compare_workspace.proto

package workspace

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//FileCompare请求
type FileCompareRequest struct {
	//
	//要比较的文件列表
	Items []*FileCompareRequest_Items `protobuf:"bytes,1,rep,name=items,proto3" json:"items" form:"items"`
	//
	//程序包Id
	PackageId            string   `protobuf:"bytes,2,opt,name=packageId,proto3" json:"packageId" form:"packageId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileCompareRequest) Reset()         { *m = FileCompareRequest{} }
func (m *FileCompareRequest) String() string { return proto.CompactTextString(m) }
func (*FileCompareRequest) ProtoMessage()    {}
func (*FileCompareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15da7cec1331f218, []int{0}
}
func (m *FileCompareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCompareRequest.Unmarshal(m, b)
}
func (m *FileCompareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCompareRequest.Marshal(b, m, deterministic)
}
func (m *FileCompareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCompareRequest.Merge(m, src)
}
func (m *FileCompareRequest) XXX_Size() int {
	return xxx_messageInfo_FileCompareRequest.Size(m)
}
func (m *FileCompareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCompareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileCompareRequest proto.InternalMessageInfo

func (m *FileCompareRequest) GetItems() []*FileCompareRequest_Items {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *FileCompareRequest) GetPackageId() string {
	if m != nil {
		return m.PackageId
	}
	return ""
}

type FileCompareRequest_Items struct {
	//
	//文件旧名称
	OldName string `protobuf:"bytes,1,opt,name=oldName,proto3" json:"oldName" form:"oldName"`
	//
	//文件新名称
	NewName string `protobuf:"bytes,2,opt,name=newName,proto3" json:"newName" form:"newName"`
	//
	//要比较的文件路径
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path" form:"path"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileCompareRequest_Items) Reset()         { *m = FileCompareRequest_Items{} }
func (m *FileCompareRequest_Items) String() string { return proto.CompactTextString(m) }
func (*FileCompareRequest_Items) ProtoMessage()    {}
func (*FileCompareRequest_Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_15da7cec1331f218, []int{0, 0}
}
func (m *FileCompareRequest_Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCompareRequest_Items.Unmarshal(m, b)
}
func (m *FileCompareRequest_Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCompareRequest_Items.Marshal(b, m, deterministic)
}
func (m *FileCompareRequest_Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCompareRequest_Items.Merge(m, src)
}
func (m *FileCompareRequest_Items) XXX_Size() int {
	return xxx_messageInfo_FileCompareRequest_Items.Size(m)
}
func (m *FileCompareRequest_Items) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCompareRequest_Items.DiscardUnknown(m)
}

var xxx_messageInfo_FileCompareRequest_Items proto.InternalMessageInfo

func (m *FileCompareRequest_Items) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

func (m *FileCompareRequest_Items) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *FileCompareRequest_Items) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

//
//FileCompare返回
type FileCompareResponse struct {
	//
	//差异详情列表
	Datail               []*FileCompareResponse_Datail `protobuf:"bytes,1,rep,name=datail,proto3" json:"datail" form:"datail"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *FileCompareResponse) Reset()         { *m = FileCompareResponse{} }
func (m *FileCompareResponse) String() string { return proto.CompactTextString(m) }
func (*FileCompareResponse) ProtoMessage()    {}
func (*FileCompareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15da7cec1331f218, []int{1}
}
func (m *FileCompareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCompareResponse.Unmarshal(m, b)
}
func (m *FileCompareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCompareResponse.Marshal(b, m, deterministic)
}
func (m *FileCompareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCompareResponse.Merge(m, src)
}
func (m *FileCompareResponse) XXX_Size() int {
	return xxx_messageInfo_FileCompareResponse.Size(m)
}
func (m *FileCompareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCompareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileCompareResponse proto.InternalMessageInfo

func (m *FileCompareResponse) GetDatail() []*FileCompareResponse_Datail {
	if m != nil {
		return m.Datail
	}
	return nil
}

type FileCompareResponse_Datail struct {
	//
	//差异信息
	Diff string `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff" form:"diff"`
	//
	//文件路径
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file" form:"file"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileCompareResponse_Datail) Reset()         { *m = FileCompareResponse_Datail{} }
func (m *FileCompareResponse_Datail) String() string { return proto.CompactTextString(m) }
func (*FileCompareResponse_Datail) ProtoMessage()    {}
func (*FileCompareResponse_Datail) Descriptor() ([]byte, []int) {
	return fileDescriptor_15da7cec1331f218, []int{1, 0}
}
func (m *FileCompareResponse_Datail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCompareResponse_Datail.Unmarshal(m, b)
}
func (m *FileCompareResponse_Datail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCompareResponse_Datail.Marshal(b, m, deterministic)
}
func (m *FileCompareResponse_Datail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCompareResponse_Datail.Merge(m, src)
}
func (m *FileCompareResponse_Datail) XXX_Size() int {
	return xxx_messageInfo_FileCompareResponse_Datail.Size(m)
}
func (m *FileCompareResponse_Datail) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCompareResponse_Datail.DiscardUnknown(m)
}

var xxx_messageInfo_FileCompareResponse_Datail proto.InternalMessageInfo

func (m *FileCompareResponse_Datail) GetDiff() string {
	if m != nil {
		return m.Diff
	}
	return ""
}

func (m *FileCompareResponse_Datail) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

//
//FileCompareApi返回
type FileCompareResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *FileCompareResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileCompareResponseWrapper) Reset()         { *m = FileCompareResponseWrapper{} }
func (m *FileCompareResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*FileCompareResponseWrapper) ProtoMessage()    {}
func (*FileCompareResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_15da7cec1331f218, []int{2}
}
func (m *FileCompareResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCompareResponseWrapper.Unmarshal(m, b)
}
func (m *FileCompareResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCompareResponseWrapper.Marshal(b, m, deterministic)
}
func (m *FileCompareResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCompareResponseWrapper.Merge(m, src)
}
func (m *FileCompareResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_FileCompareResponseWrapper.Size(m)
}
func (m *FileCompareResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCompareResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_FileCompareResponseWrapper proto.InternalMessageInfo

func (m *FileCompareResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FileCompareResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *FileCompareResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FileCompareResponseWrapper) GetData() *FileCompareResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*FileCompareRequest)(nil), "workspace.FileCompareRequest")
	proto.RegisterType((*FileCompareRequest_Items)(nil), "workspace.FileCompareRequest.Items")
	proto.RegisterType((*FileCompareResponse)(nil), "workspace.FileCompareResponse")
	proto.RegisterType((*FileCompareResponse_Datail)(nil), "workspace.FileCompareResponse.Datail")
	proto.RegisterType((*FileCompareResponseWrapper)(nil), "workspace.FileCompareResponseWrapper")
}

func init() { proto.RegisterFile("compare_workspace.proto", fileDescriptor_15da7cec1331f218) }

var fileDescriptor_15da7cec1331f218 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x53, 0x16, 0x30, 0x0c, 0xfe, 0x58, 0xc7, 0x44, 0x09, 0x07, 0x4b, 0x66, 0x57, 0x53,
	0x76, 0x2d, 0x55, 0x34, 0x66, 0x25, 0xc6, 0xcd, 0xb2, 0xba, 0x86, 0x98, 0x18, 0x1d, 0x0f, 0x26,
	0x32, 0x60, 0x06, 0x3a, 0x85, 0x86, 0x96, 0xa9, 0x6d, 0x11, 0xa3, 0xec, 0xdd, 0xfd, 0x2b, 0xfc,
	0xcf, 0x6a, 0xe2, 0xc9, 0x73, 0x4f, 0x1e, 0x4d, 0x67, 0x0a, 0x74, 0x5d, 0x35, 0xd9, 0x13, 0xf3,
	0xde, 0xf7, 0xf3, 0x66, 0xbe, 0xef, 0x3d, 0x0a, 0x6e, 0x0c, 0xb9, 0xeb, 0x51, 0x9f, 0xbd, 0x9f,
	0x73, 0x7f, 0x12, 0x78, 0x74, 0xc8, 0x1a, 0x9e, 0xcf, 0x43, 0x0e, 0x4b, 0xab, 0x44, 0x55, 0x1f,
	0xd9, 0xe1, 0x78, 0x36, 0x68, 0x0c, 0xb9, 0x6b, 0x8c, 0xf8, 0x88, 0x1b, 0x82, 0x18, 0xcc, 0x2c,
	0x11, 0x89, 0x40, 0x9c, 0x64, 0x65, 0xf5, 0x61, 0x06, 0x77, 0xe7, 0x76, 0x38, 0xe1, 0x73, 0x63,
	0xc4, 0x75, 0x21, 0xea, 0x1f, 0xa9, 0x63, 0x9b, 0x34, 0xe4, 0x7e, 0x60, 0xac, 0x8e, 0xb2, 0x0e,
	0xfd, 0xca, 0x01, 0x78, 0x64, 0x3b, 0xec, 0x50, 0x3a, 0xc2, 0xec, 0xc3, 0x8c, 0x05, 0x21, 0x7c,
	0x01, 0x0a, 0x76, 0xc8, 0xdc, 0xa0, 0xa2, 0xd4, 0x36, 0xb4, 0x72, 0x73, 0xab, 0xb1, 0x76, 0x7a,
	0x96, 0x6e, 0x74, 0x12, 0xb4, 0xbd, 0x19, 0x47, 0xea, 0x45, 0x8b, 0xfb, 0x6e, 0x0b, 0x89, 0x5a,
	0x84, 0xe5, 0x1d, 0xf0, 0x44, 0x01, 0x25, 0x8f, 0x0e, 0x27, 0x74, 0xc4, 0x3a, 0x66, 0x25, 0x57,
	0x53, 0xb4, 0x52, 0x7b, 0x12, 0x47, 0xea, 0xa6, 0x84, 0x57, 0x12, 0xfa, 0xf1, 0x5d, 0x7d, 0x03,
	0x5e, 0xf7, 0xbb, 0x54, 0xb7, 0x0e, 0xf4, 0xa3, 0xbb, 0xfa, 0xa3, 0xde, 0x97, 0xbd, 0x63, 0x7d,
	0x3f, 0x1b, 0x3f, 0x38, 0x67, 0x7c, 0xaf, 0x79, 0xbc, 0x8d, 0xd7, 0xaf, 0x57, 0xbf, 0x2a, 0xa0,
	0x20, 0xec, 0xc2, 0x3b, 0xe0, 0x02, 0x77, 0xcc, 0x97, 0xd4, 0x65, 0x15, 0x45, 0x58, 0x82, 0x71,
	0xa4, 0x5e, 0x96, 0x96, 0x52, 0x01, 0xe1, 0x25, 0x92, 0xd0, 0x53, 0x36, 0x17, 0x74, 0xee, 0x4f,
	0x3a, 0x15, 0x10, 0x5e, 0x22, 0x70, 0x0b, 0xe4, 0x3d, 0x1a, 0x8e, 0x2b, 0x1b, 0x02, 0xbd, 0x12,
	0x47, 0x6a, 0x79, 0xd9, 0x6b, 0x38, 0x46, 0x58, 0x88, 0xe8, 0x24, 0x07, 0xae, 0x9d, 0x1a, 0x66,
	0xe0, 0xf1, 0x69, 0xc0, 0xe0, 0x2b, 0x50, 0x34, 0x69, 0x48, 0x6d, 0x27, 0x1d, 0xfe, 0xad, 0x7f,
	0x0d, 0x5f, 0xf2, 0x8d, 0xa7, 0x02, 0x6e, 0x5f, 0x8d, 0x23, 0xf5, 0x92, 0x7c, 0x45, 0x96, 0x23,
	0x9c, 0xde, 0x53, 0xfd, 0xa6, 0x80, 0xa2, 0xa4, 0x12, 0x67, 0xa6, 0x6d, 0x59, 0x69, 0xcb, 0x19,
	0x67, 0x49, 0x16, 0x61, 0x21, 0x42, 0x0f, 0xe4, 0x2d, 0xdb, 0x59, 0x76, 0x4a, 0xd6, 0x50, 0x92,
	0x4d, 0xb6, 0xd4, 0x01, 0xcf, 0xfb, 0x9a, 0x46, 0x8c, 0x6e, 0x9f, 0x18, 0x2d, 0xb2, 0x43, 0xf6,
	0x11, 0x7a, 0xfc, 0x84, 0x2c, 0x88, 0x4f, 0xa6, 0xbd, 0xdd, 0xfa, 0x6e, 0x7d, 0xa1, 0x11, 0xa3,
	0xbe, 0xe8, 0x52, 0xfd, 0xf3, 0x81, 0xfe, 0xae, 0xd7, 0xd2, 0x08, 0xe9, 0xf6, 0x09, 0x39, 0x4b,
	0xee, 0x6c, 0x63, 0xf1, 0x12, 0xfa, 0xa9, 0x80, 0xea, 0x5f, 0x7a, 0x7b, 0xeb, 0x53, 0xcf, 0x63,
	0x7e, 0xe2, 0x7a, 0xc8, 0x4d, 0xb9, 0xa8, 0x42, 0xd6, 0x75, 0x92, 0x45, 0x58, 0x88, 0x70, 0x0f,
	0x94, 0x93, 0xdf, 0x67, 0x9f, 0x3c, 0x87, 0xda, 0xd3, 0xd4, 0xfc, 0xf5, 0x38, 0x52, 0xe1, 0x9a,
	0x4d, 0x45, 0x84, 0xb3, 0x28, 0xbc, 0x0d, 0x0a, 0xcc, 0xf7, 0xb9, 0x9f, 0xee, 0x2b, 0xf3, 0x47,
	0x16, 0x69, 0x84, 0xa5, 0x0c, 0x0f, 0x41, 0x3e, 0x99, 0x68, 0x25, 0x5f, 0x53, 0xb4, 0x72, 0xf3,
	0xe6, 0xff, 0xf7, 0x72, 0x6a, 0xb8, 0x34, 0xa4, 0xc9, 0x70, 0x69, 0x48, 0x07, 0x45, 0xf1, 0xe1,
	0xdd, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x21, 0x66, 0xb5, 0x81, 0x05, 0x04, 0x00, 0x00,
}
