// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: safe_commit_workspace.proto

package workspace

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
//SafeCommitWorkspace请求
type SafeCommitWorkspaceRequest struct {
	//
	//版本备注信息
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message" form:"message"`
	//
	//程序包Id
	PackageId string `protobuf:"bytes,2,opt,name=packageId,proto3" json:"packageId" form:"packageId"`
	//
	//版本Id
	VersionId string `protobuf:"bytes,3,opt,name=versionId,proto3" json:"versionId" form:"versionId"`
	//
	//版本类型 1 开发, 3 测试, 7 预发布, 15 生产
	EnvType int32 `protobuf:"varint,4,opt,name=env_type,json=envType,proto3" json:"env_type" form:"env_type"`
	//
	//包存储源信息
	Source *SafeCommitWorkspaceRequest_Source `protobuf:"bytes,5,opt,name=source,proto3" json:"source" form:"source"`
	//
	//包名称
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name" form:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeCommitWorkspaceRequest) Reset()         { *m = SafeCommitWorkspaceRequest{} }
func (m *SafeCommitWorkspaceRequest) String() string { return proto.CompactTextString(m) }
func (*SafeCommitWorkspaceRequest) ProtoMessage()    {}
func (*SafeCommitWorkspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b0ac16ad2e7ab9, []int{0}
}
func (m *SafeCommitWorkspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeCommitWorkspaceRequest.Unmarshal(m, b)
}
func (m *SafeCommitWorkspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeCommitWorkspaceRequest.Marshal(b, m, deterministic)
}
func (m *SafeCommitWorkspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeCommitWorkspaceRequest.Merge(m, src)
}
func (m *SafeCommitWorkspaceRequest) XXX_Size() int {
	return xxx_messageInfo_SafeCommitWorkspaceRequest.Size(m)
}
func (m *SafeCommitWorkspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeCommitWorkspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SafeCommitWorkspaceRequest proto.InternalMessageInfo

func (m *SafeCommitWorkspaceRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest) GetPackageId() string {
	if m != nil {
		return m.PackageId
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest) GetEnvType() int32 {
	if m != nil {
		return m.EnvType
	}
	return 0
}

func (m *SafeCommitWorkspaceRequest) GetSource() *SafeCommitWorkspaceRequest_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *SafeCommitWorkspaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SafeCommitWorkspaceRequest_Source struct {
	//
	//源服务名字
	EnsName string `protobuf:"bytes,1,opt,name=ensName,proto3" json:"ensName" form:"ensName"`
	//
	//源域名
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host" form:"host"`
	//
	//源类型
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type" form:"type"`
	//
	//http源的ip
	Ip string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip" form:"ip"`
	//
	//http源的port
	Port                 int32    `protobuf:"varint,5,opt,name=port,proto3" json:"port" form:"port"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeCommitWorkspaceRequest_Source) Reset()         { *m = SafeCommitWorkspaceRequest_Source{} }
func (m *SafeCommitWorkspaceRequest_Source) String() string { return proto.CompactTextString(m) }
func (*SafeCommitWorkspaceRequest_Source) ProtoMessage()    {}
func (*SafeCommitWorkspaceRequest_Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b0ac16ad2e7ab9, []int{0, 0}
}
func (m *SafeCommitWorkspaceRequest_Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeCommitWorkspaceRequest_Source.Unmarshal(m, b)
}
func (m *SafeCommitWorkspaceRequest_Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeCommitWorkspaceRequest_Source.Marshal(b, m, deterministic)
}
func (m *SafeCommitWorkspaceRequest_Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeCommitWorkspaceRequest_Source.Merge(m, src)
}
func (m *SafeCommitWorkspaceRequest_Source) XXX_Size() int {
	return xxx_messageInfo_SafeCommitWorkspaceRequest_Source.Size(m)
}
func (m *SafeCommitWorkspaceRequest_Source) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeCommitWorkspaceRequest_Source.DiscardUnknown(m)
}

var xxx_messageInfo_SafeCommitWorkspaceRequest_Source proto.InternalMessageInfo

func (m *SafeCommitWorkspaceRequest_Source) GetEnsName() string {
	if m != nil {
		return m.EnsName
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest_Source) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest_Source) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest_Source) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SafeCommitWorkspaceRequest_Source) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

//
//SafeCommitWorkspace返回
type SafeCommitWorkspaceResponse struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//错误信息
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回信息
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message" form:"message"`
	//
	//返回数据
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SafeCommitWorkspaceResponse) Reset()         { *m = SafeCommitWorkspaceResponse{} }
func (m *SafeCommitWorkspaceResponse) String() string { return proto.CompactTextString(m) }
func (*SafeCommitWorkspaceResponse) ProtoMessage()    {}
func (*SafeCommitWorkspaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b0ac16ad2e7ab9, []int{1}
}
func (m *SafeCommitWorkspaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeCommitWorkspaceResponse.Unmarshal(m, b)
}
func (m *SafeCommitWorkspaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeCommitWorkspaceResponse.Marshal(b, m, deterministic)
}
func (m *SafeCommitWorkspaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeCommitWorkspaceResponse.Merge(m, src)
}
func (m *SafeCommitWorkspaceResponse) XXX_Size() int {
	return xxx_messageInfo_SafeCommitWorkspaceResponse.Size(m)
}
func (m *SafeCommitWorkspaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeCommitWorkspaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SafeCommitWorkspaceResponse proto.InternalMessageInfo

func (m *SafeCommitWorkspaceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SafeCommitWorkspaceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SafeCommitWorkspaceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SafeCommitWorkspaceResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

//
//SafeCommitWorkspaceApi返回
type SafeCommitWorkspaceResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *SafeCommitWorkspaceResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SafeCommitWorkspaceResponseWrapper) Reset()         { *m = SafeCommitWorkspaceResponseWrapper{} }
func (m *SafeCommitWorkspaceResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*SafeCommitWorkspaceResponseWrapper) ProtoMessage()    {}
func (*SafeCommitWorkspaceResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6b0ac16ad2e7ab9, []int{2}
}
func (m *SafeCommitWorkspaceResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SafeCommitWorkspaceResponseWrapper.Unmarshal(m, b)
}
func (m *SafeCommitWorkspaceResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SafeCommitWorkspaceResponseWrapper.Marshal(b, m, deterministic)
}
func (m *SafeCommitWorkspaceResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SafeCommitWorkspaceResponseWrapper.Merge(m, src)
}
func (m *SafeCommitWorkspaceResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_SafeCommitWorkspaceResponseWrapper.Size(m)
}
func (m *SafeCommitWorkspaceResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_SafeCommitWorkspaceResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_SafeCommitWorkspaceResponseWrapper proto.InternalMessageInfo

func (m *SafeCommitWorkspaceResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SafeCommitWorkspaceResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *SafeCommitWorkspaceResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SafeCommitWorkspaceResponseWrapper) GetData() *SafeCommitWorkspaceResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*SafeCommitWorkspaceRequest)(nil), "workspace.SafeCommitWorkspaceRequest")
	proto.RegisterType((*SafeCommitWorkspaceRequest_Source)(nil), "workspace.SafeCommitWorkspaceRequest.Source")
	proto.RegisterType((*SafeCommitWorkspaceResponse)(nil), "workspace.SafeCommitWorkspaceResponse")
	proto.RegisterType((*SafeCommitWorkspaceResponseWrapper)(nil), "workspace.SafeCommitWorkspaceResponseWrapper")
}

func init() { proto.RegisterFile("safe_commit_workspace.proto", fileDescriptor_c6b0ac16ad2e7ab9) }

var fileDescriptor_c6b0ac16ad2e7ab9 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x26, 0xeb, 0xc7, 0xa8, 0xcb, 0xd8, 0x08, 0x12, 0x44, 0x9d, 0x50, 0x26, 0x0f, 0x4d, 0x93,
	0x58, 0x52, 0x18, 0x08, 0x0d, 0x2e, 0x88, 0x22, 0x0e, 0x13, 0x12, 0x07, 0x6f, 0xd2, 0x24, 0x10,
	0x4c, 0x5e, 0xea, 0x66, 0x51, 0x9b, 0xd8, 0xd8, 0x69, 0xbb, 0x81, 0xf6, 0x07, 0xf8, 0x4f, 0xdc,
	0xf8, 0x1d, 0x41, 0xf0, 0x13, 0x72, 0xe2, 0x88, 0xfc, 0x3a, 0x6d, 0xb3, 0xc1, 0x36, 0x38, 0x70,
	0xaa, 0xfd, 0x3e, 0xcf, 0xfb, 0xf1, 0x3c, 0x7d, 0x1d, 0xb4, 0xac, 0x68, 0x8f, 0xed, 0x07, 0x3c,
	0x8e, 0xa3, 0x74, 0x7f, 0xcc, 0x65, 0x5f, 0x09, 0x1a, 0x30, 0x5f, 0x48, 0x9e, 0x72, 0xbb, 0x31,
	0x0d, 0xb4, 0xbc, 0x30, 0x4a, 0x0f, 0x87, 0x07, 0x7e, 0xc0, 0xe3, 0x76, 0xc8, 0x43, 0xde, 0x06,
	0xc6, 0xc1, 0xb0, 0x07, 0x37, 0xb8, 0xc0, 0xc9, 0x64, 0xb6, 0x1e, 0x97, 0xe8, 0xf1, 0x38, 0x4a,
	0xfb, 0x7c, 0xdc, 0x0e, 0xb9, 0x07, 0xa0, 0x37, 0xa2, 0x83, 0xa8, 0x4b, 0x53, 0x2e, 0x55, 0x7b,
	0x7a, 0x34, 0x79, 0xf8, 0x7b, 0x0d, 0xb5, 0x76, 0x68, 0x8f, 0xbd, 0x80, 0x81, 0xf6, 0x26, 0xed,
	0x09, 0xfb, 0x30, 0x64, 0x2a, 0xb5, 0x37, 0xd0, 0x7c, 0xcc, 0x94, 0xa2, 0x21, 0x73, 0xac, 0x15,
	0x6b, 0xbd, 0xd1, 0xb1, 0xf3, 0xcc, 0xbd, 0xde, 0xe3, 0x32, 0x7e, 0x8a, 0x0b, 0x00, 0x93, 0x09,
	0xc5, 0xfe, 0x6c, 0xa1, 0x86, 0xa0, 0x41, 0x9f, 0x86, 0x6c, 0xbb, 0xeb, 0xcc, 0x41, 0xc2, 0x20,
	0xcf, 0xdc, 0x25, 0x93, 0x30, 0x85, 0xf0, 0x8f, 0x6f, 0xee, 0x2e, 0x22, 0xef, 0xdf, 0x3e, 0xa3,
	0xde, 0xc7, 0xe7, 0xde, 0x9b, 0xfb, 0xde, 0x93, 0x77, 0x9f, 0xb6, 0x4e, 0xbc, 0x53, 0xf7, 0x47,
	0xff, 0x78, 0x7f, 0xb0, 0x79, 0x72, 0x97, 0xcc, 0xda, 0xc3, 0x30, 0x23, 0x26, 0x55, 0xc4, 0x93,
	0xed, 0xae, 0x53, 0x39, 0x3b, 0xcc, 0x14, 0xfa, 0x8f, 0xc3, 0x4c, 0x7b, 0xd8, 0x3e, 0xba, 0xca,
	0x92, 0xd1, 0x7e, 0x7a, 0x2c, 0x98, 0x53, 0x5d, 0xb1, 0xd6, 0x6b, 0x9d, 0x9b, 0x79, 0xe6, 0x2e,
	0x9a, 0x51, 0x26, 0x08, 0x26, 0xf3, 0x2c, 0x19, 0xed, 0x1e, 0x0b, 0x66, 0xef, 0xa1, 0xba, 0xe2,
	0x43, 0x19, 0x30, 0xa7, 0xb6, 0x62, 0xad, 0x37, 0x37, 0x37, 0xfc, 0xd9, 0xaa, 0x9c, 0xff, 0x77,
	0xf9, 0x3b, 0x90, 0xd3, 0xb9, 0x91, 0x67, 0xee, 0x82, 0xa9, 0x6d, 0xaa, 0x60, 0x52, 0x94, 0xb3,
	0xef, 0xa1, 0x6a, 0x42, 0x63, 0xe6, 0xd4, 0xc1, 0x8f, 0xdb, 0x79, 0xe6, 0x36, 0x0d, 0x51, 0x47,
	0xb5, 0x15, 0x55, 0x71, 0xe5, 0xc8, 0x27, 0x40, 0x6a, 0x7d, 0xb5, 0x50, 0xdd, 0x94, 0xd4, 0x8b,
	0xc0, 0x12, 0xf5, 0x5a, 0xa7, 0xfe, 0xb6, 0x08, 0x05, 0x00, 0xe3, 0xc3, 0xc9, 0x5e, 0x45, 0xd5,
	0x43, 0xae, 0xd2, 0x62, 0x05, 0x16, 0x67, 0x5d, 0x74, 0x14, 0x13, 0x00, 0x35, 0x09, 0xfc, 0xa8,
	0x9c, 0x25, 0x19, 0x2f, 0x00, 0xb4, 0xef, 0xa0, 0xb9, 0x48, 0x80, 0x65, 0x8d, 0xce, 0x42, 0x9e,
	0xb9, 0x0d, 0x43, 0x89, 0x04, 0x26, 0x73, 0x91, 0xd0, 0x35, 0x04, 0x97, 0x29, 0xb8, 0x54, 0x2b,
	0xd7, 0xd0, 0x51, 0x4c, 0x00, 0xc4, 0x5f, 0x2c, 0xb4, 0xfc, 0x47, 0xd3, 0x94, 0xe0, 0x89, 0x82,
	0x69, 0x03, 0xde, 0x35, 0xc2, 0x4e, 0x15, 0xd1, 0x51, 0x4c, 0x00, 0xb4, 0xd7, 0x50, 0x8d, 0x49,
	0xc9, 0x65, 0xa1, 0x69, 0x29, 0xcf, 0xdc, 0x6b, 0x85, 0x7c, 0x1d, 0xc6, 0xc4, 0xc0, 0xe5, 0x17,
	0x53, 0xb9, 0xfc, 0xc5, 0xac, 0xa2, 0x6a, 0x97, 0xa6, 0xb4, 0x10, 0x58, 0x6a, 0xad, 0xa3, 0x98,
	0x00, 0x88, 0x7f, 0x5a, 0x08, 0x5f, 0x30, 0xff, 0x9e, 0xa4, 0x42, 0x30, 0xf9, 0x77, 0x32, 0xb6,
	0x50, 0x53, 0xff, 0xbe, 0x3c, 0x12, 0x03, 0x1a, 0x25, 0x85, 0x98, 0x5b, 0x79, 0xe6, 0xda, 0x33,
	0x6e, 0x01, 0x62, 0x52, 0xa6, 0xce, 0x0c, 0xa8, 0x5c, 0x6c, 0xc0, 0xab, 0x92, 0xa4, 0xe6, 0xe6,
	0xda, 0x65, 0x8b, 0x6b, 0x34, 0x9c, 0x23, 0xfd, 0xa0, 0x0e, 0x5f, 0xa9, 0x87, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x21, 0x6a, 0x02, 0xc3, 0x36, 0x05, 0x00, 0x00,
}
