// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: users_register.proto

package gateway

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//UserRegister请求
type UserRegisterRequest struct {
	//
	//用户名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name"`
	//
	//密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" form:"password"`
	//
	//邮箱
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email" form:"email"`
	//
	//邀请码
	Invite               string   `protobuf:"bytes,4,opt,name=invite,proto3" json:"invite" form:"invite"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_35060db285f05563, []int{0}
}
func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegisterRequest) GetInvite() string {
	if m != nil {
		return m.Invite
	}
	return ""
}

//
//UserRegister返回
type UserRegisterResponse struct {
	//
	//用户名
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name"`
	//
	//邮箱
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email" form:"email"`
	//
	//org
	Org                  int32    `protobuf:"varint,3,opt,name=org,proto3" json:"org" form:"org"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_35060db285f05563, []int{1}
}
func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRegisterResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegisterResponse) GetOrg() int32 {
	if m != nil {
		return m.Org
	}
	return 0
}

//
//UserRegisterApi返回
type UserRegisterResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *UserRegisterResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserRegisterResponseWrapper) Reset()         { *m = UserRegisterResponseWrapper{} }
func (m *UserRegisterResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponseWrapper) ProtoMessage()    {}
func (*UserRegisterResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_35060db285f05563, []int{2}
}
func (m *UserRegisterResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponseWrapper.Unmarshal(m, b)
}
func (m *UserRegisterResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponseWrapper.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponseWrapper.Merge(m, src)
}
func (m *UserRegisterResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponseWrapper.Size(m)
}
func (m *UserRegisterResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponseWrapper proto.InternalMessageInfo

func (m *UserRegisterResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserRegisterResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *UserRegisterResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UserRegisterResponseWrapper) GetData() *UserRegisterResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserRegisterRequest)(nil), "gateway.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "gateway.UserRegisterResponse")
	proto.RegisterType((*UserRegisterResponseWrapper)(nil), "gateway.UserRegisterResponseWrapper")
}

func init() { proto.RegisterFile("users_register.proto", fileDescriptor_35060db285f05563) }

var fileDescriptor_35060db285f05563 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x25, 0x69, 0x52, 0xf5, 0x46, 0xad, 0x4e, 0x8b, 0x84, 0x8a, 0x6c, 0x9d, 0x16, 0x69, 0xd0,
	0xd9, 0xd5, 0x16, 0x4a, 0x55, 0x04, 0x1b, 0xf0, 0xc5, 0x37, 0x07, 0x44, 0x68, 0x92, 0x96, 0x49,
	0x33, 0x1d, 0x07, 0xb3, 0x99, 0x75, 0x66, 0xd2, 0x68, 0xa5, 0x7f, 0xc7, 0x9f, 0xb5, 0x82, 0x4f,
	0xbe, 0xf8, 0xb2, 0xbf, 0x40, 0x66, 0x66, 0x9b, 0xae, 0x90, 0x47, 0x7d, 0xda, 0x3b, 0xe7, 0x9c,
	0xfb, 0x71, 0xee, 0xce, 0xc0, 0xda, 0xd4, 0x70, 0x6d, 0x8e, 0x35, 0x17, 0xd2, 0x58, 0xae, 0xe3,
	0x4c, 0x2b, 0xab, 0xd0, 0x35, 0xc1, 0x2c, 0x9f, 0xb1, 0xaf, 0xeb, 0x44, 0x48, 0xfb, 0x71, 0x3a,
	0x8c, 0x4f, 0x54, 0x9a, 0x08, 0x25, 0x54, 0xe2, 0xf9, 0xe1, 0xf4, 0xd4, 0x9f, 0xfc, 0xc1, 0x47,
	0x21, 0x6f, 0x7d, 0xaf, 0x22, 0x4f, 0x67, 0xd2, 0x7e, 0x52, 0xb3, 0x44, 0x28, 0xe2, 0x49, 0x72,
	0xc6, 0xc6, 0x72, 0xc4, 0xac, 0xd2, 0x26, 0x99, 0x87, 0x21, 0x0f, 0x7f, 0xaf, 0xc3, 0xea, 0x7b,
	0xc3, 0x35, 0x2d, 0xc7, 0xa0, 0xfc, 0xf3, 0x94, 0x1b, 0x8b, 0xde, 0x42, 0x63, 0xc2, 0x52, 0xde,
	0xae, 0x6d, 0xd4, 0xb6, 0x6f, 0x74, 0xf7, 0x8a, 0x3c, 0x6a, 0x9d, 0x2a, 0x9d, 0xbe, 0xc0, 0x0e,
	0xc5, 0x3f, 0x7f, 0x44, 0x9b, 0xf0, 0xf0, 0xa8, 0xc7, 0xc8, 0xf9, 0x01, 0x39, 0x7c, 0x4a, 0x9e,
	0x0f, 0x7a, 0xf1, 0x3c, 0x3e, 0x26, 0x83, 0x6f, 0x3b, 0x4f, 0x76, 0x9f, 0x5d, 0x6c, 0x51, 0x5f,
	0x03, 0x25, 0x70, 0x3d, 0x63, 0xc6, 0xcc, 0x94, 0x1e, 0xb5, 0xeb, 0xbe, 0xde, 0x6a, 0x91, 0x47,
	0x2b, 0xa1, 0xde, 0x25, 0x83, 0xe9, 0x5c, 0x84, 0x04, 0x34, 0x79, 0xca, 0xe4, 0xb8, 0xbd, 0xe4,
	0xd5, 0xef, 0x8a, 0x3c, 0xba, 0x19, 0xd4, 0x1e, 0x76, 0xed, 0x5f, 0xc1, 0xcb, 0xa3, 0xed, 0xde,
	0x01, 0x39, 0x64, 0xe4, 0xdc, 0xf5, 0xec, 0x93, 0x7e, 0x3c, 0xe8, 0x3c, 0xee, 0xbf, 0x5e, 0x04,
	0xc6, 0x97, 0xa0, 0x1b, 0x6c, 0xff, 0xa2, 0xb3, 0x45, 0x43, 0x7d, 0xd4, 0x81, 0x65, 0x39, 0x39,
	0x93, 0x96, 0xb7, 0x1b, 0xbe, 0xd3, 0xdd, 0x22, 0x8f, 0x6e, 0x85, 0x4e, 0x01, 0xc7, 0xb4, 0x14,
	0xe0, 0xdf, 0x35, 0x58, 0xfb, 0x7b, 0x51, 0x26, 0x53, 0x13, 0xc3, 0xff, 0xe9, 0xa6, 0xe6, 0xc6,
	0xeb, 0xff, 0xd9, 0xf8, 0x06, 0x2c, 0x29, 0x2d, 0xfc, 0x7e, 0x9b, 0xdd, 0xdb, 0x45, 0x1e, 0x41,
	0x68, 0xa3, 0xb4, 0xc0, 0xd4, 0x51, 0xf8, 0x57, 0x0d, 0xee, 0x2f, 0xf2, 0xfb, 0x41, 0xb3, 0x2c,
	0xe3, 0x1a, 0x6d, 0x42, 0xe3, 0x44, 0x8d, 0x82, 0xed, 0x66, 0x77, 0xe5, 0xca, 0xb6, 0x43, 0x31,
	0xf5, 0x24, 0xda, 0x87, 0x96, 0xfb, 0xbe, 0xf9, 0x92, 0x8d, 0x99, 0x9c, 0x94, 0xae, 0xee, 0x15,
	0x79, 0x84, 0xae, 0xb4, 0x25, 0x89, 0x69, 0x55, 0x8a, 0x1e, 0x41, 0x93, 0x6b, 0xad, 0x74, 0x79,
	0x05, 0xee, 0x54, 0x36, 0xe1, 0x60, 0x4c, 0x03, 0x8d, 0xba, 0xd0, 0x18, 0x31, 0xcb, 0xfc, 0xff,
	0x6b, 0xed, 0x3c, 0x88, 0xcb, 0xe7, 0x13, 0x2f, 0x1a, 0xbd, 0x3a, 0xa5, 0x4b, 0xc2, 0xd4, 0xe7,
	0x0e, 0x97, 0xfd, 0x53, 0xd8, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x9e, 0xbb, 0x3f, 0x92,
	0x03, 0x00, 0x00,
}
