// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: property.proto

package topology

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Property) Validate() error {
	if this.Strategy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Strategy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Strategy", err)
		}
	}
	for _, item := range this.RelateInstances {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RelateInstances", err)
			}
		}
	}
	return nil
}
