// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: list.proto

package sqlpkg_versions

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//ListSQLPackageVersion请求
type ListSQLPackageVersionRequest struct {
	//
	//SQL包ID
	PkgId string `protobuf:"bytes,1,opt,name=pkgId,proto3" json:"pkgId" form:"pkgId"`
	//
	//页码
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" form:"page"`
	//
	//每页数据量
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize" form:"pageSize"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSQLPackageVersionRequest) Reset()         { *m = ListSQLPackageVersionRequest{} }
func (m *ListSQLPackageVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ListSQLPackageVersionRequest) ProtoMessage()    {}
func (*ListSQLPackageVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{0}
}
func (m *ListSQLPackageVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSQLPackageVersionRequest.Unmarshal(m, b)
}
func (m *ListSQLPackageVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSQLPackageVersionRequest.Marshal(b, m, deterministic)
}
func (m *ListSQLPackageVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSQLPackageVersionRequest.Merge(m, src)
}
func (m *ListSQLPackageVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ListSQLPackageVersionRequest.Size(m)
}
func (m *ListSQLPackageVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSQLPackageVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSQLPackageVersionRequest proto.InternalMessageInfo

func (m *ListSQLPackageVersionRequest) GetPkgId() string {
	if m != nil {
		return m.PkgId
	}
	return ""
}

func (m *ListSQLPackageVersionRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSQLPackageVersionRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

//
//ListSQLPackageVersion返回
type ListSQLPackageVersionResponse struct {
	//
	//页数
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" form:"page"`
	//
	//页大小
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//总数
	Total int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total" form:"total"`
	//
	//数据列表
	List                 []*ListSQLPackageVersionResponse_List `protobuf:"bytes,4,rep,name=list,proto3" json:"list" form:"list"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ListSQLPackageVersionResponse) Reset()         { *m = ListSQLPackageVersionResponse{} }
func (m *ListSQLPackageVersionResponse) String() string { return proto.CompactTextString(m) }
func (*ListSQLPackageVersionResponse) ProtoMessage()    {}
func (*ListSQLPackageVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1}
}
func (m *ListSQLPackageVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSQLPackageVersionResponse.Unmarshal(m, b)
}
func (m *ListSQLPackageVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSQLPackageVersionResponse.Marshal(b, m, deterministic)
}
func (m *ListSQLPackageVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSQLPackageVersionResponse.Merge(m, src)
}
func (m *ListSQLPackageVersionResponse) XXX_Size() int {
	return xxx_messageInfo_ListSQLPackageVersionResponse.Size(m)
}
func (m *ListSQLPackageVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSQLPackageVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSQLPackageVersionResponse proto.InternalMessageInfo

func (m *ListSQLPackageVersionResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSQLPackageVersionResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListSQLPackageVersionResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListSQLPackageVersionResponse) GetList() []*ListSQLPackageVersionResponse_List {
	if m != nil {
		return m.List
	}
	return nil
}

type ListSQLPackageVersionResponse_List struct {
	//
	//所属的SQL包
	SqlPackage *ListSQLPackageVersionResponse_List_SqlPackage `protobuf:"bytes,1,opt,name=sqlPackage,proto3" json:"sqlPackage" form:"sqlPackage"`
	//
	//版本ID
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id" form:"id"`
	//
	//名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name" form:"name"`
	//
	//仓库版本ID
	RepoVersionId string `protobuf:"bytes,4,opt,name=repoVersionId,proto3" json:"repoVersionId" form:"repoVersionId"`
	//
	//程序包版本ID
	AppVersionId string `protobuf:"bytes,5,opt,name=appVersionId,proto3" json:"appVersionId" form:"appVersionId"`
	//
	//版本名称
	VersionName string `protobuf:"bytes,6,opt,name=versionName,proto3" json:"versionName" form:"versionName"`
	//
	//备注
	Memo string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo" form:"memo"`
	//
	//创建者
	Creator string `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator" form:"creator"`
	//
	//创建时间
	Ctime int64 `protobuf:"varint,9,opt,name=ctime,proto3" json:"ctime" form:"ctime"`
	//
	//修改时间
	Mtime                int64    `protobuf:"varint,10,opt,name=mtime,proto3" json:"mtime" form:"mtime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSQLPackageVersionResponse_List) Reset()         { *m = ListSQLPackageVersionResponse_List{} }
func (m *ListSQLPackageVersionResponse_List) String() string { return proto.CompactTextString(m) }
func (*ListSQLPackageVersionResponse_List) ProtoMessage()    {}
func (*ListSQLPackageVersionResponse_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1, 0}
}
func (m *ListSQLPackageVersionResponse_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSQLPackageVersionResponse_List.Unmarshal(m, b)
}
func (m *ListSQLPackageVersionResponse_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSQLPackageVersionResponse_List.Marshal(b, m, deterministic)
}
func (m *ListSQLPackageVersionResponse_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSQLPackageVersionResponse_List.Merge(m, src)
}
func (m *ListSQLPackageVersionResponse_List) XXX_Size() int {
	return xxx_messageInfo_ListSQLPackageVersionResponse_List.Size(m)
}
func (m *ListSQLPackageVersionResponse_List) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSQLPackageVersionResponse_List.DiscardUnknown(m)
}

var xxx_messageInfo_ListSQLPackageVersionResponse_List proto.InternalMessageInfo

func (m *ListSQLPackageVersionResponse_List) GetSqlPackage() *ListSQLPackageVersionResponse_List_SqlPackage {
	if m != nil {
		return m.SqlPackage
	}
	return nil
}

func (m *ListSQLPackageVersionResponse_List) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetRepoVersionId() string {
	if m != nil {
		return m.RepoVersionId
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetAppVersionId() string {
	if m != nil {
		return m.AppVersionId
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *ListSQLPackageVersionResponse_List) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

type ListSQLPackageVersionResponse_List_SqlPackage struct {
	//
	//SQL包ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	//
	//名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	//
	//描述
	Memo string `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo" form:"memo"`
	//
	//文件仓库包ID
	RepoPackageId string `protobuf:"bytes,4,opt,name=repoPackageId,proto3" json:"repoPackageId" form:"repoPackageId"`
	//
	//创建者
	Creator string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator" form:"creator"`
	//
	//mtime
	Mtime                int64    `protobuf:"varint,6,opt,name=mtime,proto3" json:"mtime" form:"mtime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSQLPackageVersionResponse_List_SqlPackage) Reset() {
	*m = ListSQLPackageVersionResponse_List_SqlPackage{}
}
func (m *ListSQLPackageVersionResponse_List_SqlPackage) String() string {
	return proto.CompactTextString(m)
}
func (*ListSQLPackageVersionResponse_List_SqlPackage) ProtoMessage() {}
func (*ListSQLPackageVersionResponse_List_SqlPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1, 0, 0}
}
func (m *ListSQLPackageVersionResponse_List_SqlPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSQLPackageVersionResponse_List_SqlPackage.Unmarshal(m, b)
}
func (m *ListSQLPackageVersionResponse_List_SqlPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSQLPackageVersionResponse_List_SqlPackage.Marshal(b, m, deterministic)
}
func (m *ListSQLPackageVersionResponse_List_SqlPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSQLPackageVersionResponse_List_SqlPackage.Merge(m, src)
}
func (m *ListSQLPackageVersionResponse_List_SqlPackage) XXX_Size() int {
	return xxx_messageInfo_ListSQLPackageVersionResponse_List_SqlPackage.Size(m)
}
func (m *ListSQLPackageVersionResponse_List_SqlPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSQLPackageVersionResponse_List_SqlPackage.DiscardUnknown(m)
}

var xxx_messageInfo_ListSQLPackageVersionResponse_List_SqlPackage proto.InternalMessageInfo

func (m *ListSQLPackageVersionResponse_List_SqlPackage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List_SqlPackage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List_SqlPackage) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List_SqlPackage) GetRepoPackageId() string {
	if m != nil {
		return m.RepoPackageId
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List_SqlPackage) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ListSQLPackageVersionResponse_List_SqlPackage) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

//
//ListSQLPackageVersionApi返回
type ListSQLPackageVersionResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *ListSQLPackageVersionResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListSQLPackageVersionResponseWrapper) Reset()         { *m = ListSQLPackageVersionResponseWrapper{} }
func (m *ListSQLPackageVersionResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ListSQLPackageVersionResponseWrapper) ProtoMessage()    {}
func (*ListSQLPackageVersionResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{2}
}
func (m *ListSQLPackageVersionResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSQLPackageVersionResponseWrapper.Unmarshal(m, b)
}
func (m *ListSQLPackageVersionResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSQLPackageVersionResponseWrapper.Marshal(b, m, deterministic)
}
func (m *ListSQLPackageVersionResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSQLPackageVersionResponseWrapper.Merge(m, src)
}
func (m *ListSQLPackageVersionResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ListSQLPackageVersionResponseWrapper.Size(m)
}
func (m *ListSQLPackageVersionResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSQLPackageVersionResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ListSQLPackageVersionResponseWrapper proto.InternalMessageInfo

func (m *ListSQLPackageVersionResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListSQLPackageVersionResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *ListSQLPackageVersionResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListSQLPackageVersionResponseWrapper) GetData() *ListSQLPackageVersionResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListSQLPackageVersionRequest)(nil), "sqlpkg_versions.ListSQLPackageVersionRequest")
	proto.RegisterType((*ListSQLPackageVersionResponse)(nil), "sqlpkg_versions.ListSQLPackageVersionResponse")
	proto.RegisterType((*ListSQLPackageVersionResponse_List)(nil), "sqlpkg_versions.ListSQLPackageVersionResponse.List")
	proto.RegisterType((*ListSQLPackageVersionResponse_List_SqlPackage)(nil), "sqlpkg_versions.ListSQLPackageVersionResponse.List.SqlPackage")
	proto.RegisterType((*ListSQLPackageVersionResponseWrapper)(nil), "sqlpkg_versions.ListSQLPackageVersionResponseWrapper")
}

func init() { proto.RegisterFile("list.proto", fileDescriptor_af793ce248ee1bf0) }

var fileDescriptor_af793ce248ee1bf0 = []byte{
	// 728 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x3e, 0xf9, 0x6b, 0x9b, 0x4d, 0x4f, 0x9b, 0xb3, 0x87, 0x1f, 0x13, 0x81, 0x9c, 0x6e, 0x23,
	0x14, 0x24, 0x9c, 0xb4, 0x89, 0xf8, 0x69, 0x91, 0x2a, 0x11, 0x89, 0x8b, 0x4a, 0x15, 0x82, 0x8d,
	0x04, 0x88, 0xaa, 0xad, 0xb6, 0xc9, 0xd6, 0x58, 0x89, 0xb3, 0xae, 0xed, 0xb4, 0xa8, 0x55, 0x6f,
	0x78, 0x11, 0x2e, 0x79, 0x09, 0xae, 0x79, 0x0c, 0x23, 0xf1, 0x08, 0x7e, 0x02, 0xb4, 0xb3, 0x4e,
	0xb2, 0x0d, 0x6a, 0x10, 0x15, 0x57, 0x6b, 0xcf, 0xf7, 0xcd, 0xec, 0x37, 0xdf, 0x4c, 0x1c, 0x84,
	0xfa, 0x4e, 0x10, 0xd6, 0x3c, 0x5f, 0x84, 0x02, 0x2f, 0x07, 0xc7, 0x7d, 0xaf, 0x67, 0x1f, 0x9c,
	0x70, 0x3f, 0x70, 0xc4, 0x20, 0x28, 0x59, 0xb6, 0x13, 0x7e, 0x18, 0x1e, 0xd6, 0x3a, 0xc2, 0xad,
	0xdb, 0xc2, 0x16, 0x75, 0xe0, 0x1d, 0x0e, 0x8f, 0xe0, 0x0d, 0x5e, 0xe0, 0x49, 0xe5, 0x97, 0x1e,
	0x6b, 0x74, 0xf7, 0xd4, 0x09, 0x7b, 0xe2, 0xb4, 0x6e, 0x0b, 0x0b, 0x40, 0xeb, 0x84, 0xf5, 0x9d,
	0x2e, 0x0b, 0x85, 0x1f, 0xd4, 0xc7, 0x8f, 0x2a, 0x8f, 0x7c, 0x4d, 0xa1, 0xbb, 0x3b, 0x4e, 0x10,
	0xb6, 0x5f, 0xef, 0xbc, 0x62, 0x9d, 0x1e, 0xb3, 0xf9, 0x1b, 0xa5, 0x80, 0xf2, 0xe3, 0x21, 0x0f,
	0x42, 0xbc, 0x89, 0x72, 0x5e, 0xcf, 0xde, 0xee, 0x1a, 0xa9, 0x72, 0xaa, 0x9a, 0x6f, 0x55, 0xe2,
	0xc8, 0x5c, 0x3c, 0x12, 0xbe, 0xbb, 0x49, 0x20, 0x4c, 0x7e, 0x7c, 0x37, 0x8b, 0x68, 0x69, 0x7f,
	0x77, 0xcd, 0xda, 0x60, 0xd6, 0xd9, 0xde, 0xf9, 0x7a, 0xf3, 0xa2, 0x42, 0x55, 0x0a, 0x7e, 0x80,
	0xb2, 0x1e, 0xb3, 0xb9, 0x91, 0x2e, 0xa7, 0xaa, 0xb9, 0xd6, 0xcd, 0x38, 0x32, 0x0b, 0x49, 0x2a,
	0xb3, 0xb9, 0xcc, 0x4c, 0x17, 0xff, 0xa1, 0x40, 0xc1, 0x8f, 0xd0, 0x82, 0x3c, 0xdb, 0xce, 0x19,
	0x37, 0x32, 0x40, 0xbf, 0x13, 0x47, 0xe6, 0xf2, 0x84, 0x2e, 0x91, 0x51, 0xca, 0x98, 0x4a, 0xbe,
	0xe4, 0xd1, 0xbd, 0x2b, 0xe4, 0x07, 0x9e, 0x18, 0x04, 0x7c, 0xac, 0x21, 0xf5, 0x7b, 0x0d, 0x4f,
	0x50, 0x5e, 0x9e, 0x07, 0x81, 0x14, 0xa1, 0x34, 0x97, 0xe2, 0xc8, 0x2c, 0x4e, 0xf8, 0x00, 0xfd,
	0xa2, 0x02, 0xdf, 0x47, 0xb9, 0x50, 0x84, 0xac, 0x9f, 0x28, 0x2f, 0x4e, 0x3c, 0x82, 0x30, 0xa1,
	0x0a, 0xc6, 0xef, 0x50, 0x56, 0x8e, 0xdc, 0xc8, 0x96, 0x33, 0xd5, 0x42, 0xa3, 0x59, 0x9b, 0x9a,
	0x79, 0x6d, 0x66, 0x27, 0x80, 0xb6, 0x96, 0x27, 0x0d, 0xc8, 0x52, 0x84, 0x42, 0xc5, 0xd2, 0xe7,
	0x79, 0x94, 0x95, 0x38, 0x1e, 0x22, 0x14, 0x1c, 0xf7, 0x93, 0x0a, 0xd0, 0x74, 0xa1, 0xb1, 0x75,
	0x8d, 0x8b, 0x6a, 0xed, 0x71, 0x15, 0x30, 0xed, 0x3f, 0x75, 0xe7, 0xa4, 0x36, 0xa1, 0xda, 0x45,
	0x78, 0x1d, 0xa5, 0x9d, 0x2e, 0x78, 0x96, 0x6f, 0xad, 0xc4, 0x91, 0x99, 0x57, 0x74, 0xe7, 0x8a,
	0xfd, 0x48, 0x3b, 0x5d, 0xbc, 0x8a, 0xb2, 0x03, 0xe6, 0xaa, 0x69, 0xe7, 0xf5, 0xbe, 0x64, 0x94,
	0x50, 0x00, 0xf1, 0x16, 0xfa, 0xd7, 0xe7, 0x9e, 0x48, 0x14, 0x6e, 0x77, 0x8d, 0x2c, 0xb0, 0x8d,
	0x38, 0x32, 0x6f, 0x28, 0xf6, 0x25, 0x98, 0xd0, 0xcb, 0x74, 0xfc, 0x0c, 0x2d, 0x32, 0xcf, 0x9b,
	0xa4, 0xe7, 0x20, 0xfd, 0x76, 0x1c, 0x99, 0xff, 0xab, 0x74, 0x1d, 0x25, 0xf4, 0x12, 0x19, 0x3f,
	0x45, 0x85, 0xc4, 0xb1, 0x97, 0x52, 0xe8, 0x1c, 0xe4, 0xde, 0x8a, 0x23, 0x13, 0xab, 0x5c, 0x0d,
	0x24, 0x54, 0xa7, 0xca, 0xde, 0x5c, 0xee, 0x0a, 0x63, 0x7e, 0xba, 0x37, 0x19, 0x25, 0x14, 0x40,
	0xdc, 0x46, 0xf3, 0x1d, 0x9f, 0xcb, 0xdf, 0xa2, 0xb1, 0x00, 0xbc, 0x8d, 0x38, 0x32, 0x97, 0x14,
	0x2f, 0x01, 0xa4, 0x7b, 0xab, 0x68, 0x65, 0x7f, 0x97, 0x59, 0x67, 0xcf, 0xad, 0xf7, 0x6b, 0xd6,
	0xc6, 0xde, 0x6e, 0x6d, 0xfc, 0x7c, 0x60, 0xed, 0x9d, 0x37, 0x1e, 0x36, 0xd7, 0x2f, 0x2a, 0x74,
	0x54, 0x49, 0xae, 0x62, 0x27, 0x74, 0x5c, 0x6e, 0xe4, 0xcb, 0xa9, 0x6a, 0x46, 0x5f, 0x45, 0x08,
	0x13, 0xaa, 0x60, 0xc9, 0x73, 0x81, 0x87, 0xa6, 0x79, 0x6e, 0xc2, 0x83, 0xb3, 0xf4, 0x2d, 0x8d,
	0x50, 0x7b, 0x7a, 0xce, 0xa9, 0xeb, 0xcc, 0x39, 0x3d, 0x6b, 0xce, 0x23, 0xc3, 0x32, 0xb3, 0x0c,
	0x4b, 0x96, 0x21, 0xd1, 0x72, 0xd5, 0x32, 0x8c, 0xe1, 0x64, 0x19, 0xc6, 0xef, 0xba, 0xe1, 0xb9,
	0xbf, 0x69, 0xb8, 0x32, 0x72, 0x6e, 0xa6, 0x91, 0xe4, 0x53, 0x1a, 0x55, 0x66, 0xfe, 0xec, 0xde,
	0xfa, 0xcc, 0xf3, 0xb8, 0x2f, 0xad, 0xe8, 0x88, 0xee, 0xe8, 0x83, 0xa5, 0x59, 0x21, 0xa3, 0x84,
	0x02, 0x28, 0x57, 0x53, 0x9e, 0x2f, 0x3e, 0x7a, 0x7d, 0xe6, 0x0c, 0x12, 0x6f, 0xb5, 0xd5, 0xd4,
	0x40, 0x42, 0x75, 0xaa, 0xd4, 0xcb, 0x7d, 0x5f, 0xf8, 0x89, 0xd5, 0x9a, 0x5e, 0x08, 0x13, 0xaa,
	0x60, 0xdc, 0x46, 0xd9, 0x2e, 0x0b, 0x19, 0x78, 0x5c, 0x68, 0xd4, 0xfe, 0xec, 0x13, 0xa2, 0xcb,
	0x96, 0x55, 0x08, 0x85, 0x62, 0x87, 0x73, 0xf0, 0xa7, 0xd3, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff,
	0xc2, 0x3e, 0x27, 0xb0, 0xfa, 0x06, 0x00, 0x00,
}
