// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: delete_storageclass.proto

package storageclass

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//DeleteStorageClass请求
type DeleteStorageClassRequest struct {
	//
	//StorageClass ID
	InstanceId           string   `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId" form:"instanceId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStorageClassRequest) Reset()         { *m = DeleteStorageClassRequest{} }
func (m *DeleteStorageClassRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStorageClassRequest) ProtoMessage()    {}
func (*DeleteStorageClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4215f5c209c6f1f, []int{0}
}
func (m *DeleteStorageClassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorageClassRequest.Unmarshal(m, b)
}
func (m *DeleteStorageClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorageClassRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStorageClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorageClassRequest.Merge(m, src)
}
func (m *DeleteStorageClassRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStorageClassRequest.Size(m)
}
func (m *DeleteStorageClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorageClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorageClassRequest proto.InternalMessageInfo

func (m *DeleteStorageClassRequest) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

//
//DeleteStorageClassApi返回
type DeleteStorageClassResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *types.Empty `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteStorageClassResponseWrapper) Reset()         { *m = DeleteStorageClassResponseWrapper{} }
func (m *DeleteStorageClassResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*DeleteStorageClassResponseWrapper) ProtoMessage()    {}
func (*DeleteStorageClassResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4215f5c209c6f1f, []int{1}
}
func (m *DeleteStorageClassResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStorageClassResponseWrapper.Unmarshal(m, b)
}
func (m *DeleteStorageClassResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStorageClassResponseWrapper.Marshal(b, m, deterministic)
}
func (m *DeleteStorageClassResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStorageClassResponseWrapper.Merge(m, src)
}
func (m *DeleteStorageClassResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_DeleteStorageClassResponseWrapper.Size(m)
}
func (m *DeleteStorageClassResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStorageClassResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStorageClassResponseWrapper proto.InternalMessageInfo

func (m *DeleteStorageClassResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteStorageClassResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *DeleteStorageClassResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteStorageClassResponseWrapper) GetData() *types.Empty {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteStorageClassRequest)(nil), "storageclass.DeleteStorageClassRequest")
	proto.RegisterType((*DeleteStorageClassResponseWrapper)(nil), "storageclass.DeleteStorageClassResponseWrapper")
}

func init() { proto.RegisterFile("delete_storageclass.proto", fileDescriptor_e4215f5c209c6f1f) }

var fileDescriptor_e4215f5c209c6f1f = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4f, 0xfb, 0x30,
	0x10, 0xc6, 0x95, 0xff, 0xbf, 0x45, 0xc2, 0xad, 0xa0, 0x64, 0xa8, 0xd2, 0x32, 0xa4, 0x18, 0x84,
	0xca, 0x90, 0x04, 0xa8, 0x84, 0x78, 0xd9, 0x0a, 0x1d, 0xba, 0x86, 0x81, 0x01, 0x01, 0x72, 0x13,
	0xd7, 0x44, 0x24, 0xb9, 0x60, 0xbb, 0x94, 0x17, 0xf1, 0x55, 0x83, 0xc4, 0xc2, 0x9e, 0x4f, 0x80,
	0x62, 0x17, 0x9a, 0x81, 0xc9, 0x77, 0xf7, 0x3c, 0x3f, 0xdf, 0xa3, 0x43, 0x9d, 0x90, 0xc6, 0x54,
	0xd2, 0x3b, 0x21, 0x81, 0x13, 0x46, 0x83, 0x98, 0x08, 0xe1, 0x66, 0x1c, 0x24, 0x98, 0xcd, 0xea,
	0xac, 0xeb, 0xb0, 0x48, 0xde, 0xcf, 0x26, 0x6e, 0x00, 0x89, 0xc7, 0x80, 0x81, 0xa7, 0x4c, 0x93,
	0xd9, 0x54, 0x75, 0xaa, 0x51, 0x95, 0x86, 0xbb, 0x47, 0x15, 0x7b, 0x32, 0x8f, 0xe4, 0x03, 0xcc,
	0x3d, 0x06, 0x8e, 0x12, 0x9d, 0x27, 0x12, 0x47, 0x21, 0x91, 0xc0, 0x85, 0xf7, 0x5b, 0x2e, 0xb8,
	0x4d, 0x06, 0xc0, 0x62, 0xba, 0xfc, 0x9d, 0x26, 0x99, 0x7c, 0xd1, 0x22, 0x9e, 0xa2, 0xce, 0x85,
	0x8a, 0x7b, 0xa9, 0x93, 0x9d, 0x97, 0xc9, 0x7c, 0xfa, 0x38, 0xa3, 0x42, 0x9a, 0x63, 0x84, 0xa2,
	0x54, 0x48, 0x92, 0x06, 0x74, 0x1c, 0x5a, 0x46, 0xcf, 0xe8, 0xaf, 0x0e, 0xf7, 0x8a, 0xdc, 0xde,
	0x98, 0x02, 0x4f, 0x4e, 0xf1, 0x52, 0xc3, 0x9f, 0x1f, 0x76, 0x0b, 0xad, 0xdd, 0x5e, 0xef, 0x3b,
	0x27, 0xc4, 0x79, 0xbd, 0x79, 0x3b, 0x18, 0xbc, 0xef, 0xf8, 0x15, 0x18, 0x7f, 0x19, 0x68, 0xeb,
	0xaf, 0x45, 0x22, 0x83, 0x54, 0xd0, 0x2b, 0x4e, 0xb2, 0x8c, 0x72, 0x73, 0x1b, 0xd5, 0x02, 0x08,
	0xa9, 0x5a, 0x55, 0x1f, 0xae, 0x17, 0xb9, 0xdd, 0xd0, 0xab, 0xca, 0x29, 0xf6, 0x95, 0x68, 0x1e,
	0xa3, 0x46, 0xf9, 0x8e, 0x9e, 0xb3, 0x98, 0x44, 0xa9, 0xf5, 0x4f, 0xc5, 0x6a, 0x17, 0xb9, 0x6d,
	0x2e, 0xbd, 0x0b, 0x11, 0xfb, 0x55, 0xab, 0xb9, 0x8b, 0xea, 0x94, 0x73, 0xe0, 0xd6, 0x7f, 0xc5,
	0xb4, 0x8a, 0xdc, 0x6e, 0x6a, 0x46, 0x8d, 0xb1, 0xaf, 0x65, 0xf3, 0x0c, 0xd5, 0x42, 0x22, 0x89,
	0x55, 0xeb, 0x19, 0xfd, 0xc6, 0x61, 0xdb, 0xd5, 0x07, 0x74, 0x7f, 0x0e, 0xe8, 0x8e, 0xca, 0x03,
	0x56, 0xe3, 0x95, 0x6e, 0xec, 0x2b, 0x68, 0xb2, 0xa2, 0x6c, 0x83, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe9, 0xb8, 0xe9, 0xa8, 0x07, 0x02, 0x00, 0x00,
}
