// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: replace_metric_states.proto

package stream

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//ReplaceMetricStates返回
type ReplaceMetricStatesResponse struct {
	//
	//推送的状态数据列表
	States               []*ReplaceMetricStatesResponse_States `protobuf:"bytes,1,rep,name=states,proto3" json:"states" form:"states"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ReplaceMetricStatesResponse) Reset()         { *m = ReplaceMetricStatesResponse{} }
func (m *ReplaceMetricStatesResponse) String() string { return proto.CompactTextString(m) }
func (*ReplaceMetricStatesResponse) ProtoMessage()    {}
func (*ReplaceMetricStatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0cc06cdcbdd2b3, []int{0}
}
func (m *ReplaceMetricStatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceMetricStatesResponse.Unmarshal(m, b)
}
func (m *ReplaceMetricStatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceMetricStatesResponse.Marshal(b, m, deterministic)
}
func (m *ReplaceMetricStatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceMetricStatesResponse.Merge(m, src)
}
func (m *ReplaceMetricStatesResponse) XXX_Size() int {
	return xxx_messageInfo_ReplaceMetricStatesResponse.Size(m)
}
func (m *ReplaceMetricStatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceMetricStatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceMetricStatesResponse proto.InternalMessageInfo

func (m *ReplaceMetricStatesResponse) GetStates() []*ReplaceMetricStatesResponse_States {
	if m != nil {
		return m.States
	}
	return nil
}

type ReplaceMetricStatesResponse_States struct {
	//
	//状态数据id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	//
	//状态数据版本
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version" form:"version"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplaceMetricStatesResponse_States) Reset()         { *m = ReplaceMetricStatesResponse_States{} }
func (m *ReplaceMetricStatesResponse_States) String() string { return proto.CompactTextString(m) }
func (*ReplaceMetricStatesResponse_States) ProtoMessage()    {}
func (*ReplaceMetricStatesResponse_States) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0cc06cdcbdd2b3, []int{0, 0}
}
func (m *ReplaceMetricStatesResponse_States) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceMetricStatesResponse_States.Unmarshal(m, b)
}
func (m *ReplaceMetricStatesResponse_States) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceMetricStatesResponse_States.Marshal(b, m, deterministic)
}
func (m *ReplaceMetricStatesResponse_States) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceMetricStatesResponse_States.Merge(m, src)
}
func (m *ReplaceMetricStatesResponse_States) XXX_Size() int {
	return xxx_messageInfo_ReplaceMetricStatesResponse_States.Size(m)
}
func (m *ReplaceMetricStatesResponse_States) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceMetricStatesResponse_States.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceMetricStatesResponse_States proto.InternalMessageInfo

func (m *ReplaceMetricStatesResponse_States) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReplaceMetricStatesResponse_States) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

//
//ReplaceMetricStatesApi返回
type ReplaceMetricStatesResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *ReplaceMetricStatesResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ReplaceMetricStatesResponseWrapper) Reset()         { *m = ReplaceMetricStatesResponseWrapper{} }
func (m *ReplaceMetricStatesResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ReplaceMetricStatesResponseWrapper) ProtoMessage()    {}
func (*ReplaceMetricStatesResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c0cc06cdcbdd2b3, []int{1}
}
func (m *ReplaceMetricStatesResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplaceMetricStatesResponseWrapper.Unmarshal(m, b)
}
func (m *ReplaceMetricStatesResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplaceMetricStatesResponseWrapper.Marshal(b, m, deterministic)
}
func (m *ReplaceMetricStatesResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplaceMetricStatesResponseWrapper.Merge(m, src)
}
func (m *ReplaceMetricStatesResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ReplaceMetricStatesResponseWrapper.Size(m)
}
func (m *ReplaceMetricStatesResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplaceMetricStatesResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ReplaceMetricStatesResponseWrapper proto.InternalMessageInfo

func (m *ReplaceMetricStatesResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplaceMetricStatesResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *ReplaceMetricStatesResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ReplaceMetricStatesResponseWrapper) GetData() *ReplaceMetricStatesResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ReplaceMetricStatesResponse)(nil), "stream.ReplaceMetricStatesResponse")
	proto.RegisterType((*ReplaceMetricStatesResponse_States)(nil), "stream.ReplaceMetricStatesResponse.States")
	proto.RegisterType((*ReplaceMetricStatesResponseWrapper)(nil), "stream.ReplaceMetricStatesResponseWrapper")
}

func init() { proto.RegisterFile("replace_metric_states.proto", fileDescriptor_6c0cc06cdcbdd2b3) }

var fileDescriptor_6c0cc06cdcbdd2b3 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x99, 0x7e, 0xe4, 0x4f, 0x27, 0xff, 0xfa, 0x31, 0x0b, 0x09, 0x2d, 0x92, 0x30, 0x05,
	0x09, 0xa2, 0x29, 0xd4, 0x8d, 0xb8, 0x0c, 0x08, 0x6e, 0xdc, 0x8c, 0x14, 0x97, 0x65, 0x9a, 0x4c,
	0xeb, 0x40, 0xd3, 0x09, 0x93, 0xa9, 0xf8, 0x8e, 0xbe, 0x43, 0x1e, 0x22, 0xe0, 0x5e, 0x7a, 0x6f,
	0xc4, 0xae, 0x8a, 0xab, 0xe4, 0xde, 0x73, 0xce, 0xef, 0x5c, 0x12, 0x3a, 0xb6, 0xaa, 0xdc, 0xc8,
	0x4c, 0x2d, 0x0a, 0xe5, 0xac, 0xce, 0x16, 0x95, 0x93, 0x4e, 0x55, 0x49, 0x69, 0x8d, 0x33, 0xcc,
	0xab, 0x9c, 0x55, 0xb2, 0x18, 0xdd, 0xae, 0xb5, 0x7b, 0xdb, 0x2d, 0x93, 0xcc, 0x14, 0xd3, 0xb5,
	0x59, 0x9b, 0x29, 0xc8, 0xcb, 0xdd, 0x0a, 0x26, 0x18, 0xe0, 0x0d, 0x63, 0xfc, 0x93, 0xd0, 0xb1,
	0x40, 0xec, 0x33, 0x50, 0x5f, 0x00, 0x2a, 0x54, 0x55, 0x9a, 0x6d, 0xa5, 0xd8, 0x9c, 0x7a, 0x58,
	0x13, 0x90, 0xa8, 0x1b, 0xfb, 0xb3, 0xeb, 0x04, 0x7b, 0x92, 0x23, 0xa1, 0x04, 0xc7, 0xf4, 0xbc,
	0xa9, 0xc3, 0xe1, 0xca, 0xd8, 0xe2, 0x81, 0x23, 0x83, 0x8b, 0x16, 0x36, 0x9a, 0x53, 0x0f, 0x4d,
	0xec, 0x92, 0x76, 0x74, 0x1e, 0x90, 0x88, 0xc4, 0x83, 0x74, 0xd8, 0xd4, 0xe1, 0x00, 0x03, 0x3a,
	0xe7, 0xa2, 0xa3, 0x73, 0x76, 0x43, 0xff, 0xbd, 0x2b, 0x5b, 0x69, 0xb3, 0x0d, 0x3a, 0x11, 0x89,
	0xfb, 0x29, 0x6b, 0xea, 0xf0, 0x04, 0x3d, 0xad, 0xc0, 0xc5, 0x8f, 0x85, 0x7f, 0x11, 0xca, 0x8f,
	0x1c, 0xf6, 0x6a, 0x65, 0x59, 0x2a, 0xcb, 0x26, 0xb4, 0x97, 0x99, 0x5c, 0x41, 0x6b, 0x3f, 0x3d,
	0x6d, 0xea, 0xd0, 0x47, 0xe2, 0x7e, 0xcb, 0x05, 0x88, 0xec, 0x9e, 0xfa, 0xfb, 0xe7, 0xe3, 0x47,
	0xb9, 0x91, 0x1a, 0xdb, 0x07, 0xe9, 0x45, 0x53, 0x87, 0xec, 0xd7, 0xdb, 0x8a, 0x5c, 0x1c, 0x5a,
	0xd9, 0x15, 0xed, 0x2b, 0x6b, 0x8d, 0x0d, 0xba, 0x90, 0x39, 0x6b, 0xea, 0xf0, 0x3f, 0x66, 0x60,
	0xcd, 0x05, 0xca, 0xec, 0x89, 0xf6, 0x72, 0xe9, 0x64, 0xd0, 0x8b, 0x48, 0xec, 0xcf, 0x26, 0x7f,
	0xf8, 0xb2, 0x87, 0xb7, 0xee, 0xa3, 0x5c, 0x00, 0x61, 0xe9, 0xc1, 0xcf, 0xbc, 0xfb, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x0e, 0xf1, 0x9a, 0xca, 0x22, 0x02, 0x00, 0x00,
}
