// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: list.proto

package product_line

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	app_store "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/app_store"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//ListProductLines请求
type ListProductLinesRequest struct {
	//
	//页码
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" form:"page"`
	//
	//每页大小
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductLinesRequest) Reset()         { *m = ListProductLinesRequest{} }
func (m *ListProductLinesRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductLinesRequest) ProtoMessage()    {}
func (*ListProductLinesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{0}
}
func (m *ListProductLinesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductLinesRequest.Unmarshal(m, b)
}
func (m *ListProductLinesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductLinesRequest.Marshal(b, m, deterministic)
}
func (m *ListProductLinesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductLinesRequest.Merge(m, src)
}
func (m *ListProductLinesRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductLinesRequest.Size(m)
}
func (m *ListProductLinesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductLinesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductLinesRequest proto.InternalMessageInfo

func (m *ListProductLinesRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListProductLinesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

//
//ListProductLines返回
type ListProductLinesResponse struct {
	//
	//返回总数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total" form:"total"`
	//
	//页数
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" form:"page"`
	//
	//该页大小
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//产品线列表
	List                 []*app_store.ProductLine `protobuf:"bytes,4,rep,name=list,proto3" json:"list" form:"list"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ListProductLinesResponse) Reset()         { *m = ListProductLinesResponse{} }
func (m *ListProductLinesResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductLinesResponse) ProtoMessage()    {}
func (*ListProductLinesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1}
}
func (m *ListProductLinesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductLinesResponse.Unmarshal(m, b)
}
func (m *ListProductLinesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductLinesResponse.Marshal(b, m, deterministic)
}
func (m *ListProductLinesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductLinesResponse.Merge(m, src)
}
func (m *ListProductLinesResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductLinesResponse.Size(m)
}
func (m *ListProductLinesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductLinesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductLinesResponse proto.InternalMessageInfo

func (m *ListProductLinesResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListProductLinesResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListProductLinesResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListProductLinesResponse) GetList() []*app_store.ProductLine {
	if m != nil {
		return m.List
	}
	return nil
}

//
//ListProductLinesApi返回
type ListProductLinesResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *ListProductLinesResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListProductLinesResponseWrapper) Reset()         { *m = ListProductLinesResponseWrapper{} }
func (m *ListProductLinesResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ListProductLinesResponseWrapper) ProtoMessage()    {}
func (*ListProductLinesResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{2}
}
func (m *ListProductLinesResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductLinesResponseWrapper.Unmarshal(m, b)
}
func (m *ListProductLinesResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductLinesResponseWrapper.Marshal(b, m, deterministic)
}
func (m *ListProductLinesResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductLinesResponseWrapper.Merge(m, src)
}
func (m *ListProductLinesResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ListProductLinesResponseWrapper.Size(m)
}
func (m *ListProductLinesResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductLinesResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductLinesResponseWrapper proto.InternalMessageInfo

func (m *ListProductLinesResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListProductLinesResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *ListProductLinesResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListProductLinesResponseWrapper) GetData() *ListProductLinesResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListProductLinesRequest)(nil), "product_line.ListProductLinesRequest")
	proto.RegisterType((*ListProductLinesResponse)(nil), "product_line.ListProductLinesResponse")
	proto.RegisterType((*ListProductLinesResponseWrapper)(nil), "product_line.ListProductLinesResponseWrapper")
}

func init() { proto.RegisterFile("list.proto", fileDescriptor_af793ce248ee1bf0) }

var fileDescriptor_af793ce248ee1bf0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4f, 0x8b, 0x13, 0x31,
	0x14, 0x77, 0xba, 0xb3, 0x62, 0xd3, 0x05, 0x4b, 0xc0, 0x75, 0xe8, 0x65, 0x4a, 0x84, 0xa5, 0x1e,
	0x3a, 0x81, 0x15, 0x54, 0xf4, 0x56, 0xf0, 0xe4, 0x1e, 0x24, 0x82, 0x1e, 0x4b, 0x3a, 0x93, 0x1d,
	0x83, 0xe9, 0xbc, 0x98, 0xa4, 0xae, 0x0a, 0x7e, 0xd5, 0x0a, 0xfa, 0x0d, 0x0a, 0xde, 0x25, 0x6f,
	0x66, 0xdb, 0x11, 0x59, 0x70, 0x4f, 0x93, 0xfc, 0xfe, 0xbc, 0xfc, 0xde, 0x9b, 0x47, 0x88, 0xd1,
	0x3e, 0x14, 0xd6, 0x41, 0x00, 0x7a, 0x62, 0x1d, 0x54, 0x9b, 0x32, 0x2c, 0x8d, 0x6e, 0xd4, 0x64,
	0x5e, 0xeb, 0xf0, 0x61, 0xb3, 0x2a, 0x4a, 0x58, 0xf3, 0x1a, 0x6a, 0xe0, 0x28, 0x5a, 0x6d, 0x2e,
	0xf1, 0x86, 0x17, 0x3c, 0xb5, 0xe6, 0xc9, 0xbb, 0x1a, 0x0a, 0x25, 0xfd, 0x57, 0xb0, 0xbe, 0x30,
	0x50, 0x4a, 0xc3, 0x4b, 0x68, 0x82, 0x93, 0x65, 0xf0, 0xad, 0xd3, 0x29, 0x0b, 0xf3, 0x35, 0x54,
	0xca, 0x78, 0xde, 0x09, 0x39, 0x5e, 0xb9, 0xb4, 0x76, 0xe9, 0xa3, 0x80, 0xf7, 0x03, 0x74, 0x75,
	0x9f, 0xf6, 0x62, 0xac, 0xaf, 0x74, 0xf8, 0x08, 0x57, 0xbc, 0x86, 0x39, 0x92, 0xf3, 0xcf, 0xd2,
	0xe8, 0x4a, 0x06, 0x70, 0x9e, 0xef, 0x8f, 0xad, 0x8f, 0x7d, 0x27, 0x0f, 0x2f, 0xb4, 0x0f, 0x6f,
	0xda, 0x8a, 0x17, 0xba, 0x51, 0x5e, 0xa8, 0x4f, 0x1b, 0xe5, 0x03, 0x7d, 0x4c, 0x52, 0x2b, 0x6b,
	0x95, 0x25, 0xd3, 0x64, 0x76, 0xbc, 0x78, 0xb0, 0xdb, 0xe6, 0xa3, 0x4b, 0x70, 0xeb, 0x17, 0x2c,
	0xa2, 0xec, 0xe7, 0x8f, 0x7c, 0x30, 0xbe, 0x23, 0x50, 0x42, 0x9f, 0x91, 0x61, 0xfc, 0x2e, 0xbd,
	0xfe, 0xa6, 0xb2, 0x01, 0xea, 0x27, 0xbb, 0x6d, 0x3e, 0x3e, 0xe8, 0x91, 0xba, 0x36, 0xdd, 0x8b,
	0xc8, 0xdb, 0x08, 0xfc, 0x4a, 0x48, 0xf6, 0xef, 0xfb, 0xde, 0x42, 0xe3, 0x15, 0x3d, 0x23, 0xc7,
	0x01, 0x82, 0x34, 0x5d, 0x82, 0xf1, 0x6e, 0x9b, 0x9f, 0xb4, 0x15, 0x11, 0x66, 0xa2, 0xa5, 0xf7,
	0x41, 0x07, 0xb7, 0x0c, 0x7a, 0xf4, 0xff, 0x41, 0xe9, 0x4b, 0x92, 0xc6, 0x15, 0xc8, 0xd2, 0xe9,
	0xd1, 0x6c, 0x74, 0x7e, 0x5a, 0xec, 0x7f, 0x46, 0xd1, 0x8b, 0xbe, 0xb8, 0x7f, 0x78, 0x3b, 0xaa,
	0x99, 0x40, 0x13, 0xfb, 0x9d, 0x90, 0xfc, 0xa6, 0x2e, 0xdf, 0x3b, 0x69, 0xad, 0x72, 0xf4, 0x11,
	0x49, 0x4b, 0xa8, 0xae, 0xa7, 0xdd, 0x2b, 0x14, 0x51, 0x26, 0x90, 0xa4, 0xcf, 0xc9, 0x28, 0x7e,
	0x5f, 0x7d, 0xb1, 0x46, 0xea, 0x06, 0x1b, 0x1e, 0x2e, 0x4e, 0x77, 0xdb, 0x9c, 0x1e, 0xb4, 0x1d,
	0xc9, 0x44, 0x5f, 0x1a, 0x67, 0xa9, 0x9c, 0x03, 0x87, 0x4d, 0x0f, 0xfb, 0xb3, 0x44, 0x98, 0x89,
	0x96, 0xa6, 0xaf, 0x49, 0x5a, 0xc9, 0x20, 0xb3, 0x74, 0x9a, 0xcc, 0x46, 0xe7, 0x67, 0xc5, 0x5f,
	0xab, 0x76, 0x53, 0x0f, 0xfd, 0xb8, 0xd1, 0xcd, 0x04, 0x16, 0x59, 0xdd, 0xc5, 0x1d, 0x7b, 0xf2,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x34, 0xed, 0xad, 0xfc, 0x3e, 0x03, 0x00, 0x00,
}
