// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: update_collection_config.proto

package collection_config

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//UpdateCollectionConfig请求
type UpdateCollectionConfigRequest struct {
	//
	//ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	//
	//名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	//
	//参数
	Kwargs []*UpdateCollectionConfigRequest_Kwargs `protobuf:"bytes,3,rep,name=kwargs,proto3" json:"kwargs" form:"kwargs"`
	//
	//超时时间
	Timeout int32 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout" form:"timeout"`
	//
	//环境变量
	Env []*UpdateCollectionConfigRequest_Env `protobuf:"bytes,5,rep,name=env,proto3" json:"env" form:"env"`
	//
	//是否禁用
	Disabled bool `protobuf:"varint,6,opt,name=disabled,proto3" json:"disabled" form:"disabled"`
	//
	//标签
	Labels []string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels" form:"labels"`
	//
	//脚本
	Script *UpdateCollectionConfigRequest_Script `protobuf:"bytes,8,opt,name=script,proto3" json:"script" form:"script"`
	//
	//是否忽略不符合要求数据
	IgnoreInvalid bool `protobuf:"varint,9,opt,name=ignoreInvalid,proto3" json:"ignoreInvalid" form:"ignoreInvalid"`
	//
	//主机范围
	HostRange *UpdateCollectionConfigRequest_HostRange `protobuf:"bytes,10,opt,name=hostRange,proto3" json:"hostRange" form:"hostRange"`
	//
	//采集间隔
	Interval int32 `protobuf:"varint,11,opt,name=interval,proto3" json:"interval" form:"interval"`
	//
	//缓存过期次数（时间）
	CacheTtl int32 `protobuf:"varint,12,opt,name=cacheTtl,proto3" json:"cacheTtl" form:"cacheTtl"`
	//
	//执行时间范围（24小时）
	TimeRange string `protobuf:"bytes,13,opt,name=timeRange,proto3" json:"timeRange" form:"timeRange"`
	//
	//采集类型ID
	ClazzId string `protobuf:"bytes,14,opt,name=clazzId,proto3" json:"clazzId" form:"clazzId"`
	//
	//关联模型ID
	ObjectId string `protobuf:"bytes,15,opt,name=objectId,proto3" json:"objectId" form:"objectId"`
	//
	//关联模型实例ID宏
	InstanceIdMacro      string   `protobuf:"bytes,16,opt,name=instanceIdMacro,proto3" json:"instanceIdMacro" form:"instanceIdMacro"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCollectionConfigRequest) Reset()         { *m = UpdateCollectionConfigRequest{} }
func (m *UpdateCollectionConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigRequest) ProtoMessage()    {}
func (*UpdateCollectionConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{0}
}
func (m *UpdateCollectionConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigRequest.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigRequest.Merge(m, src)
}
func (m *UpdateCollectionConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigRequest.Size(m)
}
func (m *UpdateCollectionConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigRequest proto.InternalMessageInfo

func (m *UpdateCollectionConfigRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCollectionConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCollectionConfigRequest) GetKwargs() []*UpdateCollectionConfigRequest_Kwargs {
	if m != nil {
		return m.Kwargs
	}
	return nil
}

func (m *UpdateCollectionConfigRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *UpdateCollectionConfigRequest) GetEnv() []*UpdateCollectionConfigRequest_Env {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *UpdateCollectionConfigRequest) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *UpdateCollectionConfigRequest) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *UpdateCollectionConfigRequest) GetScript() *UpdateCollectionConfigRequest_Script {
	if m != nil {
		return m.Script
	}
	return nil
}

func (m *UpdateCollectionConfigRequest) GetIgnoreInvalid() bool {
	if m != nil {
		return m.IgnoreInvalid
	}
	return false
}

func (m *UpdateCollectionConfigRequest) GetHostRange() *UpdateCollectionConfigRequest_HostRange {
	if m != nil {
		return m.HostRange
	}
	return nil
}

func (m *UpdateCollectionConfigRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *UpdateCollectionConfigRequest) GetCacheTtl() int32 {
	if m != nil {
		return m.CacheTtl
	}
	return 0
}

func (m *UpdateCollectionConfigRequest) GetTimeRange() string {
	if m != nil {
		return m.TimeRange
	}
	return ""
}

func (m *UpdateCollectionConfigRequest) GetClazzId() string {
	if m != nil {
		return m.ClazzId
	}
	return ""
}

func (m *UpdateCollectionConfigRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *UpdateCollectionConfigRequest) GetInstanceIdMacro() string {
	if m != nil {
		return m.InstanceIdMacro
	}
	return ""
}

type UpdateCollectionConfigRequest_Kwargs struct {
	//
	//键
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key" form:"key"`
	//
	//值
	Value                *types.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value" form:"value"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCollectionConfigRequest_Kwargs) Reset()         { *m = UpdateCollectionConfigRequest_Kwargs{} }
func (m *UpdateCollectionConfigRequest_Kwargs) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigRequest_Kwargs) ProtoMessage()    {}
func (*UpdateCollectionConfigRequest_Kwargs) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{0, 0}
}
func (m *UpdateCollectionConfigRequest_Kwargs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Kwargs.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigRequest_Kwargs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Kwargs.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigRequest_Kwargs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigRequest_Kwargs.Merge(m, src)
}
func (m *UpdateCollectionConfigRequest_Kwargs) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Kwargs.Size(m)
}
func (m *UpdateCollectionConfigRequest_Kwargs) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigRequest_Kwargs.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigRequest_Kwargs proto.InternalMessageInfo

func (m *UpdateCollectionConfigRequest_Kwargs) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_Kwargs) GetValue() *types.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type UpdateCollectionConfigRequest_Env struct {
	//
	//键
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key" form:"key"`
	//
	//值
	Value                *types.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value" form:"value"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCollectionConfigRequest_Env) Reset()         { *m = UpdateCollectionConfigRequest_Env{} }
func (m *UpdateCollectionConfigRequest_Env) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigRequest_Env) ProtoMessage()    {}
func (*UpdateCollectionConfigRequest_Env) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{0, 1}
}
func (m *UpdateCollectionConfigRequest_Env) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Env.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigRequest_Env) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Env.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigRequest_Env) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigRequest_Env.Merge(m, src)
}
func (m *UpdateCollectionConfigRequest_Env) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Env.Size(m)
}
func (m *UpdateCollectionConfigRequest_Env) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigRequest_Env.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigRequest_Env proto.InternalMessageInfo

func (m *UpdateCollectionConfigRequest_Env) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_Env) GetValue() *types.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type UpdateCollectionConfigRequest_Script struct {
	//
	//脚本Id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	//
	//脚本版本
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version" form:"version"`
	//
	//脚本类型
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type" form:"type"`
	//
	//脚本内容
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content" form:"content"`
	//
	//脚本名称
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name" form:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCollectionConfigRequest_Script) Reset()         { *m = UpdateCollectionConfigRequest_Script{} }
func (m *UpdateCollectionConfigRequest_Script) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigRequest_Script) ProtoMessage()    {}
func (*UpdateCollectionConfigRequest_Script) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{0, 2}
}
func (m *UpdateCollectionConfigRequest_Script) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Script.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigRequest_Script) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Script.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigRequest_Script) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigRequest_Script.Merge(m, src)
}
func (m *UpdateCollectionConfigRequest_Script) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigRequest_Script.Size(m)
}
func (m *UpdateCollectionConfigRequest_Script) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigRequest_Script.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigRequest_Script proto.InternalMessageInfo

func (m *UpdateCollectionConfigRequest_Script) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_Script) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_Script) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_Script) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_Script) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateCollectionConfigRequest_HostRange struct {
	//
	//模型ID
	ObjectId string `protobuf:"bytes,1,opt,name=objectId,proto3" json:"objectId" form:"objectId"`
	//
	//获取主机Key路径
	HostKey string `protobuf:"bytes,2,opt,name=hostKey,proto3" json:"hostKey" form:"hostKey"`
	//
	//查询者
	Querier string `protobuf:"bytes,3,opt,name=querier,proto3" json:"querier" form:"querier"`
	//
	//查询类型
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type" form:"type"`
	//
	//查询策略字符串
	QueryString string `protobuf:"bytes,5,opt,name=queryString,proto3" json:"queryString" form:"queryString"`
	//
	//查询策略ID
	QueryId string `protobuf:"bytes,6,opt,name=queryId,proto3" json:"queryId" form:"queryId"`
	//
	//查询策略ID
	Query                []*UpdateCollectionConfigRequest_HostRange_Query `protobuf:"bytes,7,rep,name=query,proto3" json:"query" form:"query"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *UpdateCollectionConfigRequest_HostRange) Reset() {
	*m = UpdateCollectionConfigRequest_HostRange{}
}
func (m *UpdateCollectionConfigRequest_HostRange) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigRequest_HostRange) ProtoMessage()    {}
func (*UpdateCollectionConfigRequest_HostRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{0, 3}
}
func (m *UpdateCollectionConfigRequest_HostRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigRequest_HostRange.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigRequest_HostRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigRequest_HostRange.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigRequest_HostRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigRequest_HostRange.Merge(m, src)
}
func (m *UpdateCollectionConfigRequest_HostRange) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigRequest_HostRange.Size(m)
}
func (m *UpdateCollectionConfigRequest_HostRange) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigRequest_HostRange.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigRequest_HostRange proto.InternalMessageInfo

func (m *UpdateCollectionConfigRequest_HostRange) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange) GetHostKey() string {
	if m != nil {
		return m.HostKey
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange) GetQuerier() string {
	if m != nil {
		return m.Querier
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange) GetQueryString() string {
	if m != nil {
		return m.QueryString
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange) GetQueryId() string {
	if m != nil {
		return m.QueryId
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange) GetQuery() []*UpdateCollectionConfigRequest_HostRange_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type UpdateCollectionConfigRequest_HostRange_Query struct {
	//
	//键
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key" form:"key"`
	//
	//操作符
	Op string `protobuf:"bytes,2,opt,name=op,proto3" json:"op" form:"op"`
	//
	//值
	Value                *types.Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value" form:"value"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateCollectionConfigRequest_HostRange_Query) Reset() {
	*m = UpdateCollectionConfigRequest_HostRange_Query{}
}
func (m *UpdateCollectionConfigRequest_HostRange_Query) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateCollectionConfigRequest_HostRange_Query) ProtoMessage() {}
func (*UpdateCollectionConfigRequest_HostRange_Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{0, 3, 0}
}
func (m *UpdateCollectionConfigRequest_HostRange_Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigRequest_HostRange_Query.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigRequest_HostRange_Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigRequest_HostRange_Query.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigRequest_HostRange_Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigRequest_HostRange_Query.Merge(m, src)
}
func (m *UpdateCollectionConfigRequest_HostRange_Query) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigRequest_HostRange_Query.Size(m)
}
func (m *UpdateCollectionConfigRequest_HostRange_Query) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigRequest_HostRange_Query.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigRequest_HostRange_Query proto.InternalMessageInfo

func (m *UpdateCollectionConfigRequest_HostRange_Query) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange_Query) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *UpdateCollectionConfigRequest_HostRange_Query) GetValue() *types.Value {
	if m != nil {
		return m.Value
	}
	return nil
}

//
//UpdateCollectionConfig返回
type UpdateCollectionConfigResponse struct {
	//
	//ID
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCollectionConfigResponse) Reset()         { *m = UpdateCollectionConfigResponse{} }
func (m *UpdateCollectionConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigResponse) ProtoMessage()    {}
func (*UpdateCollectionConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{1}
}
func (m *UpdateCollectionConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigResponse.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigResponse.Merge(m, src)
}
func (m *UpdateCollectionConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigResponse.Size(m)
}
func (m *UpdateCollectionConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigResponse proto.InternalMessageInfo

func (m *UpdateCollectionConfigResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//
//UpdateCollectionConfigApi返回
type UpdateCollectionConfigResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *UpdateCollectionConfigResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateCollectionConfigResponseWrapper) Reset()         { *m = UpdateCollectionConfigResponseWrapper{} }
func (m *UpdateCollectionConfigResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*UpdateCollectionConfigResponseWrapper) ProtoMessage()    {}
func (*UpdateCollectionConfigResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3e7537d22ef04d1, []int{2}
}
func (m *UpdateCollectionConfigResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCollectionConfigResponseWrapper.Unmarshal(m, b)
}
func (m *UpdateCollectionConfigResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCollectionConfigResponseWrapper.Marshal(b, m, deterministic)
}
func (m *UpdateCollectionConfigResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCollectionConfigResponseWrapper.Merge(m, src)
}
func (m *UpdateCollectionConfigResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_UpdateCollectionConfigResponseWrapper.Size(m)
}
func (m *UpdateCollectionConfigResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCollectionConfigResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCollectionConfigResponseWrapper proto.InternalMessageInfo

func (m *UpdateCollectionConfigResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateCollectionConfigResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *UpdateCollectionConfigResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *UpdateCollectionConfigResponseWrapper) GetData() *UpdateCollectionConfigResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateCollectionConfigRequest)(nil), "collection_config.UpdateCollectionConfigRequest")
	proto.RegisterType((*UpdateCollectionConfigRequest_Kwargs)(nil), "collection_config.UpdateCollectionConfigRequest.Kwargs")
	proto.RegisterType((*UpdateCollectionConfigRequest_Env)(nil), "collection_config.UpdateCollectionConfigRequest.Env")
	proto.RegisterType((*UpdateCollectionConfigRequest_Script)(nil), "collection_config.UpdateCollectionConfigRequest.Script")
	proto.RegisterType((*UpdateCollectionConfigRequest_HostRange)(nil), "collection_config.UpdateCollectionConfigRequest.HostRange")
	proto.RegisterType((*UpdateCollectionConfigRequest_HostRange_Query)(nil), "collection_config.UpdateCollectionConfigRequest.HostRange.Query")
	proto.RegisterType((*UpdateCollectionConfigResponse)(nil), "collection_config.UpdateCollectionConfigResponse")
	proto.RegisterType((*UpdateCollectionConfigResponseWrapper)(nil), "collection_config.UpdateCollectionConfigResponseWrapper")
}

func init() { proto.RegisterFile("update_collection_config.proto", fileDescriptor_d3e7537d22ef04d1) }

var fileDescriptor_d3e7537d22ef04d1 = []byte{
	// 1009 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x18, 0xad, 0xff, 0x63, 0xba, 0x49, 0x5c, 0xae, 0x0b, 0x34, 0x63, 0xa9, 0x0c, 0x76, 0x1d, 0x5c,
	0x20, 0xb6, 0x37, 0xaf, 0xfb, 0x0b, 0xb0, 0x60, 0x70, 0x17, 0x60, 0x46, 0xb1, 0x8b, 0xb2, 0x5b,
	0x76, 0x51, 0x14, 0x85, 0x2c, 0x31, 0x8a, 0x1a, 0x59, 0x54, 0x25, 0xda, 0x99, 0x5b, 0xf4, 0x76,
	0xd8, 0xfd, 0xee, 0xf6, 0x4e, 0x7b, 0x05, 0x0d, 0xd8, 0x23, 0xe8, 0x09, 0x06, 0x7e, 0x94, 0x64,
	0xba, 0xde, 0x82, 0x26, 0x17, 0xbb, 0x8a, 0xcc, 0x73, 0xbe, 0xc3, 0xef, 0x8f, 0x07, 0x41, 0x77,
	0xe6, 0xa1, 0x63, 0x09, 0xf6, 0xdc, 0xe6, 0xbe, 0xcf, 0x6c, 0xe1, 0xf1, 0xe0, 0xb9, 0xcd, 0x83,
	0x53, 0xcf, 0x1d, 0x84, 0x11, 0x17, 0x1c, 0xdf, 0xda, 0x00, 0x3a, 0x7d, 0xd7, 0x13, 0x67, 0xf3,
	0xe9, 0xc0, 0xe6, 0xb3, 0xa1, 0xcb, 0x5d, 0x3e, 0x04, 0xe6, 0x74, 0x7e, 0x0a, 0xbf, 0xe0, 0x07,
	0x7c, 0x29, 0x85, 0xce, 0x17, 0x1a, 0x7d, 0x76, 0xe1, 0x89, 0x73, 0x7e, 0x31, 0x74, 0x79, 0x1f,
	0xc0, 0xfe, 0xc2, 0xf2, 0x3d, 0xc7, 0x12, 0x3c, 0x8a, 0x87, 0xc5, 0x67, 0x16, 0xf7, 0xa1, 0xcb,
	0xb9, 0xeb, 0xb3, 0x95, 0x7a, 0x2c, 0xa2, 0xb9, 0x2d, 0x14, 0x4a, 0x7e, 0x6f, 0xa3, 0xfd, 0x9f,
	0x20, 0xf5, 0x87, 0x45, 0x82, 0x0f, 0x21, 0x3f, 0xca, 0x5e, 0xce, 0x59, 0x2c, 0xf0, 0x10, 0x95,
	0x3d, 0xc7, 0x28, 0x75, 0x4b, 0xbd, 0xe6, 0xd8, 0x4c, 0x13, 0xb3, 0x79, 0xca, 0xa3, 0xd9, 0x21,
	0xf1, 0x1c, 0xf2, 0xf7, 0x5f, 0xe6, 0x0e, 0xba, 0xf9, 0xf4, 0x93, 0xfe, 0xd7, 0x56, 0xff, 0xf4,
	0xd9, 0xeb, 0xd1, 0x83, 0x37, 0xb4, 0xec, 0x39, 0xf8, 0x3e, 0xaa, 0x06, 0xd6, 0x8c, 0x19, 0x65,
	0x08, 0x79, 0x3f, 0x4d, 0xcc, 0x96, 0x0a, 0x91, 0xa7, 0x32, 0xa8, 0x1c, 0xde, 0xa0, 0x40, 0xc1,
	0x53, 0x54, 0x3f, 0xbf, 0xb0, 0x22, 0x37, 0x36, 0x2a, 0xdd, 0x4a, 0xaf, 0x35, 0xfa, 0x72, 0xb0,
	0xd9, 0xbf, 0x4b, 0xb3, 0x1b, 0x3c, 0x82, 0xf0, 0xf1, 0xad, 0x34, 0x31, 0xb7, 0xd5, 0x2d, 0x4a,
	0x90, 0xd0, 0x4c, 0x19, 0x1f, 0xa0, 0x86, 0xf0, 0x66, 0x8c, 0xcf, 0x85, 0x51, 0xed, 0x96, 0x7a,
	0xb5, 0x31, 0x4e, 0x13, 0x73, 0x47, 0x71, 0x33, 0x80, 0xd0, 0x9c, 0x82, 0x4f, 0x50, 0x85, 0x05,
	0x0b, 0xa3, 0x06, 0xe9, 0x3c, 0xb8, 0x72, 0x3a, 0xc7, 0xc1, 0x62, 0xbc, 0x93, 0x26, 0x26, 0x52,
	0xfa, 0x2c, 0x58, 0x10, 0x2a, 0x05, 0xf1, 0x10, 0x6d, 0x39, 0x5e, 0x6c, 0x4d, 0x7d, 0xe6, 0x18,
	0xf5, 0x6e, 0xa9, 0xb7, 0x35, 0x7e, 0x2f, 0x4d, 0xcc, 0x5d, 0x45, 0xcb, 0x11, 0x42, 0x0b, 0x12,
	0xbe, 0x8f, 0xea, 0xbe, 0x35, 0x65, 0x7e, 0x6c, 0x34, 0xba, 0x95, 0x5e, 0x53, 0xaf, 0x50, 0x9d,
	0x13, 0x9a, 0x11, 0x64, 0x17, 0x63, 0x3b, 0xf2, 0x42, 0x61, 0x6c, 0x75, 0x4b, 0xd7, 0xea, 0xe2,
	0x13, 0x08, 0xd7, 0xef, 0x50, 0x82, 0x84, 0x66, 0xca, 0xf8, 0x08, 0x6d, 0x7b, 0x6e, 0xc0, 0x23,
	0x36, 0x09, 0x60, 0xc1, 0x8c, 0x26, 0x14, 0x61, 0xa4, 0x89, 0x79, 0x3b, 0x5b, 0x08, 0x1d, 0x26,
	0x74, 0x9d, 0x8e, 0x03, 0xd4, 0x3c, 0xe3, 0xb1, 0xa0, 0x56, 0xe0, 0x32, 0x03, 0x41, 0x9a, 0x87,
	0x57, 0x4e, 0xf3, 0xfb, 0x5c, 0x61, 0x7c, 0x3b, 0x4d, 0xcc, 0xb6, 0xba, 0xb7, 0x90, 0x25, 0x74,
	0x75, 0x05, 0xfe, 0x1c, 0x6d, 0x79, 0x81, 0x60, 0xd1, 0xc2, 0xf2, 0x8d, 0x16, 0x8c, 0xfd, 0x83,
	0x55, 0xbf, 0x73, 0x04, 0x96, 0xb1, 0x7d, 0x83, 0x16, 0x54, 0x39, 0x26, 0xdb, 0xb2, 0xcf, 0xd8,
	0x8f, 0xc2, 0x37, 0x6e, 0x42, 0x98, 0x36, 0xa6, 0x1c, 0x21, 0xb4, 0x20, 0xe1, 0xa7, 0xa8, 0x29,
	0x57, 0x47, 0xd5, 0xb5, 0x0d, 0x1b, 0xff, 0xcd, 0x2a, 0xb7, 0x02, 0x92, 0x37, 0xdd, 0x43, 0x77,
	0xe5, 0x5b, 0x79, 0xf6, 0x7a, 0xf4, 0xe6, 0x30, 0xff, 0xe8, 0x6f, 0x9c, 0xd0, 0x95, 0x1e, 0x3e,
	0x42, 0x0d, 0xdb, 0xb7, 0x5e, 0xbd, 0x9a, 0x38, 0xc6, 0x0e, 0x48, 0x7f, 0xb4, 0x5a, 0xdd, 0x0c,
	0xf8, 0xb7, 0x47, 0x98, 0x07, 0xc9, 0x6a, 0xf8, 0xf4, 0x05, 0xb3, 0xc5, 0xc4, 0x31, 0x76, 0x41,
	0x40, 0xab, 0x26, 0x47, 0x08, 0x2d, 0x48, 0xf8, 0x3b, 0xb4, 0xeb, 0x05, 0xb1, 0xb0, 0x02, 0x9b,
	0x4d, 0x9c, 0x1f, 0x2c, 0x3b, 0xe2, 0x46, 0x1b, 0xe2, 0x3a, 0x69, 0x62, 0xee, 0xe5, 0xcd, 0x5b,
	0x23, 0x10, 0xfa, 0x76, 0x48, 0xe7, 0x05, 0xaa, 0xab, 0x67, 0x89, 0xbb, 0xa8, 0x72, 0xce, 0x96,
	0x99, 0x79, 0x68, 0xef, 0xe2, 0x9c, 0x2d, 0x09, 0x95, 0x10, 0x3e, 0x42, 0xb5, 0x85, 0xe5, 0xcf,
	0x95, 0x5b, 0xb4, 0x46, 0x7b, 0x03, 0xe5, 0x56, 0x83, 0xdc, 0xad, 0x06, 0x27, 0x12, 0x1d, 0xb7,
	0xd3, 0xc4, 0xbc, 0xa9, 0x62, 0x81, 0x4e, 0xa8, 0x0a, 0xeb, 0xb8, 0xa8, 0x72, 0x1c, 0x2c, 0xfe,
	0x87, 0x8b, 0xfe, 0x2c, 0xa1, 0xba, 0x7a, 0x26, 0x78, 0x5f, 0x73, 0xc4, 0xed, 0x35, 0x47, 0x04,
	0xff, 0x3b, 0x40, 0x8d, 0x05, 0x8b, 0x62, 0x8f, 0x07, 0x99, 0x05, 0x6a, 0x86, 0x93, 0x01, 0x84,
	0xe6, 0x14, 0x7c, 0x17, 0x55, 0xc5, 0x32, 0x64, 0x46, 0x05, 0xa8, 0xbb, 0x2b, 0xb7, 0x94, 0xa7,
	0x84, 0x02, 0x28, 0x25, 0x6d, 0x1e, 0x08, 0x16, 0x28, 0x0f, 0x5b, 0x93, 0xcc, 0x00, 0x42, 0x73,
	0x8a, 0x94, 0x04, 0x03, 0xae, 0xbd, 0x2d, 0x09, 0x06, 0xac, 0xac, 0xb7, 0xf3, 0x47, 0x15, 0x35,
	0x8b, 0xf7, 0xb4, 0xb6, 0x29, 0xa5, 0x77, 0xd9, 0x94, 0x03, 0xd4, 0x90, 0x8f, 0xed, 0x11, 0x5b,
	0x6e, 0x16, 0x99, 0x01, 0x84, 0xe6, 0x14, 0xc9, 0x7e, 0x39, 0x67, 0x91, 0xc7, 0xa2, 0xac, 0x4e,
	0x8d, 0x9d, 0x01, 0x84, 0xe6, 0x94, 0xa2, 0x25, 0xd5, 0xcb, 0x5a, 0xf2, 0x15, 0x6a, 0x49, 0xfe,
	0xf2, 0x89, 0x88, 0xbc, 0xc0, 0xcd, 0x6a, 0xdd, 0x4b, 0x13, 0x13, 0xaf, 0x64, 0x33, 0x90, 0x50,
	0x9d, 0x9a, 0x27, 0xb3, 0x9c, 0x28, 0x27, 0xde, 0x48, 0x66, 0x29, 0x2b, 0xcd, 0x29, 0xf8, 0x0c,
	0xd5, 0xe0, 0x13, 0x6c, 0xb8, 0x35, 0xfa, 0xf6, 0xfa, 0xa6, 0x35, 0x78, 0x2c, 0x75, 0xf4, 0x0d,
	0x03, 0x61, 0x42, 0xd5, 0x05, 0x9d, 0xdf, 0x4a, 0xa8, 0x06, 0x94, 0x77, 0xd8, 0xe6, 0x7d, 0x54,
	0xe6, 0x61, 0xd6, 0x79, 0x6d, 0x05, 0x79, 0x48, 0x68, 0x99, 0x87, 0xab, 0x65, 0xaf, 0x5c, 0x6b,
	0xd9, 0xc9, 0x63, 0x74, 0xe7, 0xbf, 0x8a, 0x8a, 0x43, 0x1e, 0xc4, 0xec, 0xca, 0xff, 0x15, 0x90,
	0x5f, 0xcb, 0xe8, 0xde, 0xe5, 0x9a, 0x3f, 0x47, 0x56, 0x18, 0xaa, 0xf1, 0xdb, 0xdc, 0x61, 0x20,
	0x5e, 0xd3, 0xc7, 0x2f, 0x4f, 0x09, 0x05, 0x50, 0x8e, 0x5f, 0xfe, 0x3d, 0xfe, 0x25, 0xf4, 0x2d,
	0x2f, 0x7f, 0x68, 0xda, 0xf8, 0x35, 0x90, 0x50, 0x9d, 0x8a, 0x3f, 0x46, 0x35, 0x16, 0x45, 0x3c,
	0xdf, 0x44, 0xad, 0x07, 0x70, 0x4c, 0xa8, 0x82, 0xf1, 0x09, 0xaa, 0x3a, 0x96, 0xb0, 0x60, 0x0b,
	0x5b, 0xa3, 0x4f, 0xaf, 0x30, 0x77, 0x55, 0x8e, 0x9e, 0xb9, 0x14, 0x22, 0x14, 0xf4, 0xa6, 0x75,
	0x18, 0xc2, 0x67, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x17, 0xf2, 0xe7, 0x32, 0x0a, 0x00,
	0x00,
}
