// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giraffe_service.proto

package jobs

import (
	context "context"
	fmt "fmt"
	giraffe_micro "github.com/easyops-cn/giraffe-micro"
	go_proto_giraffe "github.com/easyops-cn/go-proto-giraffe"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ = io.EOF
var _ context.Context
var _ giraffe_micro.Client
var _ go_proto_giraffe.Contract

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = giraffe_micro.SupportPackageIsVersion4 // please upgrade the giraffe_micro package

// Client is the client API for jobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Client interface {
	GetChangedJobs(ctx context.Context, in *GetChangedJobsRequest) (*GetChangedJobsResponse, error)
}

type client struct {
	c giraffe_micro.Client
}

func NewClient(c giraffe_micro.Client) Client {
	return &client{
		c: c,
	}
}

func (c *client) GetChangedJobs(ctx context.Context, in *GetChangedJobsRequest) (*GetChangedJobsResponse, error) {
	out := new(GetChangedJobsResponse)
	err := c.c.Invoke(ctx, _GetChangedJobsMethodDesc, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Service is the server API for jobs service.
type Service interface {
	GetChangedJobs(context.Context, *GetChangedJobsRequest) (*GetChangedJobsResponse, error)
}

func _GetChangedJobsEndpoint(s Service) giraffe_micro.UnaryEndpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetChangedJobs(ctx, req.(*GetChangedJobsRequest))
	}
}

func RegisterService(s giraffe_micro.Server, srv Service) {
	s.RegisterUnaryEndpoint(_GetChangedJobsMethodDesc, _GetChangedJobsEndpoint(srv))
}

// Method Description
var _GetChangedJobsMethodDesc = &giraffe_micro.MethodDesc{
	Contract: &go_proto_giraffe.Contract{
		Name:    "easyops.api.collector_service.jobs.GetChangedJobs",
		Version: "1.0",
	},
	ServiceName:  "jobs.rpc",
	MethodName:   "GetChangedJobs",
	RequestType:  (*GetChangedJobsRequest)(nil),
	ResponseType: (*GetChangedJobsResponse)(nil),
	HttpRule: &go_proto_giraffe.HttpRule{
		Pattern: &go_proto_giraffe.HttpRule_Get{
			Get: "/api/v1/changed-jobs",
		},
		Body:         "",
		ResponseBody: "data",
	},
}
