// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: list.proto

package version

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//ListAppVersion请求
type ListAppVersionRequest struct {
	//
	//页码
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page" form:"page"`
	//
	//每页大小
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//小产品id
	AppId string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id" form:"app_id"`
	//
	//条件查询：按照字段正/倒序 :1表示升序, -1表示降序
	Sort                 *ListAppVersionRequest_Sort `protobuf:"bytes,4,opt,name=sort,proto3" json:"sort" form:"sort"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListAppVersionRequest) Reset()         { *m = ListAppVersionRequest{} }
func (m *ListAppVersionRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppVersionRequest) ProtoMessage()    {}
func (*ListAppVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{0}
}
func (m *ListAppVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppVersionRequest.Unmarshal(m, b)
}
func (m *ListAppVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppVersionRequest.Marshal(b, m, deterministic)
}
func (m *ListAppVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppVersionRequest.Merge(m, src)
}
func (m *ListAppVersionRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppVersionRequest.Size(m)
}
func (m *ListAppVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppVersionRequest proto.InternalMessageInfo

func (m *ListAppVersionRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAppVersionRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAppVersionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ListAppVersionRequest) GetSort() *ListAppVersionRequest_Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type ListAppVersionRequest_Sort struct {
	//
	//按ctime排序，1为升序，-1为降序
	Ctime int32 `protobuf:"varint,1,opt,name=ctime,proto3" json:"ctime" form:"ctime"`
	//
	//按releaseTime排序，1为升序，-1为降序
	ReleaseTime          int32    `protobuf:"varint,2,opt,name=releaseTime,proto3" json:"releaseTime" form:"releaseTime"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppVersionRequest_Sort) Reset()         { *m = ListAppVersionRequest_Sort{} }
func (m *ListAppVersionRequest_Sort) String() string { return proto.CompactTextString(m) }
func (*ListAppVersionRequest_Sort) ProtoMessage()    {}
func (*ListAppVersionRequest_Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{0, 0}
}
func (m *ListAppVersionRequest_Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppVersionRequest_Sort.Unmarshal(m, b)
}
func (m *ListAppVersionRequest_Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppVersionRequest_Sort.Marshal(b, m, deterministic)
}
func (m *ListAppVersionRequest_Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppVersionRequest_Sort.Merge(m, src)
}
func (m *ListAppVersionRequest_Sort) XXX_Size() int {
	return xxx_messageInfo_ListAppVersionRequest_Sort.Size(m)
}
func (m *ListAppVersionRequest_Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppVersionRequest_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppVersionRequest_Sort proto.InternalMessageInfo

func (m *ListAppVersionRequest_Sort) GetCtime() int32 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *ListAppVersionRequest_Sort) GetReleaseTime() int32 {
	if m != nil {
		return m.ReleaseTime
	}
	return 0
}

//
//ListAppVersion返回
type ListAppVersionResponse struct {
	//
	//返回总数
	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total" form:"total"`
	//
	//页数
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" form:"page"`
	//
	//该页大小
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//数据列表
	List                 []*ListAppVersionResponse_List `protobuf:"bytes,4,rep,name=list,proto3" json:"list" form:"list"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ListAppVersionResponse) Reset()         { *m = ListAppVersionResponse{} }
func (m *ListAppVersionResponse) String() string { return proto.CompactTextString(m) }
func (*ListAppVersionResponse) ProtoMessage()    {}
func (*ListAppVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1}
}
func (m *ListAppVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppVersionResponse.Unmarshal(m, b)
}
func (m *ListAppVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppVersionResponse.Marshal(b, m, deterministic)
}
func (m *ListAppVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppVersionResponse.Merge(m, src)
}
func (m *ListAppVersionResponse) XXX_Size() int {
	return xxx_messageInfo_ListAppVersionResponse.Size(m)
}
func (m *ListAppVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppVersionResponse proto.InternalMessageInfo

func (m *ListAppVersionResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListAppVersionResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAppVersionResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAppVersionResponse) GetList() []*ListAppVersionResponse_List {
	if m != nil {
		return m.List
	}
	return nil
}

type ListAppVersionResponse_List struct {
	//
	//版本实例id
	VersionId string `protobuf:"bytes,1,opt,name=versionId,proto3" json:"versionId" form:"versionId"`
	//
	//小产品名称+版本组合的唯一id
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	//
	//版本名称
	VersionName string `protobuf:"bytes,3,opt,name=versionName,proto3" json:"versionName" form:"versionName"`
	//
	//版本变更记录
	ChangeLog string `protobuf:"bytes,4,opt,name=changeLog,proto3" json:"changeLog" form:"changeLog"`
	//
	//版本发布时间
	ReleaseTime string `protobuf:"bytes,5,opt,name=releaseTime,proto3" json:"releaseTime" form:"releaseTime"`
	//
	//依赖包列表
	Dependencies         []*ListAppVersionResponse_List_Dependencies `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies" form:"dependencies"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *ListAppVersionResponse_List) Reset()         { *m = ListAppVersionResponse_List{} }
func (m *ListAppVersionResponse_List) String() string { return proto.CompactTextString(m) }
func (*ListAppVersionResponse_List) ProtoMessage()    {}
func (*ListAppVersionResponse_List) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1, 0}
}
func (m *ListAppVersionResponse_List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppVersionResponse_List.Unmarshal(m, b)
}
func (m *ListAppVersionResponse_List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppVersionResponse_List.Marshal(b, m, deterministic)
}
func (m *ListAppVersionResponse_List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppVersionResponse_List.Merge(m, src)
}
func (m *ListAppVersionResponse_List) XXX_Size() int {
	return xxx_messageInfo_ListAppVersionResponse_List.Size(m)
}
func (m *ListAppVersionResponse_List) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppVersionResponse_List.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppVersionResponse_List proto.InternalMessageInfo

func (m *ListAppVersionResponse_List) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

func (m *ListAppVersionResponse_List) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListAppVersionResponse_List) GetVersionName() string {
	if m != nil {
		return m.VersionName
	}
	return ""
}

func (m *ListAppVersionResponse_List) GetChangeLog() string {
	if m != nil {
		return m.ChangeLog
	}
	return ""
}

func (m *ListAppVersionResponse_List) GetReleaseTime() string {
	if m != nil {
		return m.ReleaseTime
	}
	return ""
}

func (m *ListAppVersionResponse_List) GetDependencies() []*ListAppVersionResponse_List_Dependencies {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type ListAppVersionResponse_List_Dependencies struct {
	//
	//依赖组件
	PackageName string `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName" form:"packageName"`
	//
	//依赖版本semver约束
	Constraint           string   `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint" form:"constraint"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppVersionResponse_List_Dependencies) Reset() {
	*m = ListAppVersionResponse_List_Dependencies{}
}
func (m *ListAppVersionResponse_List_Dependencies) String() string { return proto.CompactTextString(m) }
func (*ListAppVersionResponse_List_Dependencies) ProtoMessage()    {}
func (*ListAppVersionResponse_List_Dependencies) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1, 0, 0}
}
func (m *ListAppVersionResponse_List_Dependencies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppVersionResponse_List_Dependencies.Unmarshal(m, b)
}
func (m *ListAppVersionResponse_List_Dependencies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppVersionResponse_List_Dependencies.Marshal(b, m, deterministic)
}
func (m *ListAppVersionResponse_List_Dependencies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppVersionResponse_List_Dependencies.Merge(m, src)
}
func (m *ListAppVersionResponse_List_Dependencies) XXX_Size() int {
	return xxx_messageInfo_ListAppVersionResponse_List_Dependencies.Size(m)
}
func (m *ListAppVersionResponse_List_Dependencies) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppVersionResponse_List_Dependencies.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppVersionResponse_List_Dependencies proto.InternalMessageInfo

func (m *ListAppVersionResponse_List_Dependencies) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ListAppVersionResponse_List_Dependencies) GetConstraint() string {
	if m != nil {
		return m.Constraint
	}
	return ""
}

//
//ListAppVersionApi返回
type ListAppVersionResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *ListAppVersionResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListAppVersionResponseWrapper) Reset()         { *m = ListAppVersionResponseWrapper{} }
func (m *ListAppVersionResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ListAppVersionResponseWrapper) ProtoMessage()    {}
func (*ListAppVersionResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{2}
}
func (m *ListAppVersionResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppVersionResponseWrapper.Unmarshal(m, b)
}
func (m *ListAppVersionResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppVersionResponseWrapper.Marshal(b, m, deterministic)
}
func (m *ListAppVersionResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppVersionResponseWrapper.Merge(m, src)
}
func (m *ListAppVersionResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ListAppVersionResponseWrapper.Size(m)
}
func (m *ListAppVersionResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppVersionResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppVersionResponseWrapper proto.InternalMessageInfo

func (m *ListAppVersionResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListAppVersionResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *ListAppVersionResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListAppVersionResponseWrapper) GetData() *ListAppVersionResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListAppVersionRequest)(nil), "version.ListAppVersionRequest")
	proto.RegisterType((*ListAppVersionRequest_Sort)(nil), "version.ListAppVersionRequest.Sort")
	proto.RegisterType((*ListAppVersionResponse)(nil), "version.ListAppVersionResponse")
	proto.RegisterType((*ListAppVersionResponse_List)(nil), "version.ListAppVersionResponse.List")
	proto.RegisterType((*ListAppVersionResponse_List_Dependencies)(nil), "version.ListAppVersionResponse.List.Dependencies")
	proto.RegisterType((*ListAppVersionResponseWrapper)(nil), "version.ListAppVersionResponseWrapper")
}

func init() { proto.RegisterFile("list.proto", fileDescriptor_af793ce248ee1bf0) }

var fileDescriptor_af793ce248ee1bf0 = []byte{
	// 701 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x4f, 0xdb, 0x3a,
	0x18, 0x3e, 0x2d, 0x69, 0xcf, 0x89, 0xcb, 0x39, 0x14, 0x9f, 0xc1, 0xaa, 0x4a, 0x28, 0x95, 0xa9,
	0xa6, 0x4e, 0xac, 0x29, 0x94, 0x7d, 0xdf, 0x11, 0x31, 0x34, 0x34, 0xb6, 0x0b, 0x33, 0x6d, 0xd2,
	0xf8, 0x92, 0x49, 0x4c, 0x88, 0x68, 0x63, 0x2f, 0x31, 0x30, 0x81, 0xd0, 0xfe, 0xd5, 0x7e, 0xc1,
	0x7e, 0x47, 0x27, 0xed, 0x7a, 0x57, 0xbd, 0xde, 0xc5, 0x64, 0x3b, 0x6d, 0x3c, 0xc6, 0x34, 0xb8,
	0x49, 0x9c, 0xf7, 0x79, 0x9e, 0xf7, 0xdb, 0x01, 0xa0, 0x17, 0xa5, 0xc2, 0xe5, 0x09, 0x13, 0x0c,
	0xfe, 0x7d, 0x42, 0x93, 0x34, 0x62, 0x71, 0xbd, 0x1d, 0x46, 0xe2, 0xf0, 0x78, 0xdf, 0xf5, 0x59,
	0xbf, 0x13, 0xb2, 0x90, 0x75, 0x14, 0xbe, 0x7f, 0x7c, 0xa0, 0xbe, 0xd4, 0x87, 0x3a, 0x69, 0x5d,
	0xfd, 0xa1, 0x41, 0xef, 0x9f, 0x46, 0xe2, 0x88, 0x9d, 0x76, 0x42, 0xd6, 0x56, 0x60, 0xfb, 0x84,
	0xf4, 0xa2, 0x80, 0x08, 0x96, 0xa4, 0x9d, 0xf1, 0x51, 0xeb, 0xd0, 0xf7, 0x22, 0x98, 0xd9, 0x88,
	0x52, 0xb1, 0xc2, 0xf9, 0x1b, 0x1d, 0x19, 0xd3, 0xf7, 0xc7, 0x34, 0x15, 0xf0, 0x2e, 0xb0, 0x38,
	0x09, 0x69, 0xad, 0xd0, 0x28, 0xb4, 0x4a, 0xde, 0xcc, 0x70, 0xe0, 0x54, 0x0e, 0x58, 0xd2, 0x7f,
	0x8a, 0xa4, 0x15, 0x7d, 0xfd, 0xe2, 0x14, 0xab, 0x7f, 0x61, 0x45, 0x81, 0x8f, 0x80, 0x2d, 0xdf,
	0x7b, 0x69, 0x74, 0x46, 0x6b, 0x45, 0xc5, 0xaf, 0x0f, 0x07, 0x4e, 0x35, 0xe7, 0x2b, 0x68, 0x24,
	0xfa, 0x47, 0x5a, 0x36, 0xa3, 0x33, 0x0a, 0x5f, 0x80, 0x32, 0xe1, 0x7c, 0x2f, 0x0a, 0x6a, 0x13,
	0x8d, 0x42, 0xcb, 0xf6, 0xee, 0x0f, 0x07, 0xce, 0xbf, 0x5a, 0xa5, 0xed, 0x52, 0xe2, 0x80, 0xb9,
	0xdd, 0x2d, 0xd2, 0x3e, 0x5b, 0x69, 0xbf, 0xdb, 0xdb, 0xd9, 0x5a, 0x6c, 0x3f, 0x19, 0x9d, 0xcf,
	0x17, 0xef, 0x2d, 0x2f, 0x5d, 0x34, 0x71, 0x89, 0x70, 0xbe, 0x1e, 0xc0, 0xe7, 0xc0, 0x4a, 0x59,
	0x22, 0x6a, 0x56, 0xa3, 0xd0, 0xaa, 0x74, 0xe7, 0xdd, 0xac, 0x93, 0xee, 0x95, 0xe5, 0xb9, 0x9b,
	0x2c, 0x11, 0xde, 0x54, 0x5e, 0x95, 0x94, 0x22, 0xac, 0x3c, 0xd4, 0x0f, 0x81, 0x25, 0x61, 0x78,
	0x07, 0x94, 0x7c, 0x11, 0xf5, 0x47, 0x3d, 0xa8, 0x0e, 0x07, 0xce, 0xa4, 0x66, 0x2b, 0x33, 0xc2,
	0x1a, 0x86, 0x8f, 0x41, 0x25, 0xa1, 0x3d, 0x4a, 0x52, 0xfa, 0x5a, 0xb2, 0x75, 0x07, 0x66, 0x87,
	0x03, 0x07, 0x6a, 0xb6, 0x01, 0x22, 0x6c, 0x52, 0xd1, 0xa7, 0x32, 0x98, 0xbd, 0x9c, 0x5f, 0xca,
	0x59, 0x9c, 0x52, 0x19, 0x5c, 0x30, 0x41, 0x7a, 0xbf, 0x06, 0x57, 0x66, 0x84, 0x35, 0x3c, 0x9e,
	0x53, 0xf1, 0x86, 0x73, 0x9a, 0xb8, 0xc1, 0x9c, 0xd6, 0x81, 0x25, 0x77, 0xb4, 0x66, 0x35, 0x26,
	0x5a, 0x95, 0x6e, 0xf3, 0xb7, 0xad, 0xd5, 0xa9, 0x2b, 0xb3, 0xd9, 0x5b, 0xa9, 0x45, 0x58, 0xb9,
	0xa8, 0x7f, 0xb6, 0x80, 0x25, 0x71, 0xb8, 0x06, 0xec, 0xcc, 0xcd, 0x7a, 0xa0, 0x6a, 0xb4, 0xbd,
	0x56, 0x9e, 0xcc, 0x18, 0x92, 0xc9, 0x54, 0xc1, 0x7f, 0xbb, 0xd9, 0xe0, 0x77, 0xce, 0x97, 0x96,
	0x2f, 0x9a, 0x38, 0x97, 0xc2, 0x35, 0x60, 0xc5, 0x24, 0xeb, 0xba, 0xed, 0x75, 0xf3, 0xa8, 0xd2,
	0x7a, 0xad, 0xfd, 0x51, 0x7a, 0xf8, 0x12, 0x54, 0x32, 0xa7, 0xaf, 0xa4, 0x3b, 0xbd, 0x90, 0x0b,
	0xf9, 0x10, 0x0d, 0x50, 0x7a, 0x9d, 0x06, 0x53, 0xbb, 0xdb, 0xc1, 0xc2, 0xb6, 0x3b, 0x7a, 0x34,
	0xb1, 0xa9, 0x87, 0x5d, 0x60, 0xfb, 0x87, 0x24, 0x0e, 0xe9, 0x06, 0x0b, 0xd5, 0x4a, 0xda, 0xde,
	0xad, 0xbc, 0xbc, 0x31, 0x84, 0x70, 0x4e, 0xbb, 0xbc, 0x47, 0x25, 0xa5, 0xba, 0xce, 0x1e, 0xc1,
	0x18, 0x4c, 0x06, 0x94, 0xd3, 0x38, 0xa0, 0xb1, 0x1f, 0xd1, 0xb4, 0x56, 0x56, 0x83, 0x5a, 0xba,
	0xce, 0xa0, 0xdc, 0x55, 0x43, 0xe8, 0xdd, 0x1e, 0x0e, 0x9c, 0xff, 0x75, 0x34, 0xd3, 0x21, 0xc2,
	0x3f, 0xf9, 0xaf, 0x7f, 0x04, 0x93, 0xa6, 0x4c, 0x66, 0xce, 0x89, 0x7f, 0x44, 0x42, 0xaa, 0x9a,
	0x57, 0xb8, 0x9c, 0xb9, 0x01, 0x22, 0x6c, 0x52, 0xe1, 0x03, 0x00, 0x7c, 0x16, 0xa7, 0x22, 0x21,
	0x51, 0x2c, 0xb2, 0x21, 0xca, 0x25, 0x9e, 0xce, 0x1a, 0x35, 0xc6, 0x10, 0x36, 0x88, 0xe8, 0x5b,
	0x01, 0xcc, 0x5d, 0x5d, 0xd4, 0xdb, 0x84, 0x70, 0x4e, 0x13, 0x38, 0x0f, 0x2c, 0x9f, 0x05, 0xa3,
	0xbb, 0x6b, 0x6c, 0xa3, 0xb4, 0x22, 0xac, 0x40, 0x99, 0xb7, 0x7c, 0x3f, 0xfb, 0xc0, 0x7b, 0x24,
	0x8a, 0xb3, 0xf0, 0x46, 0xde, 0x06, 0x88, 0xb0, 0x49, 0x95, 0xd7, 0x93, 0x26, 0x09, 0x4b, 0xb2,
	0x45, 0x31, 0xae, 0xa7, 0x32, 0x23, 0xac, 0x61, 0xb8, 0x0a, 0xac, 0x80, 0x08, 0x92, 0xfd, 0x95,
	0x9c, 0x3f, 0x4c, 0xc4, 0xcc, 0x53, 0xca, 0x10, 0x56, 0xea, 0xfd, 0xb2, 0xfa, 0x5b, 0x2f, 0xff,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x78, 0x0d, 0x43, 0x2b, 0x06, 0x00, 0x00,
}
