// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_approve_object_list.proto

package cmdb_approve

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//GetApproveObjectList请求
type GetApproveObjectListRequest struct {
	//
	//查询条件、类似mongodb
	Query *types.Struct `protobuf:"bytes,1,opt,name=query,proto3" json:"query" form:"query"`
	//
	//获取待审批的或我提交的记录
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type" form:"type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApproveObjectListRequest) Reset()         { *m = GetApproveObjectListRequest{} }
func (m *GetApproveObjectListRequest) String() string { return proto.CompactTextString(m) }
func (*GetApproveObjectListRequest) ProtoMessage()    {}
func (*GetApproveObjectListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b271186ec7493141, []int{0}
}
func (m *GetApproveObjectListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApproveObjectListRequest.Unmarshal(m, b)
}
func (m *GetApproveObjectListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApproveObjectListRequest.Marshal(b, m, deterministic)
}
func (m *GetApproveObjectListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApproveObjectListRequest.Merge(m, src)
}
func (m *GetApproveObjectListRequest) XXX_Size() int {
	return xxx_messageInfo_GetApproveObjectListRequest.Size(m)
}
func (m *GetApproveObjectListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApproveObjectListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApproveObjectListRequest proto.InternalMessageInfo

func (m *GetApproveObjectListRequest) GetQuery() *types.Struct {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *GetApproveObjectListRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

//
//GetApproveObjectList返回
type GetApproveObjectListResponse struct {
	//
	//模型id列表
	ObjectIdList         []string `protobuf:"bytes,1,rep,name=objectIdList,proto3" json:"objectIdList" form:"objectIdList"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApproveObjectListResponse) Reset()         { *m = GetApproveObjectListResponse{} }
func (m *GetApproveObjectListResponse) String() string { return proto.CompactTextString(m) }
func (*GetApproveObjectListResponse) ProtoMessage()    {}
func (*GetApproveObjectListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b271186ec7493141, []int{1}
}
func (m *GetApproveObjectListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApproveObjectListResponse.Unmarshal(m, b)
}
func (m *GetApproveObjectListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApproveObjectListResponse.Marshal(b, m, deterministic)
}
func (m *GetApproveObjectListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApproveObjectListResponse.Merge(m, src)
}
func (m *GetApproveObjectListResponse) XXX_Size() int {
	return xxx_messageInfo_GetApproveObjectListResponse.Size(m)
}
func (m *GetApproveObjectListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApproveObjectListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApproveObjectListResponse proto.InternalMessageInfo

func (m *GetApproveObjectListResponse) GetObjectIdList() []string {
	if m != nil {
		return m.ObjectIdList
	}
	return nil
}

//
//GetApproveObjectListApi返回
type GetApproveObjectListResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *GetApproveObjectListResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetApproveObjectListResponseWrapper) Reset()         { *m = GetApproveObjectListResponseWrapper{} }
func (m *GetApproveObjectListResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*GetApproveObjectListResponseWrapper) ProtoMessage()    {}
func (*GetApproveObjectListResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_b271186ec7493141, []int{2}
}
func (m *GetApproveObjectListResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApproveObjectListResponseWrapper.Unmarshal(m, b)
}
func (m *GetApproveObjectListResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApproveObjectListResponseWrapper.Marshal(b, m, deterministic)
}
func (m *GetApproveObjectListResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApproveObjectListResponseWrapper.Merge(m, src)
}
func (m *GetApproveObjectListResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_GetApproveObjectListResponseWrapper.Size(m)
}
func (m *GetApproveObjectListResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApproveObjectListResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GetApproveObjectListResponseWrapper proto.InternalMessageInfo

func (m *GetApproveObjectListResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetApproveObjectListResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *GetApproveObjectListResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetApproveObjectListResponseWrapper) GetData() *GetApproveObjectListResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetApproveObjectListRequest)(nil), "cmdb_approve.GetApproveObjectListRequest")
	proto.RegisterType((*GetApproveObjectListResponse)(nil), "cmdb_approve.GetApproveObjectListResponse")
	proto.RegisterType((*GetApproveObjectListResponseWrapper)(nil), "cmdb_approve.GetApproveObjectListResponseWrapper")
}

func init() { proto.RegisterFile("get_approve_object_list.proto", fileDescriptor_b271186ec7493141) }

var fileDescriptor_b271186ec7493141 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0x26, 0xf6, 0x4e, 0xe8, 0xde, 0x81, 0xb2, 0x82, 0x86, 0xb3, 0x25, 0xc7, 0x56, 0xe4, 0x10,
	0x93, 0x54, 0x0b, 0xa2, 0x7d, 0x91, 0x1e, 0x88, 0x08, 0x42, 0x61, 0x7d, 0x10, 0x2c, 0x36, 0x6c,
	0x92, 0x6d, 0x8c, 0x26, 0x9d, 0xed, 0x66, 0xd3, 0x7a, 0x8a, 0xbe, 0xf8, 0x3f, 0x23, 0xf8, 0x13,
	0xf2, 0x2e, 0x48, 0x66, 0xef, 0xbc, 0x08, 0x72, 0x4f, 0x99, 0x9d, 0xef, 0x9b, 0x8f, 0xef, 0x9b,
	0x09, 0xd9, 0xcd, 0xa4, 0x89, 0x84, 0x52, 0x1a, 0x2e, 0x65, 0x04, 0xf1, 0x47, 0x99, 0x98, 0xa8,
	0xc8, 0x2b, 0x13, 0x28, 0x0d, 0x06, 0xe8, 0x38, 0x29, 0xd3, 0x78, 0x85, 0x4f, 0xfc, 0x2c, 0x37,
	0x1f, 0xea, 0x38, 0x48, 0xa0, 0x0c, 0x33, 0xc8, 0x20, 0x44, 0x52, 0x5c, 0x9f, 0xe1, 0x0b, 0x1f,
	0x58, 0xd9, 0xe1, 0xc9, 0x4e, 0x06, 0x90, 0x15, 0x72, 0xcd, 0xaa, 0x8c, 0xae, 0x93, 0xa5, 0xf4,
	0xe4, 0x49, 0x4f, 0xac, 0xbc, 0xca, 0xcd, 0x27, 0xb8, 0x0a, 0x33, 0xf0, 0x11, 0xf4, 0x2f, 0x45,
	0x91, 0xa7, 0xc2, 0x80, 0xae, 0xc2, 0xbf, 0xa5, 0x9d, 0x63, 0x3f, 0x1c, 0x72, 0xf7, 0xa5, 0x34,
	0x47, 0xd6, 0xd3, 0x31, 0x5a, 0x7e, 0x9d, 0x57, 0x86, 0xcb, 0x8b, 0x5a, 0x56, 0x86, 0x3e, 0x27,
	0xc3, 0x8b, 0x5a, 0xea, 0x85, 0xeb, 0x4c, 0x9d, 0xd9, 0xe8, 0xf1, 0x9d, 0xc0, 0xba, 0x08, 0x56,
	0x2e, 0x82, 0x37, 0xe8, 0x62, 0x7e, 0xb3, 0x6d, 0xbc, 0xf1, 0x19, 0xe8, 0xf2, 0x90, 0x21, 0x9f,
	0x71, 0x3b, 0x47, 0xf7, 0xc8, 0xc0, 0x2c, 0x94, 0x74, 0xaf, 0x4d, 0x9d, 0xd9, 0xf6, 0xfc, 0x46,
	0xdb, 0x78, 0x23, 0x4b, 0xeb, 0xba, 0x8c, 0x23, 0xc8, 0xbe, 0x93, 0x9d, 0xff, 0x9b, 0xa8, 0x14,
	0x9c, 0x57, 0x92, 0x9e, 0x92, 0xb1, 0xdd, 0xe6, 0xab, 0xb4, 0xeb, 0xbb, 0xce, 0x74, 0x6b, 0xb6,
	0x3d, 0x3f, 0x6c, 0x1b, 0xef, 0x96, 0x15, 0xeb, 0xa3, 0xec, 0xd7, 0x4f, 0xcf, 0x23, 0xbb, 0xa7,
	0x27, 0xc2, 0xff, 0x72, 0xe4, 0xbf, 0x8b, 0xde, 0x9f, 0xec, 0xfb, 0xcf, 0x56, 0xf5, 0xd7, 0xfd,
	0x87, 0x07, 0x8f, 0xbe, 0xdd, 0xe3, 0xff, 0xe8, 0xb1, 0xdf, 0x0e, 0xd9, 0xdb, 0x64, 0xe0, 0xad,
	0x16, 0x4a, 0x49, 0xdd, 0x85, 0x49, 0x20, 0x95, 0xb8, 0x8c, 0x61, 0x3f, 0x4c, 0xd7, 0x65, 0x1c,
	0x41, 0xfa, 0x94, 0x8c, 0xba, 0xef, 0x8b, 0xcf, 0xaa, 0x10, 0xf9, 0xf9, 0x32, 0xf8, 0xed, 0xb6,
	0xf1, 0xe8, 0x9a, 0xbb, 0x04, 0x19, 0xef, 0x53, 0xe9, 0x7d, 0x32, 0x94, 0x5a, 0x83, 0x76, 0xb7,
	0x70, 0xa6, 0xb7, 0x53, 0x6c, 0x33, 0x6e, 0x61, 0x7a, 0x4c, 0x06, 0xa9, 0x30, 0xc2, 0x1d, 0xe0,
	0x4d, 0x1e, 0x04, 0xfd, 0xdf, 0x2a, 0xd8, 0x94, 0xa3, 0x6f, 0xb9, 0x53, 0x60, 0x1c, 0x85, 0xe2,
	0xeb, 0x78, 0xce, 0x83, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0x63, 0xcd, 0xf9, 0xc0, 0x02,
	0x00, 0x00,
}
