// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: traverse_graph.proto

package instance_graph

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	_ "github.com/mwitkow/go-proto-validators"
	cmdb "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/cmdb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
//TraverseGraph请求
type TraverseGraphRequest struct {
	//
	//模型Id
	ObjectId string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id" form:"object_id"`
	//
	//实例的过滤条件 (过滤条件不仅支持属性的过滤，也支持关系字段的过滤)
	Query *types.Struct `protobuf:"bytes,2,opt,name=query,proto3" json:"query" form:"query"`
	//
	//指定返回此关系指向模型的fields
	Fields *types.Struct `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields" form:"fields"`
	//
	//子节点列表
	Child                []*cmdb.TraverseChildNode `protobuf:"bytes,4,rep,name=child,proto3" json:"child" form:"child"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TraverseGraphRequest) Reset()         { *m = TraverseGraphRequest{} }
func (m *TraverseGraphRequest) String() string { return proto.CompactTextString(m) }
func (*TraverseGraphRequest) ProtoMessage()    {}
func (*TraverseGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_327d9eaaa4ac2bcb, []int{0}
}
func (m *TraverseGraphRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraverseGraphRequest.Unmarshal(m, b)
}
func (m *TraverseGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraverseGraphRequest.Marshal(b, m, deterministic)
}
func (m *TraverseGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraverseGraphRequest.Merge(m, src)
}
func (m *TraverseGraphRequest) XXX_Size() int {
	return xxx_messageInfo_TraverseGraphRequest.Size(m)
}
func (m *TraverseGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraverseGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraverseGraphRequest proto.InternalMessageInfo

func (m *TraverseGraphRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *TraverseGraphRequest) GetQuery() *types.Struct {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *TraverseGraphRequest) GetFields() *types.Struct {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *TraverseGraphRequest) GetChild() []*cmdb.TraverseChildNode {
	if m != nil {
		return m.Child
	}
	return nil
}

//
//TraverseGraph返回
type TraverseGraphResponse struct {
	//
	//根节点实例列表
	TopicVertices []*types.Struct `protobuf:"bytes,1,rep,name=topic_vertices,json=topicVertices,proto3" json:"topic_vertices" form:"topic_vertices"`
	//
	//节点实例列表
	Vertices []*types.Struct `protobuf:"bytes,2,rep,name=vertices,proto3" json:"vertices" form:"vertices"`
	//
	//关系列表
	Edges                []*TraverseGraphResponse_Edges `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges" form:"edges"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TraverseGraphResponse) Reset()         { *m = TraverseGraphResponse{} }
func (m *TraverseGraphResponse) String() string { return proto.CompactTextString(m) }
func (*TraverseGraphResponse) ProtoMessage()    {}
func (*TraverseGraphResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_327d9eaaa4ac2bcb, []int{1}
}
func (m *TraverseGraphResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraverseGraphResponse.Unmarshal(m, b)
}
func (m *TraverseGraphResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraverseGraphResponse.Marshal(b, m, deterministic)
}
func (m *TraverseGraphResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraverseGraphResponse.Merge(m, src)
}
func (m *TraverseGraphResponse) XXX_Size() int {
	return xxx_messageInfo_TraverseGraphResponse.Size(m)
}
func (m *TraverseGraphResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TraverseGraphResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TraverseGraphResponse proto.InternalMessageInfo

func (m *TraverseGraphResponse) GetTopicVertices() []*types.Struct {
	if m != nil {
		return m.TopicVertices
	}
	return nil
}

func (m *TraverseGraphResponse) GetVertices() []*types.Struct {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *TraverseGraphResponse) GetEdges() []*TraverseGraphResponse_Edges {
	if m != nil {
		return m.Edges
	}
	return nil
}

type TraverseGraphResponse_Edges struct {
	//
	//关系Id
	RelationId string `protobuf:"bytes,1,opt,name=relation_id,json=relationId,proto3" json:"relation_id" form:"relation_id"`
	//
	//实例Id
	Out string `protobuf:"bytes,2,opt,name=out,proto3" json:"out" form:"out"`
	//
	//实例Id, 例如:「 应用的负责人 」 这一关系数据中, 「应用」数据是 out, 「用户」数据是 in
	In                   string   `protobuf:"bytes,3,opt,name=in,proto3" json:"in" form:"in"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraverseGraphResponse_Edges) Reset()         { *m = TraverseGraphResponse_Edges{} }
func (m *TraverseGraphResponse_Edges) String() string { return proto.CompactTextString(m) }
func (*TraverseGraphResponse_Edges) ProtoMessage()    {}
func (*TraverseGraphResponse_Edges) Descriptor() ([]byte, []int) {
	return fileDescriptor_327d9eaaa4ac2bcb, []int{1, 0}
}
func (m *TraverseGraphResponse_Edges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraverseGraphResponse_Edges.Unmarshal(m, b)
}
func (m *TraverseGraphResponse_Edges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraverseGraphResponse_Edges.Marshal(b, m, deterministic)
}
func (m *TraverseGraphResponse_Edges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraverseGraphResponse_Edges.Merge(m, src)
}
func (m *TraverseGraphResponse_Edges) XXX_Size() int {
	return xxx_messageInfo_TraverseGraphResponse_Edges.Size(m)
}
func (m *TraverseGraphResponse_Edges) XXX_DiscardUnknown() {
	xxx_messageInfo_TraverseGraphResponse_Edges.DiscardUnknown(m)
}

var xxx_messageInfo_TraverseGraphResponse_Edges proto.InternalMessageInfo

func (m *TraverseGraphResponse_Edges) GetRelationId() string {
	if m != nil {
		return m.RelationId
	}
	return ""
}

func (m *TraverseGraphResponse_Edges) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

func (m *TraverseGraphResponse_Edges) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

//
//TraverseGraphApi返回
type TraverseGraphResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *TraverseGraphResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TraverseGraphResponseWrapper) Reset()         { *m = TraverseGraphResponseWrapper{} }
func (m *TraverseGraphResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*TraverseGraphResponseWrapper) ProtoMessage()    {}
func (*TraverseGraphResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_327d9eaaa4ac2bcb, []int{2}
}
func (m *TraverseGraphResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraverseGraphResponseWrapper.Unmarshal(m, b)
}
func (m *TraverseGraphResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraverseGraphResponseWrapper.Marshal(b, m, deterministic)
}
func (m *TraverseGraphResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraverseGraphResponseWrapper.Merge(m, src)
}
func (m *TraverseGraphResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_TraverseGraphResponseWrapper.Size(m)
}
func (m *TraverseGraphResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TraverseGraphResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TraverseGraphResponseWrapper proto.InternalMessageInfo

func (m *TraverseGraphResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TraverseGraphResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *TraverseGraphResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TraverseGraphResponseWrapper) GetData() *TraverseGraphResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TraverseGraphRequest)(nil), "instance_graph.TraverseGraphRequest")
	proto.RegisterType((*TraverseGraphResponse)(nil), "instance_graph.TraverseGraphResponse")
	proto.RegisterType((*TraverseGraphResponse_Edges)(nil), "instance_graph.TraverseGraphResponse.Edges")
	proto.RegisterType((*TraverseGraphResponseWrapper)(nil), "instance_graph.TraverseGraphResponseWrapper")
}

func init() { proto.RegisterFile("traverse_graph.proto", fileDescriptor_327d9eaaa4ac2bcb) }

var fileDescriptor_327d9eaaa4ac2bcb = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x5b, 0x6e, 0xd4, 0x30,
	0x14, 0xd5, 0xbc, 0xaa, 0x8e, 0x87, 0xbe, 0xdc, 0x16, 0x86, 0xaa, 0x28, 0x23, 0xf3, 0x50, 0xa5,
	0x32, 0x89, 0x68, 0x25, 0x40, 0xfc, 0x20, 0x06, 0x55, 0xb4, 0x7c, 0xf0, 0x91, 0x22, 0x9e, 0x82,
	0x91, 0x27, 0x76, 0x53, 0x43, 0x26, 0x37, 0x75, 0x9c, 0x96, 0x82, 0xf8, 0x60, 0x11, 0x6c, 0x81,
	0x65, 0x05, 0x89, 0x1d, 0x90, 0x15, 0x20, 0xdb, 0xe9, 0x34, 0x45, 0xa5, 0xe2, 0xcb, 0xbe, 0xbe,
	0xe7, 0x1c, 0x1f, 0x1f, 0x5f, 0xb4, 0xa4, 0x24, 0x3d, 0xe4, 0x32, 0xe5, 0xc3, 0x50, 0xd2, 0x64,
	0xdf, 0x4d, 0x24, 0x28, 0xc0, 0xb3, 0x22, 0x4e, 0x15, 0x8d, 0x83, 0xf2, 0x74, 0xa5, 0x1f, 0x0a,
	0xb5, 0x9f, 0x8d, 0xdc, 0x00, 0xc6, 0x5e, 0x08, 0x21, 0x78, 0x06, 0x36, 0xca, 0xf6, 0x4c, 0x65,
	0x0a, 0xb3, 0xb3, 0xf4, 0x95, 0x57, 0x21, 0xb8, 0x9c, 0xa6, 0xc7, 0x90, 0xa4, 0x6e, 0x04, 0x01,
	0x8d, 0xbc, 0x00, 0x62, 0x25, 0x69, 0xa0, 0x52, 0xcb, 0x94, 0x3c, 0x81, 0xfe, 0x18, 0x18, 0x8f,
	0x52, 0xaf, 0x04, 0x7a, 0xa6, 0xf4, 0x82, 0x31, 0x1b, 0x79, 0x13, 0x4f, 0xc1, 0xbe, 0x88, 0xd8,
	0x30, 0x06, 0xc6, 0x4b, 0xe5, 0xbb, 0x15, 0x23, 0xe3, 0x23, 0xa1, 0x3e, 0xc2, 0x91, 0x17, 0x42,
	0xdf, 0x34, 0xfb, 0x87, 0x34, 0x12, 0x8c, 0x2a, 0x90, 0xa9, 0x37, 0xd9, 0x96, 0xbc, 0xd5, 0x10,
	0x20, 0x8c, 0xf8, 0xa9, 0xef, 0x54, 0xc9, 0x2c, 0x50, 0xb6, 0x4b, 0x7e, 0xd4, 0xd1, 0xd2, 0xf3,
	0xf2, 0xce, 0x27, 0xfa, 0xc1, 0x3e, 0x3f, 0xc8, 0x78, 0xaa, 0xf0, 0x36, 0x6a, 0xc3, 0xe8, 0x03,
	0x0f, 0xd4, 0x50, 0xb0, 0x6e, 0xad, 0x57, 0x5b, 0x6b, 0x0f, 0xd6, 0x8b, 0xdc, 0x99, 0xdf, 0x03,
	0x39, 0x7e, 0x40, 0x26, 0x2d, 0xf2, 0xeb, 0xa7, 0xb3, 0x88, 0x16, 0xde, 0xbf, 0xa5, 0xfd, 0xcf,
	0x8f, 0xfa, 0x6f, 0x86, 0xef, 0xbe, 0xdc, 0xb9, 0xbd, 0xb9, 0xf1, 0xf5, 0x86, 0x3f, 0x6d, 0x21,
	0x3b, 0x0c, 0x3f, 0x44, 0xad, 0x83, 0x8c, 0xcb, 0xe3, 0x6e, 0xbd, 0x57, 0x5b, 0xeb, 0x6c, 0x5c,
	0x71, 0xad, 0x21, 0xf7, 0xc4, 0x90, 0xbb, 0x6b, 0x0c, 0x0d, 0xe6, 0x8b, 0xdc, 0xb9, 0x64, 0xe5,
	0x0d, 0x9e, 0xf8, 0x96, 0x87, 0x07, 0x68, 0x6a, 0x4f, 0xf0, 0x88, 0xa5, 0xdd, 0xc6, 0xc5, 0x0a,
	0x0b, 0x45, 0xee, 0xcc, 0x58, 0x05, 0x4b, 0x20, 0x7e, 0xc9, 0xd4, 0x26, 0x4c, 0xa2, 0xdd, 0x66,
	0xaf, 0x61, 0x24, 0x74, 0xda, 0xee, 0xc9, 0xcb, 0x1f, 0xeb, 0xd6, 0x33, 0x60, 0xbc, 0x6a, 0xc2,
	0xe0, 0x89, 0x6f, 0x79, 0xe4, 0x7b, 0x03, 0x2d, 0xff, 0x15, 0x54, 0x9a, 0x40, 0x9c, 0x72, 0xfc,
	0x1a, 0xcd, 0x2a, 0x48, 0x44, 0x30, 0x3c, 0xe4, 0x52, 0x89, 0x80, 0xa7, 0xdd, 0x5a, 0x79, 0xc7,
	0x3f, 0x6c, 0x5e, 0x2d, 0x72, 0x67, 0xd9, 0xde, 0x71, 0x96, 0x48, 0xfc, 0x19, 0x73, 0xf0, 0xa2,
	0xac, 0xf1, 0x36, 0x9a, 0x9e, 0x88, 0xd6, 0x2f, 0x16, 0x5d, 0x2c, 0x72, 0x67, 0xce, 0x8a, 0x9e,
	0xca, 0x4d, 0xd8, 0x78, 0x17, 0xb5, 0x38, 0x0b, 0xb9, 0x8e, 0x50, 0xcb, 0xac, 0xbb, 0x67, 0xc7,
	0xdc, 0x3d, 0xf7, 0x69, 0xee, 0x96, 0xa6, 0x54, 0x33, 0x31, 0x1a, 0xc4, 0xb7, 0x5a, 0x2b, 0xdf,
	0x6a, 0xa8, 0x65, 0x20, 0xf8, 0x1e, 0xea, 0x48, 0x1e, 0x51, 0x25, 0x20, 0x3e, 0x9d, 0x97, 0xcb,
	0x45, 0xee, 0x60, 0xcb, 0xab, 0x34, 0x89, 0x8f, 0x4e, 0xaa, 0x1d, 0x86, 0x7b, 0xa8, 0x01, 0x99,
	0x32, 0xa3, 0xd1, 0x1e, 0xcc, 0x16, 0xb9, 0x83, 0xca, 0x01, 0xcb, 0x14, 0xf1, 0x75, 0x0b, 0x5f,
	0x43, 0x75, 0x11, 0x9b, 0x9f, 0x6f, 0x0f, 0x66, 0x8a, 0xdc, 0x69, 0x5b, 0x80, 0x88, 0x89, 0x5f,
	0x17, 0x31, 0xf9, 0x5d, 0x43, 0xab, 0xe7, 0x9a, 0x7f, 0x29, 0x69, 0x92, 0x70, 0x89, 0xaf, 0xa3,
	0x66, 0x00, 0x8c, 0x1b, 0x4f, 0xad, 0xc1, 0x5c, 0x91, 0x3b, 0x9d, 0xf2, 0x7f, 0x81, 0x71, 0xe2,
	0x9b, 0x26, 0xbe, 0x8f, 0x3a, 0x7a, 0xdd, 0xfa, 0x94, 0x44, 0x54, 0xc4, 0xa5, 0x9d, 0x8a, 0xff,
	0x4a, 0x93, 0xf8, 0x55, 0x28, 0xbe, 0x85, 0x5a, 0x5c, 0x4a, 0x90, 0xa5, 0xc3, 0x6a, 0x56, 0xfa,
	0x58, 0x67, 0xa5, 0x57, 0xfc, 0x14, 0x35, 0x19, 0x55, 0xb4, 0xdb, 0x34, 0x23, 0x7c, 0xf3, 0xbf,
	0xf2, 0xaf, 0xba, 0xd5, 0x64, 0xe2, 0x1b, 0x8d, 0xd1, 0x94, 0xf9, 0xfc, 0xcd, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x76, 0x85, 0xba, 0xc1, 0xc2, 0x04, 0x00, 0x00,
}
