// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: delete_instance_batch.proto

package instance

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	cmdb "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/cmdb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
//DeleteInstanceBatch请求
type DeleteInstanceBatchRequest struct {
	//
	//模型对象ID
	ObjectId string `protobuf:"bytes,1,opt,name=objectId,proto3" json:"objectId" form:"objectId"`
	//
	//实例ID, 用分号隔开, e.g. 5ab9f10a6ef88;5abb0dca9971d
	InstanceIds          string   `protobuf:"bytes,2,opt,name=instanceIds,proto3" json:"instanceIds" form:"instanceIds"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteInstanceBatchRequest) Reset()         { *m = DeleteInstanceBatchRequest{} }
func (m *DeleteInstanceBatchRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteInstanceBatchRequest) ProtoMessage()    {}
func (*DeleteInstanceBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1107d4cc07423e91, []int{0}
}
func (m *DeleteInstanceBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstanceBatchRequest.Unmarshal(m, b)
}
func (m *DeleteInstanceBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstanceBatchRequest.Marshal(b, m, deterministic)
}
func (m *DeleteInstanceBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstanceBatchRequest.Merge(m, src)
}
func (m *DeleteInstanceBatchRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteInstanceBatchRequest.Size(m)
}
func (m *DeleteInstanceBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstanceBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstanceBatchRequest proto.InternalMessageInfo

func (m *DeleteInstanceBatchRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *DeleteInstanceBatchRequest) GetInstanceIds() string {
	if m != nil {
		return m.InstanceIds
	}
	return ""
}

//
//DeleteInstanceBatch返回
type DeleteInstanceBatchResponse struct {
	//
	//删除失败的实例列表
	DeleteFailedInstances []*cmdb.FailInstance `protobuf:"bytes,1,rep,name=deleteFailedInstances,proto3" json:"deleteFailedInstances" form:"deleteFailedInstances"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *DeleteInstanceBatchResponse) Reset()         { *m = DeleteInstanceBatchResponse{} }
func (m *DeleteInstanceBatchResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteInstanceBatchResponse) ProtoMessage()    {}
func (*DeleteInstanceBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1107d4cc07423e91, []int{1}
}
func (m *DeleteInstanceBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstanceBatchResponse.Unmarshal(m, b)
}
func (m *DeleteInstanceBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstanceBatchResponse.Marshal(b, m, deterministic)
}
func (m *DeleteInstanceBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstanceBatchResponse.Merge(m, src)
}
func (m *DeleteInstanceBatchResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteInstanceBatchResponse.Size(m)
}
func (m *DeleteInstanceBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstanceBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstanceBatchResponse proto.InternalMessageInfo

func (m *DeleteInstanceBatchResponse) GetDeleteFailedInstances() []*cmdb.FailInstance {
	if m != nil {
		return m.DeleteFailedInstances
	}
	return nil
}

//
//DeleteInstanceBatchApi返回
type DeleteInstanceBatchResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *DeleteInstanceBatchResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DeleteInstanceBatchResponseWrapper) Reset()         { *m = DeleteInstanceBatchResponseWrapper{} }
func (m *DeleteInstanceBatchResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*DeleteInstanceBatchResponseWrapper) ProtoMessage()    {}
func (*DeleteInstanceBatchResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_1107d4cc07423e91, []int{2}
}
func (m *DeleteInstanceBatchResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteInstanceBatchResponseWrapper.Unmarshal(m, b)
}
func (m *DeleteInstanceBatchResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteInstanceBatchResponseWrapper.Marshal(b, m, deterministic)
}
func (m *DeleteInstanceBatchResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteInstanceBatchResponseWrapper.Merge(m, src)
}
func (m *DeleteInstanceBatchResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_DeleteInstanceBatchResponseWrapper.Size(m)
}
func (m *DeleteInstanceBatchResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteInstanceBatchResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteInstanceBatchResponseWrapper proto.InternalMessageInfo

func (m *DeleteInstanceBatchResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteInstanceBatchResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *DeleteInstanceBatchResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DeleteInstanceBatchResponseWrapper) GetData() *DeleteInstanceBatchResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteInstanceBatchRequest)(nil), "instance.DeleteInstanceBatchRequest")
	proto.RegisterType((*DeleteInstanceBatchResponse)(nil), "instance.DeleteInstanceBatchResponse")
	proto.RegisterType((*DeleteInstanceBatchResponseWrapper)(nil), "instance.DeleteInstanceBatchResponseWrapper")
}

func init() { proto.RegisterFile("delete_instance_batch.proto", fileDescriptor_1107d4cc07423e91) }

var fileDescriptor_1107d4cc07423e91 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xa6, 0xee, 0xae, 0xac, 0x19, 0x61, 0x35, 0xa2, 0x94, 0x59, 0xa1, 0x43, 0xfc, 0x61, 0x10,
	0xdb, 0xe0, 0x2c, 0x88, 0x78, 0xe7, 0xa0, 0x0b, 0xe3, 0x65, 0x6e, 0x04, 0x45, 0x87, 0x34, 0xc9,
	0x74, 0xbb, 0xb6, 0x3d, 0x35, 0xc9, 0xb8, 0xfe, 0xe0, 0x03, 0xf8, 0x12, 0x3e, 0x5a, 0x05, 0x1f,
	0xa1, 0x37, 0xde, 0x4a, 0x93, 0x99, 0x52, 0x70, 0xd8, 0xab, 0xe6, 0x9c, 0xef, 0x27, 0xdf, 0x39,
	0x0d, 0x3a, 0x96, 0xaa, 0x50, 0x56, 0x2d, 0xf3, 0xca, 0x58, 0x5e, 0x09, 0xb5, 0x4c, 0xb9, 0x15,
	0x67, 0x49, 0xad, 0xc1, 0x02, 0x3e, 0xdc, 0x76, 0xc7, 0x71, 0x96, 0xdb, 0xb3, 0x75, 0x9a, 0x08,
	0x28, 0x69, 0x06, 0x19, 0x50, 0x47, 0x48, 0xd7, 0x2b, 0x57, 0xb9, 0xc2, 0x9d, 0xbc, 0x70, 0xcc,
	0x32, 0x48, 0x14, 0x37, 0x5f, 0xa1, 0x36, 0x49, 0x01, 0x82, 0x17, 0x54, 0x40, 0x65, 0x35, 0x17,
	0xd6, 0x78, 0xa5, 0x56, 0x35, 0xc4, 0x25, 0x48, 0x55, 0x18, 0xba, 0x21, 0x52, 0x57, 0x52, 0x51,
	0xca, 0x94, 0xae, 0x78, 0x5e, 0xf4, 0x91, 0x36, 0x9e, 0x4f, 0x07, 0x11, 0xca, 0x8b, 0xdc, 0x7e,
	0x84, 0x0b, 0x9a, 0x41, 0xec, 0xc0, 0xf8, 0x33, 0x2f, 0x72, 0xc9, 0x2d, 0x68, 0x43, 0xfb, 0xa3,
	0xd7, 0x91, 0x5f, 0x01, 0x1a, 0xbf, 0x74, 0x43, 0x2e, 0x36, 0x86, 0xf3, 0x6e, 0x44, 0xa6, 0x3e,
	0xad, 0x95, 0xb1, 0xf8, 0x14, 0x1d, 0x42, 0x7a, 0xae, 0x84, 0x5d, 0xc8, 0x30, 0x98, 0x04, 0xd3,
	0x6b, 0xf3, 0x47, 0x6d, 0x13, 0x1d, 0xad, 0x40, 0x97, 0xcf, 0xc9, 0x16, 0x21, 0x7f, 0x7e, 0x47,
	0xb7, 0xd0, 0xcd, 0x0f, 0xef, 0x78, 0xfc, 0xed, 0x45, 0xfc, 0x76, 0xf9, 0xfe, 0xfb, 0x93, 0xc7,
	0x27, 0xb3, 0x1f, 0xf7, 0x59, 0xaf, 0xc5, 0xcf, 0xd0, 0x68, 0x1b, 0x78, 0x21, 0x4d, 0x78, 0xc5,
	0x59, 0xdd, 0x69, 0x9b, 0x08, 0x7b, 0xab, 0x01, 0x48, 0xd8, 0x90, 0x4a, 0x7e, 0x06, 0xe8, 0x78,
	0x67, 0x40, 0x53, 0x43, 0x65, 0x14, 0x3e, 0x47, 0xb7, 0xfd, 0x4f, 0x3a, 0xe5, 0x79, 0xa1, 0xe4,
	0x96, 0x64, 0xc2, 0x60, 0xb2, 0x37, 0x1d, 0xcd, 0x70, 0xd2, 0xad, 0x2c, 0xe9, 0xc0, 0x5e, 0x3f,
	0x69, 0x9b, 0xe8, 0xae, 0xbf, 0x77, 0xa7, 0x94, 0xb0, 0xdd, 0x96, 0xe4, 0x6f, 0x80, 0xc8, 0x25,
	0x59, 0xde, 0x68, 0x5e, 0xd7, 0x4a, 0xe3, 0x7b, 0x68, 0x5f, 0x80, 0x54, 0x6e, 0x61, 0x07, 0xf3,
	0xa3, 0xb6, 0x89, 0x46, 0xfe, 0xb6, 0xae, 0x4b, 0x98, 0x03, 0xbb, 0x8d, 0x74, 0xdf, 0x57, 0x5f,
	0xea, 0x82, 0xe7, 0xd5, 0xff, 0x1b, 0x19, 0x80, 0x84, 0x0d, 0xa9, 0xf8, 0x21, 0x3a, 0x50, 0x5a,
	0x83, 0x0e, 0xf7, 0x9c, 0xe6, 0x46, 0xdb, 0x44, 0xd7, 0xbd, 0xc6, 0xb5, 0x09, 0xf3, 0x30, 0x7e,
	0x8d, 0xf6, 0x25, 0xb7, 0x3c, 0xdc, 0x9f, 0x04, 0xd3, 0xd1, 0xec, 0x41, 0xd2, 0xbf, 0x98, 0x4b,
	0x46, 0x18, 0xa6, 0xed, 0xc4, 0x84, 0x39, 0x8f, 0xf4, 0xaa, 0x7b, 0x2d, 0x27, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x7e, 0x01, 0x98, 0x21, 0x11, 0x03, 0x00, 0x00,
}
