// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: translate_data_handler.proto

package translate_rule

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//TranslateDataHandler请求
type TranslateDataHandlerRequest struct {
	//
	//翻译规则id
	RuleIds              []string `protobuf:"bytes,1,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids" form:"rule_ids"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateDataHandlerRequest) Reset()         { *m = TranslateDataHandlerRequest{} }
func (m *TranslateDataHandlerRequest) String() string { return proto.CompactTextString(m) }
func (*TranslateDataHandlerRequest) ProtoMessage()    {}
func (*TranslateDataHandlerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa1effcdde97081, []int{0}
}
func (m *TranslateDataHandlerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateDataHandlerRequest.Unmarshal(m, b)
}
func (m *TranslateDataHandlerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateDataHandlerRequest.Marshal(b, m, deterministic)
}
func (m *TranslateDataHandlerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateDataHandlerRequest.Merge(m, src)
}
func (m *TranslateDataHandlerRequest) XXX_Size() int {
	return xxx_messageInfo_TranslateDataHandlerRequest.Size(m)
}
func (m *TranslateDataHandlerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateDataHandlerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateDataHandlerRequest proto.InternalMessageInfo

func (m *TranslateDataHandlerRequest) GetRuleIds() []string {
	if m != nil {
		return m.RuleIds
	}
	return nil
}

//
//TranslateDataHandler返回
type TranslateDataHandlerResponse struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//分页参数
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//页数
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page" form:"page"`
	//
	//返回信息
	Msg string `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg" form:"msg"`
	//
	//总数
	Total int32 `protobuf:"varint,5,opt,name=total,proto3" json:"total" form:"total"`
	//
	//返回数据
	Data                 []*TranslateDataHandlerResponse_Data `protobuf:"bytes,6,rep,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *TranslateDataHandlerResponse) Reset()         { *m = TranslateDataHandlerResponse{} }
func (m *TranslateDataHandlerResponse) String() string { return proto.CompactTextString(m) }
func (*TranslateDataHandlerResponse) ProtoMessage()    {}
func (*TranslateDataHandlerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa1effcdde97081, []int{1}
}
func (m *TranslateDataHandlerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateDataHandlerResponse.Unmarshal(m, b)
}
func (m *TranslateDataHandlerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateDataHandlerResponse.Marshal(b, m, deterministic)
}
func (m *TranslateDataHandlerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateDataHandlerResponse.Merge(m, src)
}
func (m *TranslateDataHandlerResponse) XXX_Size() int {
	return xxx_messageInfo_TranslateDataHandlerResponse.Size(m)
}
func (m *TranslateDataHandlerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateDataHandlerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateDataHandlerResponse proto.InternalMessageInfo

func (m *TranslateDataHandlerResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TranslateDataHandlerResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *TranslateDataHandlerResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *TranslateDataHandlerResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *TranslateDataHandlerResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *TranslateDataHandlerResponse) GetData() []*TranslateDataHandlerResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type TranslateDataHandlerResponse_Data struct {
	//
	//匹配key
	MatchKey string `protobuf:"bytes,1,opt,name=matchKey,proto3" json:"matchKey" form:"matchKey"`
	//
	//关联资源
	Resource *TranslateDataHandlerResponse_Data_Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource" form:"resource"`
	//
	//标签
	Tags                 []*TranslateDataHandlerResponse_Data_Tags `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags" form:"tags"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *TranslateDataHandlerResponse_Data) Reset()         { *m = TranslateDataHandlerResponse_Data{} }
func (m *TranslateDataHandlerResponse_Data) String() string { return proto.CompactTextString(m) }
func (*TranslateDataHandlerResponse_Data) ProtoMessage()    {}
func (*TranslateDataHandlerResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa1effcdde97081, []int{1, 0}
}
func (m *TranslateDataHandlerResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data.Unmarshal(m, b)
}
func (m *TranslateDataHandlerResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data.Marshal(b, m, deterministic)
}
func (m *TranslateDataHandlerResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateDataHandlerResponse_Data.Merge(m, src)
}
func (m *TranslateDataHandlerResponse_Data) XXX_Size() int {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data.Size(m)
}
func (m *TranslateDataHandlerResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateDataHandlerResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateDataHandlerResponse_Data proto.InternalMessageInfo

func (m *TranslateDataHandlerResponse_Data) GetMatchKey() string {
	if m != nil {
		return m.MatchKey
	}
	return ""
}

func (m *TranslateDataHandlerResponse_Data) GetResource() *TranslateDataHandlerResponse_Data_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *TranslateDataHandlerResponse_Data) GetTags() []*TranslateDataHandlerResponse_Data_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type TranslateDataHandlerResponse_Data_Resource struct {
	//
	//实例id列表
	Instances []string `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances" form:"instances"`
	//
	//关联模型Id
	ObjectId             string   `protobuf:"bytes,2,opt,name=objectId,proto3" json:"objectId" form:"objectId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateDataHandlerResponse_Data_Resource) Reset() {
	*m = TranslateDataHandlerResponse_Data_Resource{}
}
func (m *TranslateDataHandlerResponse_Data_Resource) String() string {
	return proto.CompactTextString(m)
}
func (*TranslateDataHandlerResponse_Data_Resource) ProtoMessage() {}
func (*TranslateDataHandlerResponse_Data_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa1effcdde97081, []int{1, 0, 0}
}
func (m *TranslateDataHandlerResponse_Data_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data_Resource.Unmarshal(m, b)
}
func (m *TranslateDataHandlerResponse_Data_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data_Resource.Marshal(b, m, deterministic)
}
func (m *TranslateDataHandlerResponse_Data_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateDataHandlerResponse_Data_Resource.Merge(m, src)
}
func (m *TranslateDataHandlerResponse_Data_Resource) XXX_Size() int {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data_Resource.Size(m)
}
func (m *TranslateDataHandlerResponse_Data_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateDataHandlerResponse_Data_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateDataHandlerResponse_Data_Resource proto.InternalMessageInfo

func (m *TranslateDataHandlerResponse_Data_Resource) GetInstances() []string {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *TranslateDataHandlerResponse_Data_Resource) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type TranslateDataHandlerResponse_Data_Tags struct {
	//
	//值
	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value" form:"value"`
	//
	//键
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key" form:"key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TranslateDataHandlerResponse_Data_Tags) Reset() {
	*m = TranslateDataHandlerResponse_Data_Tags{}
}
func (m *TranslateDataHandlerResponse_Data_Tags) String() string { return proto.CompactTextString(m) }
func (*TranslateDataHandlerResponse_Data_Tags) ProtoMessage()    {}
func (*TranslateDataHandlerResponse_Data_Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa1effcdde97081, []int{1, 0, 1}
}
func (m *TranslateDataHandlerResponse_Data_Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data_Tags.Unmarshal(m, b)
}
func (m *TranslateDataHandlerResponse_Data_Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data_Tags.Marshal(b, m, deterministic)
}
func (m *TranslateDataHandlerResponse_Data_Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateDataHandlerResponse_Data_Tags.Merge(m, src)
}
func (m *TranslateDataHandlerResponse_Data_Tags) XXX_Size() int {
	return xxx_messageInfo_TranslateDataHandlerResponse_Data_Tags.Size(m)
}
func (m *TranslateDataHandlerResponse_Data_Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateDataHandlerResponse_Data_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateDataHandlerResponse_Data_Tags proto.InternalMessageInfo

func (m *TranslateDataHandlerResponse_Data_Tags) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TranslateDataHandlerResponse_Data_Tags) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

//
//TranslateDataHandlerApi返回
type TranslateDataHandlerResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *TranslateDataHandlerResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TranslateDataHandlerResponseWrapper) Reset()         { *m = TranslateDataHandlerResponseWrapper{} }
func (m *TranslateDataHandlerResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*TranslateDataHandlerResponseWrapper) ProtoMessage()    {}
func (*TranslateDataHandlerResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa1effcdde97081, []int{2}
}
func (m *TranslateDataHandlerResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TranslateDataHandlerResponseWrapper.Unmarshal(m, b)
}
func (m *TranslateDataHandlerResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TranslateDataHandlerResponseWrapper.Marshal(b, m, deterministic)
}
func (m *TranslateDataHandlerResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TranslateDataHandlerResponseWrapper.Merge(m, src)
}
func (m *TranslateDataHandlerResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_TranslateDataHandlerResponseWrapper.Size(m)
}
func (m *TranslateDataHandlerResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_TranslateDataHandlerResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_TranslateDataHandlerResponseWrapper proto.InternalMessageInfo

func (m *TranslateDataHandlerResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TranslateDataHandlerResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *TranslateDataHandlerResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *TranslateDataHandlerResponseWrapper) GetData() *TranslateDataHandlerResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TranslateDataHandlerRequest)(nil), "translate_rule.TranslateDataHandlerRequest")
	proto.RegisterType((*TranslateDataHandlerResponse)(nil), "translate_rule.TranslateDataHandlerResponse")
	proto.RegisterType((*TranslateDataHandlerResponse_Data)(nil), "translate_rule.TranslateDataHandlerResponse.Data")
	proto.RegisterType((*TranslateDataHandlerResponse_Data_Resource)(nil), "translate_rule.TranslateDataHandlerResponse.Data.Resource")
	proto.RegisterType((*TranslateDataHandlerResponse_Data_Tags)(nil), "translate_rule.TranslateDataHandlerResponse.Data.Tags")
	proto.RegisterType((*TranslateDataHandlerResponseWrapper)(nil), "translate_rule.TranslateDataHandlerResponseWrapper")
}

func init() { proto.RegisterFile("translate_data_handler.proto", fileDescriptor_0fa1effcdde97081) }

var fileDescriptor_0fa1effcdde97081 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x6a, 0x13, 0x41,
	0x18, 0x6e, 0x9a, 0x4d, 0x4d, 0x26, 0xd2, 0x86, 0x11, 0x74, 0x89, 0x95, 0x0d, 0xd3, 0x22, 0xb9,
	0xe8, 0x6e, 0x7a, 0x80, 0xaa, 0xbd, 0x33, 0xa8, 0x58, 0x44, 0xd0, 0xb1, 0x28, 0x58, 0xda, 0x30,
	0xc9, 0x4e, 0xb7, 0x6b, 0x36, 0x99, 0x38, 0x33, 0x69, 0x6d, 0x4a, 0x5f, 0xc7, 0x77, 0xf0, 0x19,
	0x7c, 0x87, 0x15, 0x7c, 0x84, 0xbd, 0x16, 0x94, 0x99, 0x3d, 0x06, 0xb4, 0xd8, 0xab, 0xfc, 0xfb,
	0x7f, 0xdf, 0x7c, 0xff, 0x39, 0x60, 0x55, 0x72, 0x32, 0x16, 0x01, 0x91, 0xb4, 0xe7, 0x12, 0x49,
	0x7a, 0xa7, 0x64, 0xec, 0x06, 0x94, 0x3b, 0x13, 0xce, 0x24, 0x83, 0xcb, 0x39, 0xca, 0xa7, 0x01,
	0x6d, 0xda, 0x9e, 0x2f, 0x4f, 0xa7, 0x7d, 0x67, 0xc0, 0x46, 0x1d, 0x8f, 0x79, 0xac, 0xa3, 0x69,
	0xfd, 0xe9, 0x89, 0xfe, 0xd2, 0x1f, 0xda, 0x8a, 0x9f, 0x37, 0x77, 0x0b, 0xf4, 0xd1, 0xb9, 0x2f,
	0x87, 0xec, 0xbc, 0xe3, 0x31, 0x5b, 0x83, 0xf6, 0x19, 0x09, 0x7c, 0x97, 0x48, 0xc6, 0x45, 0x27,
	0x33, 0xe3, 0x77, 0xe8, 0x35, 0xb8, 0x7f, 0x90, 0x06, 0x7e, 0x46, 0x24, 0x79, 0x19, 0x27, 0x85,
	0xe9, 0xe7, 0x29, 0x15, 0x12, 0x3a, 0xa0, 0xaa, 0xb2, 0xe9, 0xf9, 0xae, 0x30, 0x4b, 0xad, 0x72,
	0xbb, 0xd6, 0xbd, 0x13, 0x85, 0xd6, 0xca, 0x09, 0xe3, 0xa3, 0x3d, 0x94, 0x22, 0x08, 0xdf, 0x52,
	0xe6, 0xbe, 0x2b, 0xd0, 0xf7, 0x25, 0xb0, 0xfa, 0x77, 0x3d, 0x31, 0x61, 0x63, 0x41, 0xe1, 0x1a,
	0x30, 0x06, 0xcc, 0xa5, 0x66, 0xa9, 0x55, 0x6a, 0x57, 0xba, 0x2b, 0x51, 0x68, 0xd5, 0x63, 0x31,
	0xe5, 0x45, 0x58, 0x83, 0xf0, 0x11, 0xa8, 0x4d, 0x88, 0x47, 0x7b, 0xc2, 0x9f, 0x51, 0x73, 0x51,
	0x33, 0x9b, 0x51, 0x68, 0x35, 0x62, 0x66, 0x06, 0xa1, 0x9f, 0x3f, 0xac, 0xc5, 0xc6, 0x02, 0xae,
	0x2a, 0xcf, 0x3b, 0x7f, 0x46, 0xe1, 0x06, 0x30, 0x94, 0x6d, 0x96, 0xf5, 0x1b, 0x33, 0x57, 0x57,
	0x5e, 0x45, 0xaf, 0x34, 0x16, 0xcc, 0x6f, 0xf7, 0xb0, 0x66, 0xc1, 0x16, 0x28, 0x8f, 0x84, 0x67,
	0x1a, 0xad, 0x52, 0xbb, 0xd6, 0x5d, 0x8e, 0x42, 0x0b, 0xc4, 0xe4, 0x91, 0xf0, 0x10, 0x56, 0x10,
	0x7c, 0x08, 0x2a, 0x92, 0x49, 0x12, 0x98, 0x15, 0x2d, 0xd8, 0x88, 0x42, 0xeb, 0x76, 0xcc, 0xd1,
	0x6e, 0x84, 0x63, 0x18, 0xbe, 0x07, 0x86, 0x1a, 0xa9, 0xb9, 0xd4, 0x2a, 0xb7, 0xeb, 0xdb, 0x5b,
	0xce, 0xfc, 0x2c, 0x9d, 0xeb, 0x3a, 0xe2, 0x28, 0x5f, 0xb1, 0x11, 0x4a, 0x08, 0x61, 0xad, 0xd7,
	0xfc, 0x55, 0x06, 0x86, 0xc2, 0x61, 0x07, 0x54, 0x47, 0x44, 0x0e, 0x4e, 0x5f, 0xd1, 0x0b, 0xdd,
	0xba, 0xb9, 0x39, 0xa4, 0x08, 0xc2, 0x19, 0x09, 0x0e, 0x41, 0x95, 0x53, 0xc1, 0xa6, 0x7c, 0x10,
	0x77, 0xb0, 0xbe, 0xbd, 0x77, 0xe3, 0xac, 0x1c, 0x9c, 0x28, 0xcc, 0x0d, 0x3d, 0xf1, 0x21, 0x9c,
	0x05, 0x80, 0x87, 0xc0, 0x90, 0xc4, 0x13, 0x66, 0x59, 0x97, 0xbf, 0x7b, 0xf3, 0x40, 0x07, 0xc4,
	0x13, 0xc5, 0x1e, 0x28, 0x35, 0x84, 0xb5, 0x68, 0xf3, 0x6b, 0x09, 0x54, 0xd3, 0x44, 0xe0, 0x0b,
	0x50, 0xf3, 0xc7, 0x42, 0x92, 0xf1, 0x80, 0xa6, 0x0b, 0xd9, 0xce, 0x37, 0x23, 0x83, 0xd4, 0xa8,
	0x1b, 0x60, 0xf9, 0xf8, 0x70, 0xd3, 0x7e, 0x42, 0xec, 0xd9, 0xd1, 0xe5, 0xd6, 0xce, 0xd5, 0x3a,
	0xce, 0x9f, 0x42, 0x0c, 0xaa, 0xac, 0xff, 0x89, 0x0e, 0xe4, 0xbe, 0xab, 0xdb, 0x53, 0xeb, 0xee,
	0xe6, 0x25, 0xa6, 0x88, 0x52, 0xb1, 0xc0, 0x83, 0xe3, 0x43, 0x62, 0xcf, 0x9e, 0xda, 0x1f, 0x7b,
	0x47, 0x89, 0x9c, 0xb6, 0x2f, 0x37, 0x37, 0x76, 0xb6, 0xae, 0xd6, 0x71, 0xa6, 0xd3, 0x7c, 0x03,
	0x0c, 0x55, 0x87, 0x5a, 0x9a, 0x33, 0x12, 0x4c, 0x69, 0x92, 0x5f, 0x61, 0x69, 0xb4, 0x1b, 0xe1,
	0x18, 0x56, 0xeb, 0x37, 0xa4, 0x17, 0x49, 0xf8, 0xc2, 0xfa, 0x0d, 0xd5, 0x24, 0x15, 0x84, 0x7e,
	0x97, 0xc0, 0xda, 0x75, 0xcd, 0xfb, 0xc0, 0xc9, 0x64, 0x42, 0xf9, 0xff, 0x1d, 0xd5, 0x63, 0x50,
	0x57, 0xbf, 0xcf, 0xbf, 0x4c, 0x02, 0xe2, 0x8f, 0x93, 0xb0, 0x77, 0xa3, 0xd0, 0x82, 0x39, 0x37,
	0x01, 0x11, 0x2e, 0x52, 0x55, 0x41, 0x94, 0x73, 0xc6, 0xf5, 0x59, 0xcd, 0x15, 0xa4, 0xdd, 0x08,
	0xc7, 0x30, 0x7c, 0x9b, 0x5c, 0x81, 0xa1, 0xf7, 0x6d, 0xe3, 0x26, 0x6b, 0xf0, 0x8f, 0x03, 0xe8,
	0x2f, 0xe9, 0x7f, 0xa9, 0x9d, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x14, 0x32, 0x7a, 0x3c,
	0x05, 0x00, 0x00,
}
