// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_toolkit_status.proto

package toolkit

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//GetToolkitStatus请求
type GetToolkitStatusRequest struct {
	//
	//模型Id
	ObjectId             string   `protobuf:"bytes,1,opt,name=objectId,proto3" json:"objectId" form:"objectId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetToolkitStatusRequest) Reset()         { *m = GetToolkitStatusRequest{} }
func (m *GetToolkitStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetToolkitStatusRequest) ProtoMessage()    {}
func (*GetToolkitStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c3eb14039f57f44, []int{0}
}
func (m *GetToolkitStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetToolkitStatusRequest.Unmarshal(m, b)
}
func (m *GetToolkitStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetToolkitStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetToolkitStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetToolkitStatusRequest.Merge(m, src)
}
func (m *GetToolkitStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetToolkitStatusRequest.Size(m)
}
func (m *GetToolkitStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetToolkitStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetToolkitStatusRequest proto.InternalMessageInfo

func (m *GetToolkitStatusRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

//
//GetToolkitStatus返回
type GetToolkitStatusResponse struct {
	//
	//状态
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled" form:"enabled"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetToolkitStatusResponse) Reset()         { *m = GetToolkitStatusResponse{} }
func (m *GetToolkitStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetToolkitStatusResponse) ProtoMessage()    {}
func (*GetToolkitStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c3eb14039f57f44, []int{1}
}
func (m *GetToolkitStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetToolkitStatusResponse.Unmarshal(m, b)
}
func (m *GetToolkitStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetToolkitStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetToolkitStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetToolkitStatusResponse.Merge(m, src)
}
func (m *GetToolkitStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetToolkitStatusResponse.Size(m)
}
func (m *GetToolkitStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetToolkitStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetToolkitStatusResponse proto.InternalMessageInfo

func (m *GetToolkitStatusResponse) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

//
//GetToolkitStatusApi返回
type GetToolkitStatusResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *GetToolkitStatusResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetToolkitStatusResponseWrapper) Reset()         { *m = GetToolkitStatusResponseWrapper{} }
func (m *GetToolkitStatusResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*GetToolkitStatusResponseWrapper) ProtoMessage()    {}
func (*GetToolkitStatusResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c3eb14039f57f44, []int{2}
}
func (m *GetToolkitStatusResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetToolkitStatusResponseWrapper.Unmarshal(m, b)
}
func (m *GetToolkitStatusResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetToolkitStatusResponseWrapper.Marshal(b, m, deterministic)
}
func (m *GetToolkitStatusResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetToolkitStatusResponseWrapper.Merge(m, src)
}
func (m *GetToolkitStatusResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_GetToolkitStatusResponseWrapper.Size(m)
}
func (m *GetToolkitStatusResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetToolkitStatusResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GetToolkitStatusResponseWrapper proto.InternalMessageInfo

func (m *GetToolkitStatusResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetToolkitStatusResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *GetToolkitStatusResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetToolkitStatusResponseWrapper) GetData() *GetToolkitStatusResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetToolkitStatusRequest)(nil), "toolkit.GetToolkitStatusRequest")
	proto.RegisterType((*GetToolkitStatusResponse)(nil), "toolkit.GetToolkitStatusResponse")
	proto.RegisterType((*GetToolkitStatusResponseWrapper)(nil), "toolkit.GetToolkitStatusResponseWrapper")
}

func init() { proto.RegisterFile("get_toolkit_status.proto", fileDescriptor_2c3eb14039f57f44) }

var fileDescriptor_2c3eb14039f57f44 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xa9, 0x76, 0x6e, 0xa6, 0xe2, 0x24, 0x82, 0x06, 0x5f, 0x32, 0x23, 0xc8, 0x1e, 0xb4,
	0x05, 0x7d, 0x11, 0x1f, 0x0b, 0xfe, 0x7d, 0x8c, 0x82, 0x8f, 0x23, 0x6d, 0xb3, 0x5a, 0xed, 0x7a,
	0x6b, 0x9a, 0x82, 0x9f, 0xb6, 0x9f, 0x41, 0xfa, 0x09, 0xa4, 0x49, 0xa7, 0x83, 0xb1, 0xa7, 0xf6,
	0xde, 0x73, 0xce, 0x8f, 0x13, 0x2e, 0x22, 0xa9, 0xd4, 0x33, 0x0d, 0x90, 0x7f, 0x66, 0x7a, 0x56,
	0x69, 0xa1, 0xeb, 0xca, 0x2f, 0x15, 0x68, 0xc0, 0xc3, 0x7e, 0x7b, 0x72, 0x99, 0x66, 0xfa, 0xbd,
	0x8e, 0xfc, 0x18, 0x16, 0x41, 0x0a, 0x29, 0x04, 0x46, 0x8f, 0xea, 0xb9, 0x99, 0xcc, 0x60, 0xfe,
	0x6c, 0x8e, 0x3d, 0xa3, 0xe3, 0x07, 0xa9, 0x5f, 0x6d, 0xf8, 0xc5, 0x10, 0xb9, 0xfc, 0xaa, 0x65,
	0xa5, 0x71, 0x80, 0x46, 0x10, 0x7d, 0xc8, 0x58, 0x3f, 0x25, 0xc4, 0x99, 0x38, 0xd3, 0xdd, 0xf0,
	0xb0, 0x6d, 0xe8, 0x78, 0x0e, 0x6a, 0x71, 0xcb, 0x96, 0x0a, 0xe3, 0x7f, 0x26, 0xf6, 0x88, 0xc8,
	0x3a, 0xab, 0x2a, 0xa1, 0xa8, 0x24, 0xbe, 0x40, 0x43, 0x59, 0x88, 0x28, 0x97, 0x96, 0x35, 0x0a,
	0x71, 0xdb, 0xd0, 0x7d, 0xcb, 0xea, 0x05, 0xc6, 0x97, 0x16, 0xf6, 0xe3, 0x20, 0xba, 0x09, 0xf5,
	0xa6, 0x44, 0x59, 0x4a, 0x85, 0xcf, 0x90, 0x1b, 0x43, 0x22, 0x0d, 0x6e, 0x10, 0x8e, 0xdb, 0x86,
	0x7a, 0x16, 0xd7, 0x6d, 0x19, 0x37, 0x22, 0xbe, 0x41, 0x5e, 0xf7, 0xbd, 0xfb, 0x2e, 0x73, 0x91,
	0x15, 0x64, 0xcb, 0x3c, 0xe3, 0xa8, 0x6d, 0x28, 0xfe, 0xf7, 0xf6, 0x22, 0xe3, 0xab, 0x56, 0x7c,
	0x8e, 0x06, 0x52, 0x29, 0x50, 0x64, 0xdb, 0x64, 0x0e, 0xda, 0x86, 0xee, 0xf5, 0x75, 0xbb, 0x35,
	0xe3, 0x56, 0xc6, 0xf7, 0xc8, 0x4d, 0x84, 0x16, 0xc4, 0x9d, 0x38, 0x53, 0xef, 0xea, 0xd4, 0xef,
	0xef, 0xe0, 0x6f, 0xaa, 0xbf, 0xda, 0xb4, 0x0b, 0x32, 0x6e, 0xf2, 0xd1, 0x8e, 0xb9, 0xc7, 0xf5,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xc5, 0x70, 0x07, 0xe3, 0x01, 0x00, 0x00,
}
