// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: giraffe_service.proto

package business

import (
	context "context"
	fmt "fmt"
	giraffe_micro "github.com/easyops-cn/giraffe-micro"
	go_proto_giraffe "github.com/easyops-cn/go-proto-giraffe"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ = io.EOF
var _ context.Context
var _ giraffe_micro.Client
var _ go_proto_giraffe.Contract

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = giraffe_micro.SupportPackageIsVersion4 // please upgrade the giraffe_micro package

// Client is the client API for business service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Client interface {
	GetAppDeployInstance(ctx context.Context, in *GetAppDeployInstanceRequest) (*GetAppDeployInstanceResponse, error)
	GetAppDeployInfo(ctx context.Context, in *GetAppDeployInfoRequest) (*GetAppDeployInfoResponse, error)
}

type client struct {
	c giraffe_micro.Client
}

func NewClient(c giraffe_micro.Client) Client {
	return &client{
		c: c,
	}
}

func (c *client) GetAppDeployInstance(ctx context.Context, in *GetAppDeployInstanceRequest) (*GetAppDeployInstanceResponse, error) {
	out := new(GetAppDeployInstanceResponse)
	err := c.c.Invoke(ctx, _GetAppDeployInstanceMethodDesc, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *client) GetAppDeployInfo(ctx context.Context, in *GetAppDeployInfoRequest) (*GetAppDeployInfoResponse, error) {
	out := new(GetAppDeployInfoResponse)
	err := c.c.Invoke(ctx, _GetAppDeployInfoMethodDesc, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Service is the server API for business service.
type Service interface {
	GetAppDeployInstance(context.Context, *GetAppDeployInstanceRequest) (*GetAppDeployInstanceResponse, error)
	GetAppDeployInfo(context.Context, *GetAppDeployInfoRequest) (*GetAppDeployInfoResponse, error)
}

func _GetAppDeployInstanceEndpoint(s Service) giraffe_micro.UnaryEndpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetAppDeployInstance(ctx, req.(*GetAppDeployInstanceRequest))
	}
}

func _GetAppDeployInfoEndpoint(s Service) giraffe_micro.UnaryEndpoint {
	return func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetAppDeployInfo(ctx, req.(*GetAppDeployInfoRequest))
	}
}

func RegisterService(s giraffe_micro.Server, srv Service) {
	s.RegisterUnaryEndpoint(_GetAppDeployInstanceMethodDesc, _GetAppDeployInstanceEndpoint(srv))
	s.RegisterUnaryEndpoint(_GetAppDeployInfoMethodDesc, _GetAppDeployInfoEndpoint(srv))
}

// Method Description
var _GetAppDeployInstanceMethodDesc = &giraffe_micro.MethodDesc{
	Contract: &go_proto_giraffe.Contract{
		Name:    "easyops.api.architecture_view.business.GetAppDeployInstance",
		Version: "1.0",
	},
	ServiceName:  "business.rpc",
	MethodName:   "GetAppDeployInstance",
	RequestType:  (*GetAppDeployInstanceRequest)(nil),
	ResponseType: (*GetAppDeployInstanceResponse)(nil),
	HttpRule: &go_proto_giraffe.HttpRule{
		Pattern: &go_proto_giraffe.HttpRule_Get{
			Get: "/api/architecture_view/v1/apps/instance",
		},
		Body:         "",
		ResponseBody: "data",
	},
}

var _GetAppDeployInfoMethodDesc = &giraffe_micro.MethodDesc{
	Contract: &go_proto_giraffe.Contract{
		Name:    "easyops.api.architecture_view.business.GetAppDeployInfo",
		Version: "1.0",
	},
	ServiceName:  "business.rpc",
	MethodName:   "GetAppDeployInfo",
	RequestType:  (*GetAppDeployInfoRequest)(nil),
	ResponseType: (*GetAppDeployInfoResponse)(nil),
	HttpRule: &go_proto_giraffe.HttpRule{
		Pattern: &go_proto_giraffe.HttpRule_Get{
			Get: "/api/architecture_view/v1/business/:businessId/deploy",
		},
		Body:         "",
		ResponseBody: "data",
	},
}
