// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data_name_list_handler.proto

package date_name_list_handler

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	translate_rule "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/translate_rule"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//DataNameListHandler请求
type DataNameListHandlerRequest struct {
	//
	//策略名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" form:"name"`
	//
	//page
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" form:"page"`
	//
	//page_size
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//是否查询关系
	Relate               bool     `protobuf:"varint,4,opt,name=relate,proto3" json:"relate" form:"relate"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataNameListHandlerRequest) Reset()         { *m = DataNameListHandlerRequest{} }
func (m *DataNameListHandlerRequest) String() string { return proto.CompactTextString(m) }
func (*DataNameListHandlerRequest) ProtoMessage()    {}
func (*DataNameListHandlerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f9dfe0aee89d34, []int{0}
}
func (m *DataNameListHandlerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNameListHandlerRequest.Unmarshal(m, b)
}
func (m *DataNameListHandlerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNameListHandlerRequest.Marshal(b, m, deterministic)
}
func (m *DataNameListHandlerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNameListHandlerRequest.Merge(m, src)
}
func (m *DataNameListHandlerRequest) XXX_Size() int {
	return xxx_messageInfo_DataNameListHandlerRequest.Size(m)
}
func (m *DataNameListHandlerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNameListHandlerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataNameListHandlerRequest proto.InternalMessageInfo

func (m *DataNameListHandlerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataNameListHandlerRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *DataNameListHandlerRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *DataNameListHandlerRequest) GetRelate() bool {
	if m != nil {
		return m.Relate
	}
	return false
}

//
//DataNameListHandler返回
type DataNameListHandlerResponse struct {
	//
	//描述
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description" form:"description"`
	//
	//数据类型
	DataType string `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type" form:"data_type"`
	//
	//数据名称
	DataName string `protobuf:"bytes,3,opt,name=data_name,json=dataName,proto3" json:"data_name" form:"data_name"`
	//
	//formats
	Formats []*DataNameListHandlerResponse_Formats `protobuf:"bytes,4,rep,name=formats,proto3" json:"formats" form:"formats"`
	//
	//翻译规则
	TranslateRules       []*translate_rule.TransalteRule `protobuf:"bytes,5,rep,name=translate_rules,json=translateRules,proto3" json:"translate_rules" form:"translate_rules"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *DataNameListHandlerResponse) Reset()         { *m = DataNameListHandlerResponse{} }
func (m *DataNameListHandlerResponse) String() string { return proto.CompactTextString(m) }
func (*DataNameListHandlerResponse) ProtoMessage()    {}
func (*DataNameListHandlerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f9dfe0aee89d34, []int{1}
}
func (m *DataNameListHandlerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNameListHandlerResponse.Unmarshal(m, b)
}
func (m *DataNameListHandlerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNameListHandlerResponse.Marshal(b, m, deterministic)
}
func (m *DataNameListHandlerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNameListHandlerResponse.Merge(m, src)
}
func (m *DataNameListHandlerResponse) XXX_Size() int {
	return xxx_messageInfo_DataNameListHandlerResponse.Size(m)
}
func (m *DataNameListHandlerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNameListHandlerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataNameListHandlerResponse proto.InternalMessageInfo

func (m *DataNameListHandlerResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataNameListHandlerResponse) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *DataNameListHandlerResponse) GetDataName() string {
	if m != nil {
		return m.DataName
	}
	return ""
}

func (m *DataNameListHandlerResponse) GetFormats() []*DataNameListHandlerResponse_Formats {
	if m != nil {
		return m.Formats
	}
	return nil
}

func (m *DataNameListHandlerResponse) GetTranslateRules() []*translate_rule.TransalteRule {
	if m != nil {
		return m.TranslateRules
	}
	return nil
}

type DataNameListHandlerResponse_Formats struct {
	//
	//fields
	Fields               []*DataNameListHandlerResponse_Formats_Fields `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields" form:"fields"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *DataNameListHandlerResponse_Formats) Reset()         { *m = DataNameListHandlerResponse_Formats{} }
func (m *DataNameListHandlerResponse_Formats) String() string { return proto.CompactTextString(m) }
func (*DataNameListHandlerResponse_Formats) ProtoMessage()    {}
func (*DataNameListHandlerResponse_Formats) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f9dfe0aee89d34, []int{1, 0}
}
func (m *DataNameListHandlerResponse_Formats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNameListHandlerResponse_Formats.Unmarshal(m, b)
}
func (m *DataNameListHandlerResponse_Formats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNameListHandlerResponse_Formats.Marshal(b, m, deterministic)
}
func (m *DataNameListHandlerResponse_Formats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNameListHandlerResponse_Formats.Merge(m, src)
}
func (m *DataNameListHandlerResponse_Formats) XXX_Size() int {
	return xxx_messageInfo_DataNameListHandlerResponse_Formats.Size(m)
}
func (m *DataNameListHandlerResponse_Formats) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNameListHandlerResponse_Formats.DiscardUnknown(m)
}

var xxx_messageInfo_DataNameListHandlerResponse_Formats proto.InternalMessageInfo

func (m *DataNameListHandlerResponse_Formats) GetFields() []*DataNameListHandlerResponse_Formats_Fields {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DataNameListHandlerResponse_Formats_Fields struct {
	//
	//类型
	FieldType string `protobuf:"bytes,1,opt,name=field_type,json=fieldType,proto3" json:"field_type" form:"field_type"`
	//
	//描述
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description" form:"description"`
	//
	//名称
	FieldName string `protobuf:"bytes,3,opt,name=field_name,json=fieldName,proto3" json:"field_name" form:"field_name"`
	//
	//值类型
	FieldValueType string `protobuf:"bytes,4,opt,name=field_value_type,json=fieldValueType,proto3" json:"field_value_type" form:"field_value_type"`
	//
	//预告值
	PriviewValue string `protobuf:"bytes,5,opt,name=priview_value,json=priviewValue,proto3" json:"priview_value" form:"priview_value"`
	//
	//期限
	StatPeriod int32 `protobuf:"varint,6,opt,name=stat_period,json=statPeriod,proto3" json:"stat_period" form:"stat_period"`
	//
	//类型
	StatType string `protobuf:"bytes,7,opt,name=stat_type,json=statType,proto3" json:"stat_type" form:"stat_type"`
	//
	//单元
	Unit string `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit" form:"unit"`
	//
	//列名
	ColumnName           string   `protobuf:"bytes,9,opt,name=column_name,json=columnName,proto3" json:"column_name" form:"column_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataNameListHandlerResponse_Formats_Fields) Reset() {
	*m = DataNameListHandlerResponse_Formats_Fields{}
}
func (m *DataNameListHandlerResponse_Formats_Fields) String() string {
	return proto.CompactTextString(m)
}
func (*DataNameListHandlerResponse_Formats_Fields) ProtoMessage() {}
func (*DataNameListHandlerResponse_Formats_Fields) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f9dfe0aee89d34, []int{1, 0, 0}
}
func (m *DataNameListHandlerResponse_Formats_Fields) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNameListHandlerResponse_Formats_Fields.Unmarshal(m, b)
}
func (m *DataNameListHandlerResponse_Formats_Fields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNameListHandlerResponse_Formats_Fields.Marshal(b, m, deterministic)
}
func (m *DataNameListHandlerResponse_Formats_Fields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNameListHandlerResponse_Formats_Fields.Merge(m, src)
}
func (m *DataNameListHandlerResponse_Formats_Fields) XXX_Size() int {
	return xxx_messageInfo_DataNameListHandlerResponse_Formats_Fields.Size(m)
}
func (m *DataNameListHandlerResponse_Formats_Fields) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNameListHandlerResponse_Formats_Fields.DiscardUnknown(m)
}

var xxx_messageInfo_DataNameListHandlerResponse_Formats_Fields proto.InternalMessageInfo

func (m *DataNameListHandlerResponse_Formats_Fields) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetFieldValueType() string {
	if m != nil {
		return m.FieldValueType
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetPriviewValue() string {
	if m != nil {
		return m.PriviewValue
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetStatPeriod() int32 {
	if m != nil {
		return m.StatPeriod
	}
	return 0
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetStatType() string {
	if m != nil {
		return m.StatType
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *DataNameListHandlerResponse_Formats_Fields) GetColumnName() string {
	if m != nil {
		return m.ColumnName
	}
	return ""
}

//
//DataNameListHandlerApi返回
type DataNameListHandlerResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *DataNameListHandlerResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DataNameListHandlerResponseWrapper) Reset()         { *m = DataNameListHandlerResponseWrapper{} }
func (m *DataNameListHandlerResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*DataNameListHandlerResponseWrapper) ProtoMessage()    {}
func (*DataNameListHandlerResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f9dfe0aee89d34, []int{2}
}
func (m *DataNameListHandlerResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNameListHandlerResponseWrapper.Unmarshal(m, b)
}
func (m *DataNameListHandlerResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNameListHandlerResponseWrapper.Marshal(b, m, deterministic)
}
func (m *DataNameListHandlerResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNameListHandlerResponseWrapper.Merge(m, src)
}
func (m *DataNameListHandlerResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_DataNameListHandlerResponseWrapper.Size(m)
}
func (m *DataNameListHandlerResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNameListHandlerResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_DataNameListHandlerResponseWrapper proto.InternalMessageInfo

func (m *DataNameListHandlerResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DataNameListHandlerResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *DataNameListHandlerResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DataNameListHandlerResponseWrapper) GetData() *DataNameListHandlerResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*DataNameListHandlerRequest)(nil), "date_name_list_handler.DataNameListHandlerRequest")
	proto.RegisterType((*DataNameListHandlerResponse)(nil), "date_name_list_handler.DataNameListHandlerResponse")
	proto.RegisterType((*DataNameListHandlerResponse_Formats)(nil), "date_name_list_handler.DataNameListHandlerResponse.Formats")
	proto.RegisterType((*DataNameListHandlerResponse_Formats_Fields)(nil), "date_name_list_handler.DataNameListHandlerResponse.Formats.Fields")
	proto.RegisterType((*DataNameListHandlerResponseWrapper)(nil), "date_name_list_handler.DataNameListHandlerResponseWrapper")
}

func init() { proto.RegisterFile("data_name_list_handler.proto", fileDescriptor_95f9dfe0aee89d34) }

var fileDescriptor_95f9dfe0aee89d34 = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0x13, 0x3d,
	0x10, 0x56, 0x9a, 0x8f, 0x26, 0x4e, 0x3f, 0x57, 0x7d, 0xfb, 0xae, 0xd2, 0xf7, 0xd5, 0x46, 0xae,
	0x84, 0xc2, 0xa1, 0x1b, 0xd1, 0x22, 0x81, 0x40, 0x5c, 0x22, 0x5a, 0x71, 0x40, 0x08, 0x99, 0x0a,
	0xb8, 0xa0, 0xc8, 0xc9, 0xba, 0xa9, 0xa5, 0xcd, 0x7a, 0xb1, 0xbd, 0x85, 0xf6, 0x8e, 0xc4, 0x0f,
	0xe3, 0x77, 0xec, 0x8f, 0xd8, 0x1b, 0x17, 0x84, 0x3c, 0x5e, 0x52, 0x77, 0x1b, 0x55, 0x08, 0x4e,
	0xeb, 0x99, 0xe7, 0x99, 0x99, 0x67, 0x3c, 0xb3, 0x46, 0xff, 0x45, 0x54, 0xd3, 0x71, 0x42, 0xe7,
	0x6c, 0x1c, 0x73, 0xa5, 0xc7, 0xe7, 0x34, 0x89, 0x62, 0x26, 0xc3, 0x54, 0x0a, 0x2d, 0xbc, 0xdd,
	0x88, 0x6a, 0x76, 0x1b, 0xed, 0x1d, 0xcc, 0xb8, 0x3e, 0xcf, 0x26, 0xe1, 0x54, 0xcc, 0x87, 0x33,
	0x31, 0x13, 0x43, 0xa0, 0x4f, 0xb2, 0x33, 0xb0, 0xc0, 0x80, 0x93, 0x4d, 0xd3, 0xfb, 0x30, 0x13,
	0x21, 0xa3, 0xea, 0x52, 0xa4, 0x2a, 0x8c, 0xc5, 0x94, 0xc6, 0xc3, 0xa9, 0x48, 0xb4, 0xa4, 0x53,
	0xad, 0x6c, 0xa4, 0x64, 0xa9, 0x38, 0x98, 0x8b, 0x88, 0xc5, 0x6a, 0x58, 0x12, 0x87, 0x60, 0x0e,
	0xb5, 0xa4, 0x89, 0x8a, 0x8d, 0x0a, 0x99, 0xc5, 0xac, 0x62, 0xda, 0xf4, 0xf8, 0x5b, 0x0d, 0xf5,
	0x9e, 0x53, 0x4d, 0x5f, 0xd1, 0x39, 0x7b, 0xc9, 0x95, 0x7e, 0x61, 0x55, 0x12, 0xf6, 0x31, 0x63,
	0x4a, 0x7b, 0xfb, 0xa8, 0x61, 0x3a, 0xf0, 0x6b, 0xfd, 0xda, 0xa0, 0x33, 0xda, 0x2c, 0xf2, 0xa0,
	0x7b, 0x26, 0xe4, 0xfc, 0x09, 0x36, 0x5e, 0x4c, 0x00, 0x34, 0xa4, 0x94, 0xce, 0x98, 0xbf, 0xd2,
	0xaf, 0x0d, 0x9a, 0x2e, 0xc9, 0x78, 0x31, 0x01, 0xd0, 0x7b, 0x80, 0x3a, 0xe6, 0x3b, 0x56, 0xfc,
	0x8a, 0xf9, 0x75, 0x60, 0xee, 0x14, 0x79, 0xb0, 0x75, 0xcd, 0x04, 0x08, 0x93, 0xb6, 0x39, 0xbf,
	0xe1, 0x57, 0xcc, 0xbb, 0x8f, 0x5a, 0x92, 0x19, 0xc1, 0x7e, 0xa3, 0x5f, 0x1b, 0xb4, 0x47, 0xdb,
	0x45, 0x1e, 0xac, 0x5b, 0xbe, 0xf5, 0x63, 0x52, 0x12, 0xf0, 0xd7, 0x36, 0xda, 0x5b, 0xda, 0x86,
	0x4a, 0x45, 0xa2, 0x98, 0xf7, 0x18, 0x75, 0x23, 0xa6, 0xa6, 0x92, 0xa7, 0x9a, 0x8b, 0xa4, 0x6c,
	0x67, 0xb7, 0xc8, 0x03, 0xcf, 0xe6, 0x73, 0x40, 0x4c, 0x5c, 0xaa, 0xd1, 0x0d, 0x63, 0xd6, 0x97,
	0xa9, 0xed, 0xb0, 0xe3, 0xea, 0x5e, 0x40, 0x98, 0xb4, 0xcd, 0xf9, 0xf4, 0x32, 0x65, 0x8b, 0x10,
	0xb8, 0xb9, 0xfa, 0xd2, 0x10, 0x7b, 0x7d, 0x10, 0x62, 0x24, 0x7b, 0x1c, 0xad, 0x1a, 0x94, 0x6a,
	0xe5, 0x37, 0xfa, 0xf5, 0x41, 0xf7, 0xf0, 0x69, 0xb8, 0x7c, 0x7d, 0xc2, 0x3b, 0xba, 0x0c, 0x4f,
	0x6c, 0x8a, 0x91, 0x57, 0xe4, 0xc1, 0x86, 0xad, 0x56, 0x66, 0xc5, 0xe4, 0x57, 0x7e, 0x6f, 0x82,
	0x36, 0x6f, 0x6e, 0x82, 0xf2, 0x9b, 0x50, 0xf2, 0xff, 0xb0, 0xb2, 0x21, 0xa7, 0xc6, 0xa4, 0xb1,
	0x66, 0x24, 0x8b, 0xd9, 0xa8, 0x57, 0xe4, 0xc1, 0xae, 0x4d, 0x5a, 0x89, 0xc7, 0x64, 0x63, 0xe1,
	0x31, 0x54, 0xd5, 0xfb, 0xde, 0x40, 0xab, 0xa5, 0x18, 0x6f, 0x8e, 0x5a, 0x67, 0x9c, 0xc5, 0x91,
	0xf2, 0x6b, 0x50, 0x66, 0xf4, 0x17, 0x9d, 0x85, 0x27, 0x90, 0xc9, 0xdd, 0x04, 0x9b, 0x1b, 0x93,
	0xb2, 0x48, 0xef, 0x47, 0x1d, 0xb5, 0x2c, 0xcb, 0x7b, 0x88, 0x10, 0x38, 0xed, 0xec, 0xec, 0xcc,
	0xff, 0x29, 0xf2, 0x60, 0xdb, 0x89, 0x2c, 0x87, 0xd7, 0x01, 0x03, 0xa6, 0x57, 0x59, 0x95, 0x95,
	0xdf, 0x5f, 0x95, 0x45, 0x3d, 0x67, 0xf0, 0xb7, 0xea, 0xd9, 0xc9, 0xdb, 0x7a, 0x30, 0xfa, 0x63,
	0xb4, 0x65, 0x91, 0x0b, 0x1a, 0x67, 0xcc, 0x6a, 0x6d, 0x40, 0xec, 0x5e, 0x91, 0x07, 0xff, 0xba,
	0xb1, 0xd7, 0x0c, 0x4c, 0x36, 0xc0, 0xf5, 0xd6, 0x78, 0x40, 0xf6, 0x33, 0xb4, 0x9e, 0x4a, 0x7e,
	0xc1, 0xd9, 0x27, 0x4b, 0xf3, 0x9b, 0x90, 0xc3, 0x2f, 0xf2, 0x60, 0xa7, 0xfc, 0xc7, 0x5c, 0x18,
	0x93, 0xb5, 0xd2, 0x86, 0x14, 0xde, 0x23, 0xd4, 0x55, 0x9a, 0xea, 0x71, 0xca, 0x24, 0x17, 0x91,
	0xdf, 0x82, 0x1f, 0xd4, 0xe9, 0xda, 0x01, 0x31, 0x41, 0xc6, 0x7a, 0x0d, 0x86, 0x59, 0x76, 0xc0,
	0x40, 0xf7, 0x6a, 0x75, 0xd9, 0x17, 0x10, 0x26, 0x6d, 0x73, 0x06, 0xa9, 0xfb, 0xa8, 0x91, 0x25,
	0x5c, 0xfb, 0xed, 0xea, 0xa3, 0x62, 0xbc, 0x98, 0x00, 0x68, 0x04, 0x4d, 0x45, 0x9c, 0xcd, 0x13,
	0x7b, 0x9b, 0x9d, 0xea, 0x18, 0x1c, 0x10, 0x13, 0x64, 0x2d, 0x73, 0x9f, 0xf8, 0xcb, 0x0a, 0xc2,
	0x77, 0xac, 0xd2, 0x3b, 0x49, 0xd3, 0x94, 0x49, 0x23, 0x62, 0x2a, 0x22, 0xbb, 0x16, 0x37, 0x1e,
	0x2d, 0xe3, 0xc5, 0x04, 0x40, 0xb3, 0x0b, 0xe6, 0x7b, 0xfc, 0x39, 0x8d, 0x29, 0x5f, 0xb2, 0x0b,
	0x0e, 0x88, 0x89, 0x4b, 0xf5, 0xee, 0xa1, 0x26, 0x93, 0x52, 0xc8, 0x72, 0x0d, 0xb6, 0x8a, 0x3c,
	0x58, 0xb3, 0x31, 0xe0, 0xc6, 0xc4, 0xc2, 0xde, 0x7b, 0xd4, 0x30, 0x8f, 0x00, 0x4c, 0xbc, 0x7b,
	0x78, 0xf4, 0x07, 0xff, 0x86, 0xab, 0xdd, 0xa4, 0xc2, 0x04, 0x32, 0x4e, 0x5a, 0xf0, 0xc0, 0x1f,
	0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x89, 0xe1, 0xa6, 0xa6, 0x06, 0x00, 0x00,
}
