// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: list_support_infom.proto

package custom_sender

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//ListSupportInform返回
type ListSupportInformResponse struct {
	//
	//数据内容
	Data []*ListSupportInformResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data" form:"data"`
	//
	//页码
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" form:"page"`
	//
	//每页记录数
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size" form:"page_size"`
	//
	//记录总数
	Tatal int32 `protobuf:"varint,4,opt,name=tatal,proto3" json:"tatal" form:"tatal"`
	//
	//请求错误信息
	Msg string `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg" form:"msg"`
	//
	//请求返回码
	Code                 int32    `protobuf:"varint,6,opt,name=code,proto3" json:"code" form:"code"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSupportInformResponse) Reset()         { *m = ListSupportInformResponse{} }
func (m *ListSupportInformResponse) String() string { return proto.CompactTextString(m) }
func (*ListSupportInformResponse) ProtoMessage()    {}
func (*ListSupportInformResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_980446af05d1a1f3, []int{0}
}
func (m *ListSupportInformResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSupportInformResponse.Unmarshal(m, b)
}
func (m *ListSupportInformResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSupportInformResponse.Marshal(b, m, deterministic)
}
func (m *ListSupportInformResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSupportInformResponse.Merge(m, src)
}
func (m *ListSupportInformResponse) XXX_Size() int {
	return xxx_messageInfo_ListSupportInformResponse.Size(m)
}
func (m *ListSupportInformResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSupportInformResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSupportInformResponse proto.InternalMessageInfo

func (m *ListSupportInformResponse) GetData() []*ListSupportInformResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListSupportInformResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSupportInformResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListSupportInformResponse) GetTatal() int32 {
	if m != nil {
		return m.Tatal
	}
	return 0
}

func (m *ListSupportInformResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListSupportInformResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ListSupportInformResponse_Data struct {
	//
	//关联的cmdb用户对象字段
	ColOfCmdbUserObject string `protobuf:"bytes,1,opt,name=col_of_cmdb_user_object,json=colOfCmdbUserObject,proto3" json:"col_of_cmdb_user_object" form:"col_of_cmdb_user_object"`
	//
	//是否启用
	Enable bool `protobuf:"varint,2,opt,name=enable,proto3" json:"enable" form:"enable"`
	//
	//通知插件名称
	PluginName string `protobuf:"bytes,3,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name" form:"plugin_name"`
	//
	//通知方式描述
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description" form:"description"`
	//
	//通知方式名称
	InformType           string   `protobuf:"bytes,5,opt,name=inform_type,json=informType,proto3" json:"inform_type" form:"inform_type"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSupportInformResponse_Data) Reset()         { *m = ListSupportInformResponse_Data{} }
func (m *ListSupportInformResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ListSupportInformResponse_Data) ProtoMessage()    {}
func (*ListSupportInformResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_980446af05d1a1f3, []int{0, 0}
}
func (m *ListSupportInformResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSupportInformResponse_Data.Unmarshal(m, b)
}
func (m *ListSupportInformResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSupportInformResponse_Data.Marshal(b, m, deterministic)
}
func (m *ListSupportInformResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSupportInformResponse_Data.Merge(m, src)
}
func (m *ListSupportInformResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ListSupportInformResponse_Data.Size(m)
}
func (m *ListSupportInformResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSupportInformResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ListSupportInformResponse_Data proto.InternalMessageInfo

func (m *ListSupportInformResponse_Data) GetColOfCmdbUserObject() string {
	if m != nil {
		return m.ColOfCmdbUserObject
	}
	return ""
}

func (m *ListSupportInformResponse_Data) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *ListSupportInformResponse_Data) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *ListSupportInformResponse_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListSupportInformResponse_Data) GetInformType() string {
	if m != nil {
		return m.InformType
	}
	return ""
}

//
//ListSupportInformApi返回
type ListSupportInformResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *ListSupportInformResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListSupportInformResponseWrapper) Reset()         { *m = ListSupportInformResponseWrapper{} }
func (m *ListSupportInformResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*ListSupportInformResponseWrapper) ProtoMessage()    {}
func (*ListSupportInformResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_980446af05d1a1f3, []int{1}
}
func (m *ListSupportInformResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSupportInformResponseWrapper.Unmarshal(m, b)
}
func (m *ListSupportInformResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSupportInformResponseWrapper.Marshal(b, m, deterministic)
}
func (m *ListSupportInformResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSupportInformResponseWrapper.Merge(m, src)
}
func (m *ListSupportInformResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_ListSupportInformResponseWrapper.Size(m)
}
func (m *ListSupportInformResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSupportInformResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ListSupportInformResponseWrapper proto.InternalMessageInfo

func (m *ListSupportInformResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ListSupportInformResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *ListSupportInformResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ListSupportInformResponseWrapper) GetData() *ListSupportInformResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListSupportInformResponse)(nil), "custom_sender.ListSupportInformResponse")
	proto.RegisterType((*ListSupportInformResponse_Data)(nil), "custom_sender.ListSupportInformResponse.Data")
	proto.RegisterType((*ListSupportInformResponseWrapper)(nil), "custom_sender.ListSupportInformResponseWrapper")
}

func init() { proto.RegisterFile("list_support_infom.proto", fileDescriptor_980446af05d1a1f3) }

var fileDescriptor_980446af05d1a1f3 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0xba, 0x1f, 0xea, 0x7a, 0x29, 0x14, 0x83, 0x20, 0xf4, 0x40, 0x56, 0x46, 0x42, 0xcb,
	0xa1, 0xa9, 0x28, 0x07, 0x10, 0xc7, 0x05, 0x0e, 0x48, 0x40, 0x25, 0x17, 0x04, 0x37, 0xcb, 0x49,
	0x9c, 0x60, 0x14, 0xc7, 0x96, 0xed, 0x48, 0xd0, 0x3f, 0xc6, 0xbf, 0xc9, 0x6f, 0x40, 0x39, 0x71,
	0x44, 0xb6, 0x03, 0xcd, 0x22, 0x16, 0xf5, 0x14, 0xcf, 0x7b, 0x6f, 0xc6, 0x93, 0xe7, 0x19, 0x10,
	0xd7, 0xdc, 0x58, 0x62, 0x5a, 0xa5, 0xa4, 0xb6, 0x84, 0x37, 0xa5, 0x14, 0xa9, 0xd2, 0xd2, 0x4a,
	0x78, 0x90, 0xb7, 0xc6, 0x4a, 0x41, 0x0c, 0x6b, 0x0a, 0xa6, 0x8f, 0x8e, 0x2b, 0x6e, 0x3f, 0xb7,
	0x59, 0x9a, 0x4b, 0x71, 0x52, 0xc9, 0x4a, 0x9e, 0x78, 0x55, 0xd6, 0x96, 0x3e, 0xf2, 0x81, 0x3f,
	0x85, 0x6c, 0xf4, 0x63, 0x0a, 0xee, 0xbd, 0xe1, 0xc6, 0x9e, 0x87, 0xca, 0xaf, 0x9b, 0x52, 0x6a,
	0x81, 0x99, 0x51, 0xb2, 0x31, 0x0c, 0x62, 0x30, 0x2d, 0xa8, 0xa5, 0x71, 0xb4, 0x9a, 0xac, 0x97,
	0xa7, 0xc7, 0xe9, 0xd6, 0x55, 0xe9, 0xce, 0xbc, 0xf4, 0x25, 0xb5, 0x74, 0x73, 0xa3, 0xef, 0x92,
	0xa5, 0x83, 0x9f, 0x23, 0x57, 0x04, 0x61, 0x5f, 0x0b, 0x3e, 0x00, 0x53, 0x45, 0x2b, 0x16, 0xef,
	0xad, 0xa2, 0xf5, 0x6c, 0x2c, 0x72, 0x28, 0xc2, 0x9e, 0x84, 0x8f, 0xc1, 0xc2, 0x7d, 0x89, 0xe1,
	0x17, 0x2c, 0x9e, 0x78, 0xe5, 0xed, 0xbe, 0x4b, 0x0e, 0x2f, 0x95, 0x9e, 0x42, 0x78, 0xdf, 0x9d,
	0xcf, 0xf9, 0x05, 0x83, 0x0f, 0xc1, 0xcc, 0x52, 0x4b, 0xeb, 0x78, 0xea, 0xe5, 0x87, 0x7d, 0x97,
	0x5c, 0x0b, 0x72, 0x0f, 0x23, 0x1c, 0x68, 0xb8, 0x02, 0x13, 0x61, 0xaa, 0x78, 0xb6, 0x8a, 0xd6,
	0x8b, 0xcd, 0xf5, 0xbe, 0x4b, 0x40, 0x50, 0x09, 0x53, 0x21, 0xec, 0x28, 0xd7, 0x61, 0x2e, 0x0b,
	0x16, 0xcf, 0xff, 0xee, 0xd0, 0xa1, 0x08, 0x7b, 0xf2, 0xe8, 0xfb, 0x1e, 0x98, 0xba, 0xdf, 0x84,
	0x9f, 0xc0, 0xdd, 0x5c, 0xd6, 0x44, 0x96, 0x24, 0x17, 0x45, 0x46, 0x5a, 0xc3, 0x34, 0x91, 0xd9,
	0x17, 0x96, 0xdb, 0x38, 0xf2, 0x77, 0xa0, 0xbe, 0x4b, 0xee, 0xff, 0x2e, 0xf0, 0x4f, 0x21, 0xc2,
	0xb7, 0x72, 0x59, 0x9f, 0x95, 0x2f, 0x44, 0x91, 0x7d, 0x30, 0x4c, 0x9f, 0x79, 0x14, 0x3e, 0x02,
	0x73, 0xd6, 0xd0, 0xac, 0x0e, 0x5e, 0xed, 0x6f, 0x6e, 0xf6, 0x5d, 0x72, 0x10, 0x0a, 0x05, 0x1c,
	0xe1, 0x41, 0x00, 0x9f, 0x82, 0xa5, 0xaa, 0xdb, 0x8a, 0x37, 0xa4, 0xa1, 0x22, 0x38, 0xb6, 0xd8,
	0xdc, 0xe9, 0xbb, 0x04, 0x0e, 0x8e, 0x5d, 0x92, 0x08, 0x83, 0x10, 0xbd, 0xa3, 0x82, 0xc1, 0x67,
	0x60, 0x59, 0x30, 0x93, 0x6b, 0xae, 0x2c, 0x97, 0x8d, 0xf7, 0x6e, 0x2b, 0x71, 0x44, 0x22, 0x3c,
	0x96, 0xba, 0x2b, 0xb9, 0x7f, 0x75, 0x62, 0xbf, 0x29, 0x36, 0xf8, 0x39, 0xca, 0x1c, 0x91, 0x08,
	0x83, 0x10, 0xbd, 0x77, 0xc1, 0xcf, 0x08, 0xac, 0x76, 0x8e, 0xce, 0x47, 0x4d, 0x95, 0x62, 0xfa,
	0xcf, 0x1b, 0x44, 0xff, 0x79, 0x03, 0xd7, 0xbc, 0xfb, 0xbe, 0xfa, 0xaa, 0x6a, 0xca, 0x1b, 0xef,
	0xd2, 0x56, 0x0b, 0x23, 0x12, 0xe1, 0xb1, 0xd4, 0x0d, 0x0b, 0xd3, 0x5a, 0xea, 0xc1, 0xa9, 0xd1,
	0xb0, 0x78, 0x18, 0xe1, 0x40, 0xc3, 0xb7, 0xc3, 0x02, 0x38, 0x5f, 0x96, 0xa7, 0xeb, 0xab, 0x2e,
	0xc0, 0x8e, 0xd9, 0xcf, 0xe6, 0x7e, 0xe9, 0x9e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x45, 0x3c,
	0xbb, 0x33, 0xce, 0x03, 0x00, 0x00,
}
