// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: app_health_config_variable.proto

package monitor_config

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AppHealthConfigVariable) Validate() error {
	return nil
}
