// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: target_info.proto

package easy_flow

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "github.com/easyopsapis/easyops-api-go/protorepo-models/easyops/model/cmdb"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_TargetInfo_TargetId = regexp.MustCompile(`^[?a-zA-Z0-9]{8}-[?a-zA-Z0-9]{4}-[?a-zA-Z0-9]{4}-[?a-zA-Z0-9]{4}-[?a-zA-Z0-9]{12}$`)
var _regex_TargetInfo_InstanceId = regexp.MustCompile(`^[0-9a-z]{13}$`)

func (this *TargetInfo) Validate() error {
	if !_regex_TargetInfo_TargetId.MatchString(this.TargetId) {
		return github_com_mwitkow_go_proto_validators.FieldError("TargetId", fmt.Errorf(`value '%v' must be a string conforming to regex "^[?a-zA-Z0-9]{8}-[?a-zA-Z0-9]{4}-[?a-zA-Z0-9]{4}-[?a-zA-Z0-9]{4}-[?a-zA-Z0-9]{12}$"`, this.TargetId))
	}
	if !_regex_TargetInfo_InstanceId.MatchString(this.InstanceId) {
		return github_com_mwitkow_go_proto_validators.FieldError("InstanceId", fmt.Errorf(`value '%v' must be a string conforming to regex "^[0-9a-z]{13}$"`, this.InstanceId))
	}
	if this.Cluster != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Cluster); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Cluster", err)
		}
	}
	return nil
}
