// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_sqlpkg_dbtask_detail.proto

package dbtask

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
	regexp "regexp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_GetSQLPackageDBTaskDetailRequest_DbTaskId = regexp.MustCompile(`^[0-9a-fA-F]{24}$`)

func (this *GetSQLPackageDBTaskDetailRequest) Validate() error {
	if !_regex_GetSQLPackageDBTaskDetailRequest_DbTaskId.MatchString(this.DbTaskId) {
		return github_com_mwitkow_go_proto_validators.FieldError("DbTaskId", fmt.Errorf(`value '%v' must be a string conforming to regex "^[0-9a-fA-F]{24}$"`, this.DbTaskId))
	}
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse) Validate() error {
	for _, item := range this.BackupTask {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("BackupTask", err)
			}
		}
	}
	for _, item := range this.ChangeTask {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ChangeTask", err)
			}
		}
	}
	for _, item := range this.CheckTask {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("CheckTask", err)
			}
		}
	}
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_BackupTask) Validate() error {
	for _, item := range this.Result {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
			}
		}
	}
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_BackupTask_Result) Validate() error {
	for _, item := range this.Variables {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Variables", err)
			}
		}
	}
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_BackupTask_Result_Variables) Validate() error {
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_ChangeTask) Validate() error {
	for _, item := range this.Result {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
			}
		}
	}
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_ChangeTask_Result) Validate() error {
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_CheckTask) Validate() error {
	for _, item := range this.Result {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Result", err)
			}
		}
	}
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponse_CheckTask_Result) Validate() error {
	return nil
}
func (this *GetSQLPackageDBTaskDetailResponseWrapper) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
