// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: get_custom_dbtask_rollbackinfo.proto

package dbtask

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//GetCustomDBTaskRollbackInfo请求
type GetCustomDBTaskRollbackInfoRequest struct {
	//
	//任务ID
	DbTaskId             string   `protobuf:"bytes,1,opt,name=dbTaskId,proto3" json:"dbTaskId" form:"dbTaskId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomDBTaskRollbackInfoRequest) Reset()         { *m = GetCustomDBTaskRollbackInfoRequest{} }
func (m *GetCustomDBTaskRollbackInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomDBTaskRollbackInfoRequest) ProtoMessage()    {}
func (*GetCustomDBTaskRollbackInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f23e371b328c11, []int{0}
}
func (m *GetCustomDBTaskRollbackInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoRequest.Unmarshal(m, b)
}
func (m *GetCustomDBTaskRollbackInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomDBTaskRollbackInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoRequest.Merge(m, src)
}
func (m *GetCustomDBTaskRollbackInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoRequest.Size(m)
}
func (m *GetCustomDBTaskRollbackInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomDBTaskRollbackInfoRequest proto.InternalMessageInfo

func (m *GetCustomDBTaskRollbackInfoRequest) GetDbTaskId() string {
	if m != nil {
		return m.DbTaskId
	}
	return ""
}

//
//GetCustomDBTaskRollbackInfo返回
type GetCustomDBTaskRollbackInfoResponse struct {
	//
	//任务实体ID
	EntityTaskId string `protobuf:"bytes,1,opt,name=entityTaskId,proto3" json:"entityTaskId" form:"entityTaskId"`
	//
	//数据库实例ID
	DbInstanceId string `protobuf:"bytes,2,opt,name=dbInstanceId,proto3" json:"dbInstanceId" form:"dbInstanceId"`
	//
	//数据库实例名称
	DbInstanceName string `protobuf:"bytes,3,opt,name=dbInstanceName,proto3" json:"dbInstanceName" form:"dbInstanceName"`
	//
	//可回退的变更集列表
	ChangesetList        []*GetCustomDBTaskRollbackInfoResponse_ChangesetList `protobuf:"bytes,4,rep,name=changesetList,proto3" json:"changesetList" form:"changesetList"`
	XXX_NoUnkeyedLiteral struct{}                                             `json:"-"`
	XXX_unrecognized     []byte                                               `json:"-"`
	XXX_sizecache        int32                                                `json:"-"`
}

func (m *GetCustomDBTaskRollbackInfoResponse) Reset()         { *m = GetCustomDBTaskRollbackInfoResponse{} }
func (m *GetCustomDBTaskRollbackInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomDBTaskRollbackInfoResponse) ProtoMessage()    {}
func (*GetCustomDBTaskRollbackInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f23e371b328c11, []int{1}
}
func (m *GetCustomDBTaskRollbackInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse.Unmarshal(m, b)
}
func (m *GetCustomDBTaskRollbackInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomDBTaskRollbackInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse.Merge(m, src)
}
func (m *GetCustomDBTaskRollbackInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse.Size(m)
}
func (m *GetCustomDBTaskRollbackInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse proto.InternalMessageInfo

func (m *GetCustomDBTaskRollbackInfoResponse) GetEntityTaskId() string {
	if m != nil {
		return m.EntityTaskId
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponse) GetDbInstanceId() string {
	if m != nil {
		return m.DbInstanceId
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponse) GetDbInstanceName() string {
	if m != nil {
		return m.DbInstanceName
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponse) GetChangesetList() []*GetCustomDBTaskRollbackInfoResponse_ChangesetList {
	if m != nil {
		return m.ChangesetList
	}
	return nil
}

type GetCustomDBTaskRollbackInfoResponse_ChangesetList struct {
	//
	//变更集ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	//
	//变更集名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	//
	//变更SQL
	UpdateSql string `protobuf:"bytes,3,opt,name=updateSql,proto3" json:"updateSql" form:"updateSql"`
	//
	//回退SQL
	RollbackSql          string   `protobuf:"bytes,4,opt,name=rollbackSql,proto3" json:"rollbackSql" form:"rollbackSql"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) Reset() {
	*m = GetCustomDBTaskRollbackInfoResponse_ChangesetList{}
}
func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) String() string {
	return proto.CompactTextString(m)
}
func (*GetCustomDBTaskRollbackInfoResponse_ChangesetList) ProtoMessage() {}
func (*GetCustomDBTaskRollbackInfoResponse_ChangesetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f23e371b328c11, []int{1, 0}
}
func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse_ChangesetList.Unmarshal(m, b)
}
func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse_ChangesetList.Marshal(b, m, deterministic)
}
func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse_ChangesetList.Merge(m, src)
}
func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) XXX_Size() int {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse_ChangesetList.Size(m)
}
func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse_ChangesetList.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomDBTaskRollbackInfoResponse_ChangesetList proto.InternalMessageInfo

func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) GetUpdateSql() string {
	if m != nil {
		return m.UpdateSql
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponse_ChangesetList) GetRollbackSql() string {
	if m != nil {
		return m.RollbackSql
	}
	return ""
}

//
//GetCustomDBTaskRollbackInfoApi返回
type GetCustomDBTaskRollbackInfoResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *GetCustomDBTaskRollbackInfoResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *GetCustomDBTaskRollbackInfoResponseWrapper) Reset() {
	*m = GetCustomDBTaskRollbackInfoResponseWrapper{}
}
func (m *GetCustomDBTaskRollbackInfoResponseWrapper) String() string {
	return proto.CompactTextString(m)
}
func (*GetCustomDBTaskRollbackInfoResponseWrapper) ProtoMessage() {}
func (*GetCustomDBTaskRollbackInfoResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_05f23e371b328c11, []int{2}
}
func (m *GetCustomDBTaskRollbackInfoResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponseWrapper.Unmarshal(m, b)
}
func (m *GetCustomDBTaskRollbackInfoResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponseWrapper.Marshal(b, m, deterministic)
}
func (m *GetCustomDBTaskRollbackInfoResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoResponseWrapper.Merge(m, src)
}
func (m *GetCustomDBTaskRollbackInfoResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_GetCustomDBTaskRollbackInfoResponseWrapper.Size(m)
}
func (m *GetCustomDBTaskRollbackInfoResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomDBTaskRollbackInfoResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomDBTaskRollbackInfoResponseWrapper proto.InternalMessageInfo

func (m *GetCustomDBTaskRollbackInfoResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetCustomDBTaskRollbackInfoResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetCustomDBTaskRollbackInfoResponseWrapper) GetData() *GetCustomDBTaskRollbackInfoResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetCustomDBTaskRollbackInfoRequest)(nil), "dbtask.GetCustomDBTaskRollbackInfoRequest")
	proto.RegisterType((*GetCustomDBTaskRollbackInfoResponse)(nil), "dbtask.GetCustomDBTaskRollbackInfoResponse")
	proto.RegisterType((*GetCustomDBTaskRollbackInfoResponse_ChangesetList)(nil), "dbtask.GetCustomDBTaskRollbackInfoResponse.ChangesetList")
	proto.RegisterType((*GetCustomDBTaskRollbackInfoResponseWrapper)(nil), "dbtask.GetCustomDBTaskRollbackInfoResponseWrapper")
}

func init() {
	proto.RegisterFile("get_custom_dbtask_rollbackinfo.proto", fileDescriptor_05f23e371b328c11)
}

var fileDescriptor_05f23e371b328c11 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0xd5, 0xae, 0x9b, 0xa8, 0xbb, 0xb1, 0xe1, 0x0d, 0x28, 0xbd, 0xc9, 0xe4, 0x55, 0x68,
	0x1a, 0x4a, 0x8b, 0xca, 0x84, 0x18, 0x5c, 0xad, 0x83, 0xa1, 0x4a, 0x08, 0x21, 0x83, 0xc4, 0x05,
	0x82, 0xca, 0x49, 0xdc, 0xcc, 0x6a, 0x6a, 0x67, 0xb1, 0xcb, 0x98, 0x10, 0x97, 0xbc, 0x13, 0x8f,
	0xc2, 0x55, 0x90, 0x78, 0x84, 0x3c, 0x01, 0xb2, 0xdd, 0x76, 0x4e, 0x25, 0xd0, 0xb8, 0x8a, 0xed,
	0xef, 0xfc, 0xe7, 0x9c, 0xff, 0xd8, 0x01, 0xed, 0x98, 0xaa, 0x61, 0x38, 0x95, 0x4a, 0x4c, 0x86,
	0x51, 0xa0, 0x88, 0x1c, 0x0f, 0x33, 0x91, 0x24, 0x01, 0x09, 0xc7, 0x8c, 0x8f, 0x44, 0x27, 0xcd,
	0x84, 0x12, 0x70, 0xcd, 0xa2, 0x96, 0x1f, 0x33, 0x75, 0x36, 0x0d, 0x3a, 0xa1, 0x98, 0x74, 0x63,
	0x11, 0x8b, 0xae, 0xc1, 0xc1, 0x74, 0x64, 0x76, 0x66, 0x63, 0x56, 0x56, 0xd6, 0x7a, 0xec, 0x84,
	0x4f, 0x2e, 0x98, 0x1a, 0x8b, 0x8b, 0x6e, 0x2c, 0x7c, 0x03, 0xfd, 0xcf, 0x24, 0x61, 0x11, 0x51,
	0x22, 0x93, 0xdd, 0xc5, 0xd2, 0xea, 0x50, 0x02, 0xd0, 0x4b, 0xaa, 0x4e, 0x4c, 0x57, 0xcf, 0xfb,
	0xef, 0x88, 0x1c, 0xe3, 0x59, 0x4f, 0x03, 0x3e, 0x12, 0x98, 0x9e, 0x4f, 0xa9, 0x54, 0xf0, 0x14,
	0xdc, 0x88, 0x02, 0x0d, 0x07, 0x51, 0xb3, 0xb2, 0x5b, 0xd9, 0xaf, 0xf7, 0x0f, 0x8a, 0xdc, 0xdb,
	0x1c, 0x89, 0x6c, 0xf2, 0x14, 0xcd, 0x09, 0xfa, 0xfd, 0xcb, 0xdb, 0x06, 0xb7, 0x3e, 0x7d, 0x78,
	0xe8, 0x1f, 0x11, 0x7f, 0x74, 0xec, 0x9f, 0x7e, 0xfc, 0xda, 0x3b, 0xfc, 0xd6, 0xc6, 0x0b, 0x2d,
	0xfa, 0x51, 0x03, 0x7b, 0xff, 0x2c, 0x27, 0x53, 0xc1, 0x25, 0x85, 0xcf, 0xc0, 0x3a, 0xe5, 0x8a,
	0xa9, 0xcb, 0x52, 0xcd, 0xbb, 0x45, 0xee, 0x6d, 0xdb, 0x9a, 0x2e, 0x45, 0xb8, 0x14, 0xac, 0xc5,
	0x51, 0x30, 0xe0, 0x52, 0x11, 0x1e, 0xd2, 0x41, 0xd4, 0xac, 0x2e, 0x8b, 0x5d, 0x8a, 0x70, 0x29,
	0x18, 0x1e, 0x83, 0x9b, 0x57, 0xfb, 0xd7, 0x64, 0x42, 0x9b, 0x2b, 0x46, 0x7e, 0xaf, 0xc8, 0xbd,
	0xdb, 0xcb, 0x72, 0xcd, 0x11, 0x5e, 0x12, 0xc0, 0x4b, 0xb0, 0x11, 0x9e, 0x11, 0x1e, 0x53, 0x49,
	0xd5, 0x2b, 0x26, 0x55, 0xb3, 0xb6, 0xbb, 0xb2, 0xdf, 0xe8, 0x1d, 0x75, 0xec, 0xcd, 0x76, 0xae,
	0x31, 0x80, 0xce, 0x89, 0x9b, 0xa0, 0xdf, 0x2c, 0x72, 0x6f, 0xc7, 0x16, 0x2f, 0x65, 0x46, 0xb8,
	0x5c, 0xa9, 0xf5, 0xb3, 0x02, 0x36, 0x4a, 0x52, 0x78, 0x08, 0xaa, 0x6c, 0x3e, 0xbf, 0x76, 0x91,
	0x7b, 0x75, 0x9b, 0x86, 0xfd, 0xfd, 0xb6, 0xaa, 0x2c, 0x82, 0x7b, 0xa0, 0xc6, 0xb5, 0x77, 0x3b,
	0xba, 0xcd, 0x22, 0xf7, 0x1a, 0x56, 0xc7, 0x8d, 0x63, 0x03, 0x61, 0x0f, 0xd4, 0xa7, 0x69, 0x44,
	0x14, 0x7d, 0x7b, 0x9e, 0xcc, 0xa6, 0xb4, 0x53, 0xe4, 0xde, 0x96, 0x8d, 0x5c, 0x20, 0x84, 0xaf,
	0xc2, 0xe0, 0x13, 0xd0, 0x98, 0xbf, 0x79, 0xad, 0xaa, 0x19, 0xd5, 0x9d, 0x22, 0xf7, 0xa0, 0x55,
	0x39, 0x10, 0x61, 0x37, 0x14, 0x7d, 0xaf, 0x82, 0x83, 0x6b, 0x4c, 0xee, 0x7d, 0x46, 0xd2, 0x94,
	0x66, 0xda, 0x41, 0x28, 0x22, 0x6a, 0x9c, 0xaf, 0xba, 0x0e, 0xf4, 0x29, 0xc2, 0x06, 0xea, 0x6e,
	0xf4, 0xf7, 0xc5, 0x97, 0x34, 0x21, 0x8c, 0xcf, 0xdc, 0x3a, 0xdd, 0x38, 0x10, 0x61, 0x37, 0x14,
	0xde, 0x07, 0xab, 0x34, 0xcb, 0x44, 0x36, 0xf3, 0xbd, 0x55, 0xe4, 0xde, 0xfa, 0xec, 0x65, 0xea,
	0x63, 0x84, 0x2d, 0x86, 0x6f, 0x40, 0x2d, 0x22, 0x8a, 0x18, 0xa3, 0x8d, 0xde, 0x83, 0xff, 0x78,
	0x02, 0x6e, 0xcf, 0x3a, 0x05, 0xc2, 0x26, 0x53, 0xb0, 0x66, 0xfe, 0xdb, 0x47, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x4b, 0xd1, 0xca, 0x4e, 0x04, 0x00, 0x00,
}
