// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: influxdb_proxy.proto

package influxdb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
//InfluxdbProxy请求
type InfluxdbProxyRequest struct {
	//
	//数据库
	Db string `protobuf:"bytes,1,opt,name=db,proto3" json:"db" form:"db"`
	//
	//SQL语句
	Q string `protobuf:"bytes,2,opt,name=q,proto3" json:"q" form:"q"`
	//
	//返回时间戳的精度
	Epoch                string   `protobuf:"bytes,3,opt,name=epoch,proto3" json:"epoch" form:"epoch"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfluxdbProxyRequest) Reset()         { *m = InfluxdbProxyRequest{} }
func (m *InfluxdbProxyRequest) String() string { return proto.CompactTextString(m) }
func (*InfluxdbProxyRequest) ProtoMessage()    {}
func (*InfluxdbProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9db21d273b69a2f, []int{0}
}
func (m *InfluxdbProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxdbProxyRequest.Unmarshal(m, b)
}
func (m *InfluxdbProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxdbProxyRequest.Marshal(b, m, deterministic)
}
func (m *InfluxdbProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxdbProxyRequest.Merge(m, src)
}
func (m *InfluxdbProxyRequest) XXX_Size() int {
	return xxx_messageInfo_InfluxdbProxyRequest.Size(m)
}
func (m *InfluxdbProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxdbProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxdbProxyRequest proto.InternalMessageInfo

func (m *InfluxdbProxyRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *InfluxdbProxyRequest) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *InfluxdbProxyRequest) GetEpoch() string {
	if m != nil {
		return m.Epoch
	}
	return ""
}

//
//InfluxdbProxy返回
type InfluxdbProxyResponse struct {
	//
	//返回的数据
	Results              []*InfluxdbProxyResponse_Results `protobuf:"bytes,1,rep,name=results,proto3" json:"results" form:"results"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *InfluxdbProxyResponse) Reset()         { *m = InfluxdbProxyResponse{} }
func (m *InfluxdbProxyResponse) String() string { return proto.CompactTextString(m) }
func (*InfluxdbProxyResponse) ProtoMessage()    {}
func (*InfluxdbProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9db21d273b69a2f, []int{1}
}
func (m *InfluxdbProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxdbProxyResponse.Unmarshal(m, b)
}
func (m *InfluxdbProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxdbProxyResponse.Marshal(b, m, deterministic)
}
func (m *InfluxdbProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxdbProxyResponse.Merge(m, src)
}
func (m *InfluxdbProxyResponse) XXX_Size() int {
	return xxx_messageInfo_InfluxdbProxyResponse.Size(m)
}
func (m *InfluxdbProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxdbProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxdbProxyResponse proto.InternalMessageInfo

func (m *InfluxdbProxyResponse) GetResults() []*InfluxdbProxyResponse_Results {
	if m != nil {
		return m.Results
	}
	return nil
}

type InfluxdbProxyResponse_Results struct {
	//
	//series
	Series []*InfluxdbProxyResponse_Results_Series `protobuf:"bytes,1,rep,name=series,proto3" json:"series" form:"series"`
	//
	//error
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error" form:"error"`
	//
	//statement_id
	StatementId          int32    `protobuf:"varint,3,opt,name=statement_id,json=statementId,proto3" json:"statement_id" form:"statement_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfluxdbProxyResponse_Results) Reset()         { *m = InfluxdbProxyResponse_Results{} }
func (m *InfluxdbProxyResponse_Results) String() string { return proto.CompactTextString(m) }
func (*InfluxdbProxyResponse_Results) ProtoMessage()    {}
func (*InfluxdbProxyResponse_Results) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9db21d273b69a2f, []int{1, 0}
}
func (m *InfluxdbProxyResponse_Results) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxdbProxyResponse_Results.Unmarshal(m, b)
}
func (m *InfluxdbProxyResponse_Results) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxdbProxyResponse_Results.Marshal(b, m, deterministic)
}
func (m *InfluxdbProxyResponse_Results) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxdbProxyResponse_Results.Merge(m, src)
}
func (m *InfluxdbProxyResponse_Results) XXX_Size() int {
	return xxx_messageInfo_InfluxdbProxyResponse_Results.Size(m)
}
func (m *InfluxdbProxyResponse_Results) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxdbProxyResponse_Results.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxdbProxyResponse_Results proto.InternalMessageInfo

func (m *InfluxdbProxyResponse_Results) GetSeries() []*InfluxdbProxyResponse_Results_Series {
	if m != nil {
		return m.Series
	}
	return nil
}

func (m *InfluxdbProxyResponse_Results) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *InfluxdbProxyResponse_Results) GetStatementId() int32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

type InfluxdbProxyResponse_Results_Series struct {
	//
	//指标值（是一个二维表），根据sql不同而不同，他的列在columns标明
	Values *types.Value `protobuf:"bytes,1,opt,name=values,proto3" json:"values" form:"values"`
	//
	//表名
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" form:"name"`
	//
	//列名
	Columns []string `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns" form:"columns"`
	//
	//tags
	Tags                 *types.Struct `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags" form:"tags"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InfluxdbProxyResponse_Results_Series) Reset()         { *m = InfluxdbProxyResponse_Results_Series{} }
func (m *InfluxdbProxyResponse_Results_Series) String() string { return proto.CompactTextString(m) }
func (*InfluxdbProxyResponse_Results_Series) ProtoMessage()    {}
func (*InfluxdbProxyResponse_Results_Series) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9db21d273b69a2f, []int{1, 0, 0}
}
func (m *InfluxdbProxyResponse_Results_Series) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxdbProxyResponse_Results_Series.Unmarshal(m, b)
}
func (m *InfluxdbProxyResponse_Results_Series) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxdbProxyResponse_Results_Series.Marshal(b, m, deterministic)
}
func (m *InfluxdbProxyResponse_Results_Series) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxdbProxyResponse_Results_Series.Merge(m, src)
}
func (m *InfluxdbProxyResponse_Results_Series) XXX_Size() int {
	return xxx_messageInfo_InfluxdbProxyResponse_Results_Series.Size(m)
}
func (m *InfluxdbProxyResponse_Results_Series) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxdbProxyResponse_Results_Series.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxdbProxyResponse_Results_Series proto.InternalMessageInfo

func (m *InfluxdbProxyResponse_Results_Series) GetValues() *types.Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *InfluxdbProxyResponse_Results_Series) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InfluxdbProxyResponse_Results_Series) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *InfluxdbProxyResponse_Results_Series) GetTags() *types.Struct {
	if m != nil {
		return m.Tags
	}
	return nil
}

//
//InfluxdbProxyApi返回
type InfluxdbProxyResponseWrapper struct {
	//
	//返回码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//
	//返回码解释
	CodeExplain string `protobuf:"bytes,2,opt,name=codeExplain,proto3" json:"codeExplain" form:"codeExplain"`
	//
	//错误详情
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error" form:"error"`
	//
	//返回数据
	Data                 *InfluxdbProxyResponse `protobuf:"bytes,4,opt,name=data,proto3" json:"data" form:"data"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *InfluxdbProxyResponseWrapper) Reset()         { *m = InfluxdbProxyResponseWrapper{} }
func (m *InfluxdbProxyResponseWrapper) String() string { return proto.CompactTextString(m) }
func (*InfluxdbProxyResponseWrapper) ProtoMessage()    {}
func (*InfluxdbProxyResponseWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9db21d273b69a2f, []int{2}
}
func (m *InfluxdbProxyResponseWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxdbProxyResponseWrapper.Unmarshal(m, b)
}
func (m *InfluxdbProxyResponseWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxdbProxyResponseWrapper.Marshal(b, m, deterministic)
}
func (m *InfluxdbProxyResponseWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxdbProxyResponseWrapper.Merge(m, src)
}
func (m *InfluxdbProxyResponseWrapper) XXX_Size() int {
	return xxx_messageInfo_InfluxdbProxyResponseWrapper.Size(m)
}
func (m *InfluxdbProxyResponseWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxdbProxyResponseWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxdbProxyResponseWrapper proto.InternalMessageInfo

func (m *InfluxdbProxyResponseWrapper) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *InfluxdbProxyResponseWrapper) GetCodeExplain() string {
	if m != nil {
		return m.CodeExplain
	}
	return ""
}

func (m *InfluxdbProxyResponseWrapper) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *InfluxdbProxyResponseWrapper) GetData() *InfluxdbProxyResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InfluxdbProxyRequest)(nil), "influxdb.InfluxdbProxyRequest")
	proto.RegisterType((*InfluxdbProxyResponse)(nil), "influxdb.InfluxdbProxyResponse")
	proto.RegisterType((*InfluxdbProxyResponse_Results)(nil), "influxdb.InfluxdbProxyResponse.Results")
	proto.RegisterType((*InfluxdbProxyResponse_Results_Series)(nil), "influxdb.InfluxdbProxyResponse.Results.Series")
	proto.RegisterType((*InfluxdbProxyResponseWrapper)(nil), "influxdb.InfluxdbProxyResponseWrapper")
}

func init() { proto.RegisterFile("influxdb_proxy.proto", fileDescriptor_d9db21d273b69a2f) }

var fileDescriptor_d9db21d273b69a2f = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x6e, 0xd4, 0x3c,
	0x14, 0x55, 0x26, 0xf3, 0xd3, 0x71, 0xa6, 0xdf, 0x07, 0xa6, 0xb4, 0x51, 0x54, 0x94, 0x91, 0x91,
	0x60, 0x16, 0xe0, 0x4a, 0x65, 0x83, 0x2a, 0x36, 0x8c, 0x60, 0xd1, 0x1d, 0x72, 0x05, 0x88, 0x55,
	0x95, 0x1f, 0x4f, 0x1a, 0x29, 0x89, 0x33, 0xb6, 0x83, 0xa6, 0x6f, 0xc2, 0x1b, 0xf0, 0x52, 0x28,
	0x2f, 0xc0, 0x2e, 0x4f, 0x80, 0xfc, 0x13, 0x26, 0x82, 0x0a, 0x58, 0x25, 0xbe, 0xe7, 0xdc, 0x7b,
	0xce, 0xf1, 0x35, 0x38, 0xca, 0xab, 0x4d, 0xd1, 0xec, 0xd2, 0xf8, 0xba, 0xe6, 0x6c, 0x77, 0x8b,
	0x6b, 0xce, 0x24, 0x83, 0x07, 0x7d, 0x35, 0x78, 0x9e, 0xe5, 0xf2, 0xa6, 0x89, 0x71, 0xc2, 0xca,
	0xb3, 0x8c, 0x65, 0xec, 0x4c, 0x13, 0xe2, 0x66, 0xa3, 0x4f, 0xfa, 0xa0, 0xff, 0x4c, 0x63, 0x70,
	0x9a, 0x31, 0x96, 0x15, 0x74, 0xcf, 0x12, 0x92, 0x37, 0x89, 0x34, 0x28, 0xba, 0x05, 0x47, 0x97,
	0x76, 0xf0, 0x3b, 0xa5, 0x46, 0xe8, 0xb6, 0xa1, 0x42, 0xc2, 0x47, 0x60, 0x94, 0xc6, 0xbe, 0xb3,
	0x74, 0x56, 0xf3, 0xf5, 0x61, 0xd7, 0x86, 0xf3, 0x0d, 0xe3, 0xe5, 0x05, 0x4a, 0x63, 0x44, 0x46,
	0x69, 0x0c, 0x03, 0xe0, 0x6c, 0xfd, 0x91, 0x46, 0x17, 0x5d, 0x1b, 0x1e, 0x18, 0x74, 0x8b, 0x88,
	0xb3, 0x85, 0x4f, 0xc0, 0x84, 0xd6, 0x2c, 0xb9, 0xf1, 0x5d, 0x8d, 0xdf, 0xeb, 0xda, 0x70, 0x61,
	0x70, 0x5d, 0x46, 0xc4, 0xc0, 0xe8, 0xcb, 0x18, 0x3c, 0xfc, 0x45, 0x5b, 0xd4, 0xac, 0x12, 0x14,
	0xbe, 0x07, 0x33, 0x4e, 0x45, 0x53, 0x48, 0xe1, 0x3b, 0x4b, 0x77, 0xe5, 0x9d, 0x3f, 0xc5, 0x7d,
	0x7a, 0x7c, 0x67, 0x07, 0x26, 0x86, 0xbe, 0x86, 0x5d, 0x1b, 0xfe, 0x67, 0xc4, 0xec, 0x04, 0x44,
	0xfa, 0x59, 0xc1, 0x57, 0x17, 0xcc, 0x2c, 0x11, 0x7e, 0x02, 0x53, 0x41, 0x79, 0x4e, 0x7b, 0x05,
	0xfc, 0x8f, 0x0a, 0xf8, 0x4a, 0x77, 0xad, 0xef, 0x77, 0x6d, 0x78, 0x68, 0x84, 0xcc, 0x1c, 0x44,
	0xec, 0x40, 0x9d, 0x9f, 0x73, 0xc6, 0xed, 0xfd, 0x0c, 0xf3, 0xab, 0xb2, 0xca, 0xaf, 0xbe, 0xf0,
	0x02, 0x2c, 0x84, 0x8c, 0x24, 0x2d, 0x69, 0x25, 0xaf, 0xf3, 0x54, 0x5f, 0xd7, 0x64, 0x7d, 0xd2,
	0xb5, 0xe1, 0x03, 0x3b, 0x78, 0x80, 0x22, 0xe2, 0xfd, 0x3c, 0x5e, 0xa6, 0xc1, 0x37, 0x07, 0x4c,
	0x8d, 0x13, 0xf8, 0x1a, 0x4c, 0x3f, 0x47, 0x45, 0xa3, 0x93, 0x38, 0x2b, 0xef, 0xfc, 0x18, 0x9b,
	0x85, 0xe3, 0x7e, 0xe1, 0xf8, 0x83, 0x82, 0x87, 0x8e, 0x0d, 0x1f, 0x11, 0xdb, 0x08, 0x1f, 0x83,
	0x71, 0x15, 0x95, 0xd4, 0x1a, 0xfe, 0xbf, 0x6b, 0x43, 0xcf, 0x10, 0x55, 0x15, 0x11, 0x0d, 0xc2,
	0x67, 0x60, 0x96, 0xb0, 0xa2, 0x29, 0x2b, 0xe1, 0xbb, 0x4b, 0x77, 0x35, 0x1f, 0xde, 0xb5, 0x05,
	0x10, 0xe9, 0x29, 0xf0, 0x15, 0x18, 0xcb, 0x28, 0x13, 0xfe, 0x58, 0x7b, 0x3a, 0xf9, 0xcd, 0xd3,
	0x95, 0x7e, 0x84, 0x43, 0x2d, 0x45, 0x47, 0x44, 0x77, 0xa1, 0xef, 0x0e, 0x38, 0xbd, 0x73, 0x0d,
	0x1f, 0x79, 0x54, 0xd7, 0x94, 0x2b, 0xc7, 0x09, 0x4b, 0xa9, 0x8e, 0x3c, 0x19, 0x4e, 0x51, 0x55,
	0x44, 0x34, 0x08, 0x5f, 0x02, 0x4f, 0x7d, 0xdf, 0xee, 0xea, 0x22, 0xca, 0x2b, 0x9b, 0xee, 0xb8,
	0x6b, 0x43, 0xb8, 0xe7, 0x5a, 0x10, 0x91, 0x21, 0x75, 0xbf, 0x42, 0xf7, 0xcf, 0x2b, 0x7c, 0x03,
	0xc6, 0x69, 0x24, 0x23, 0x9b, 0x32, 0xfc, 0xcb, 0x1b, 0x1a, 0xfa, 0x54, 0x6d, 0x88, 0xe8, 0xee,
	0x78, 0xaa, 0x6f, 0xe5, 0xc5, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x23, 0x28, 0x2b, 0xf9,
	0x03, 0x00, 0x00,
}
